import random

import requests
import tweepy
parks_and_rec_quotes = {
    1: "'Everything hurts and I’m dying.' -Leslie Knope",
    2: "'There’s only one thing I hate more than lying: skim milk. Which is water that is lying about being milk.' -Ron Swanson",
    3: "'Time is money; Money is power; Power is pizza; Pizza is knowledge. Let’s go!' -April Ludgate",
    4: "'I am a goddess, a glorious female warrior.' -Leslie Knope",
    5: "'Just remember, every time you look up at the moon, I, too, will be looking at a moon. Not the same moon, obviously, That’s impossible.' -Andy Dwyer",
    6: "'Sometimes you gotta work a little so you can ball a lot.' -Tom Haverford",
    7: "'We have to remember what’s important in life: friends, waffles, and work. Or waffles, friends, work. But work has to come third.' -Leslie Knope",
    8: "'Hey, Leslie. It’s Leslie. Hang in there. I love you. Bye.' -Leslie Knope"
    9: "'If I keep my body moving, and my mind occupied at all times, I will avoid falling into a bottomless pit of despair.' -Chris Traeger",
    10: "'What I hear when I’m being yelled at is people caring really loudly at me.' -Leslie Knope",
    11: "'Do you think that marrying penguins made some kind of statement?' -Leslie Knope",
    12: "'Are you kidding me? Sell baby, sell! Could you imagine the Treat Yo’Self day we could have? It would be pedicures on top of pedicures on top of pedicures.' -Donna Meagle",
    13: "'I’m fine. It’s just that life is pointless and nothing matters and I’m always tired.' -Andy Dwyer",
    14: "'Put some alcohol in your mouth to block with words from coming out.' -Ron Swanson",
    15: "'I’m big enough to admit that I am often inspired by myself.' -Leslie Knope",
    16: "'Boss man, I wanna go home early. Ooh, hold on actually, hang on. Yeah, no, I wanna quit and never come here again.' -Mona-Lisa Saperstein",
    17: "'There’s nothing we can’t do if we work hard, never sleep, and shirk from all other responsibilities in our lives.' -Leslie Knope",
    18: "'I once forgot to brush my teeth for five weeks. I didn’t actually sell my car, I just forgot where I parked it. I don’t know who Al Gore is, and at this point, I’m too afraid to ask. When they say two percent milk, I don’t know what the other 98 percent is. When I was a baby, my head was so big scientists did experiments on me. I once threw beer at a swan and then it attacked my niece, Rebecca.' -Andy Dwyer",
    19: "'I think you’ve got several options. They’re all terrible… but you have them.' -Chris Traeger",
    20: "'My first ex-wife’s name is Tammy. My second ex-wife’s name is Tammy. My Mom’s name is Tamara… she goes by Tammy.' -Ron Swanson",
    21: "'One person’s annoying is another’s inspiring and heroic.' -Leslie Knope",
    22: "'I’m gonna buy some sweatpants and a Nicholas Sparks novel. Might as well lean into it.' -Tom Haverford",
    23: "'You have all the strengths.' -Leslie Knope",
    24: "'No matter what I do, literally nothing bad can happen to me. I’m like a white, male U.S. Senator.' -Leslie Knope",
    25: "'Thank god my grandfather just died, so I am fluh-uh-shed with ca-ah-ash.' -Jean-Ralphio",
    26: "'Treat yo self.' -Donna Meagle and Tom Haverford",
    27: "'All I need to do is focus and stay calm.' -Leslie Knope",
    28: "'Who hasn’t had gay thoughts?' -Ben Wyatt",
    29: "'Do you know how much fun gay Halloween parties are? Last year, I saw three Jonas Brothers make out with three Robert Pattinsons. It was amazing.' -April Ludgate",
    30: "'Do it. Fierce. Power.' -Leslie Knope",
    31: "'These dogs are so cute I want to throw up and kill myself.' -Craig Middlebrooks",
    32: "'Goodbye, Ann Perkins, my faithful employee. Hello, Ann Perkins, my fallopian princess.' -Chris Traeger",
    33: "'I’m a simple man. I like pretty, dark-haired women, and breakfast food.' -Ron Swanson",
    34: "'Can we have ONE conversation about feminism where MEN get to be in charge?' -Kipp Bunthart",
    35: "'I stand behind my decision to avoid salad and other disgusting things.' -Leslie Knope",
    36: "'His name is Champion because he’s the dog world champion.' -Andy Dwyer",
    37: "'I totally hear you, but, erm, I also don’t like what you’re saying. So if you say no, I will start a fire in the bathroom.' -Mona-Lisa Saperstein",
    38: "'When Andy and I used to go the movies, he would always try to guess the ending of the movie. And he would always guess that the main character had been dead the whole time. Even when we saw Ratatouille.' -Ann Perkins",
    39: "'Oh Ann, you beautiful tropical fish.' -Leslie Knope",
    40: "'Bababooey.' -Ben Wyatt",
    41: "'LITerally.' -Chris Traeger",
    42: "'It’s like I always say. When life gives you lemons, you sell some of your grandma’s jewelry, and go clubbing.' -Jean-Ralphio",
    43: "'Say goodbye to your father.' -Orin",
    44: "'I ate a brownie once at a party in college. It was intense. It was kind of indescribable, actually. I felt like I was floating. Turns out there wasn’t any pot in the brownie, it was just an insanely good brownie.' -Leslie Knope",
    45: "'Do I look like I drink water?' -Donna Meagle",
    46: "'This is so awesome. We are like Robin Hood. We steal from the club and give to ourselves.' -Andy Dwyer",
    47: "'If I keep my body moving, and my mind occupied at all times, I will avoid falling into a bottomless pit of despair.' -Chris Traeger",
    48: "'You know my code. Hoes before bros. Uteruses before duderuses. Ovaries before brovaries.' -Leslie Knope",
    49: "'Jogging is the worst. I know it keeps you healthy, but God, at what cost?' -Ann Perkins",
    50: "'Red carpet. My entire apartment is red carpet. On top of that, leading into my bedroom, a second red carpet. Oh, what’s this in my shoe? Red carpet insole. Everywhere I go, I’m walking on red carpet.' -Tom Haverford",
    51: "'I believe assault should be legal if the person is a jerk.' -Leslie Knope",
    52: "'One time I waited outside a woman’s house for five days just to show her how serious I was about wanting to drill her. Turns out, it was the wrong house. She loved the story anyway. We got to third base. Over the pants.' -Jean-Ralphio",
    53: "'Oh my god! (catches calculator) Hey, Dr. Buttons! I mean, my old calculator. It doesn’t have a name.' -Ben Wyatt",
    54: "'There has never been a sadness that can’t be cured by breakfast food.' -Ron Swanson",
    55: "'My only official recommendations are U.S. Army-issued mustache trimmers, Morton’s Salt, and the C.R. Lawrence Fein two-inch ax-style scraper oscillating knife blade.' -Leslie Knope",
    56: "'When life gives you lemons, make lemonade. I read that one on a can of lemonade. I like to think it applies to life.' -Andy Dwyer",
    57: "'If I had to have anybody tell me that I have cancer, I would want it to be me.' -Chris Traeger",
    58: "'It’s not my favorite shirt… but it is my least favorite shirt.' -Donna Meagle",
    59: "'A couple more rules: if you ever watch a sad movie, you have to wear mascara so we can see whether or not you’ve been crying. There’s no noise allowed on Mondays. And no TV after breakfast.' -April Ludgate",
    60: "'I guess my thoughts on abortion are, you know, let’s all just have a good time.' -Bobby Newport",
    61: "'I am super chill all the time.' -Leslie Knope",
    62: "'Strippers do nothing for me… but I will take a free breakfast buffet anytime, anyplace.' -Ron Swanson",
    63: "'Are you duking on my chest right now?' -Councilman Jamm",
    64: "'Pawnee’s Library Department is the most diabolical, ruthless bunch of bureaucrats I’ve ever seen. They’re like a biker gang, but instead of shotguns and crystal meth they use political savvy and shhhing.' -Leslie Knope",
    65: "'I really only listen to, like, German Death Reggae and Halloween sound effects records from the 1950s. And Bette Midler. Obviously.' -April Ludgate",
    66: "'No, that’s Buckingham Palace. Hogwarts is fictional. You do know that, don’t you? It’s important to me that you know that.' -Ben Wyatt",
    67: "'I know what things are.' -Andy Dwyer",
    68: "'Oh, I love any book about vampires, werewolves, monsters, zombies, sorcerers, beasties, or time-traveling romances. And if I had an hour alone with Robert Pattinson, he would forget all about Skinny Legs Magee, I’ll tell you that much.' -Donna Meagle",
    69: "'Stop. Pooping.' -Chris Traeger",
    70: "'If I had a stripper’s name, it would be Equality.' -Leslie Knope",
    71: "'Birthdays were invented by Hallmark to sell cards.' -Ron Swanson",
    72: "'Well, I salsa your face.' -Ann Perkins",
    73: "'You know, in the 1880s, there were a few years that were pretty rough and tumble in Pawnee. This depicts kind of a famous fight between Reverend Bradley and Annabeth Stevenson, a widowed mother of seven. The original title of this was ‘A Lively Fisting.’ But y’know, they had to change it for… obvious reasons.' -Leslie Knope",
    74: "'Horizons are dumb. Never broaden your horizons.' -April Ludgate",
    75: "'I regret nothing. The end.' -Ron Swanson",
    76: "'Most people would say ‘the deets,’ but I say ‘the tails.’ Just another example of innovation.' -Tom Haverford",
    77: "'I don’t want to be overdramatic, but today felt like a hundred years in h*ll and the absolute worst day of my life.' -Leslie Knope",
    78: "'Lucky for me, I’ve processed all my feelings. And I’ve gone through the five stages of grief: Denial, anger, internet commenting, cat adoption, African dance, cat returning to the adoption place, watching all the episodes of Murphy Brown, and not giving a flying fart.' -Leslie Knope",
    79: "'Idaho cut their parks department by 80 percent. And Idaho is basically one giant park.' -Ben Wyatt",
    80: "'The raccoon problem is under control. They have their part of the town and we have ours.' -Leslie Knope",
    81: "'I’m allergic to sushi. Every time I eat more than 80 sushis, I barf.' -Andy Dwyer",
    82: "'Guys love it when you can show them you’re better than they are at something they love.' -Leslie Knope",
    83: "'Clear alcohols are for rich women on diets.' -Ron Swanson",
    84: "'I’ll have a glass of your most expensive red wine mixed with a glass of your cheapest white wine served in a dog bowl. Silly straws all around, please.' -April Ludgate",
    85: "'This seems like the type of place where a Ska band would go to shoot heroin.' -Ann Perkins",
    86: "'I have never taken the high road. But I tell other people to ‘cause then there’s more room for me on the low road.' -Tom Haverford",
    87: "'I’m gonna get drunk and then I’m gonna order a three-course meal where each course is made of dessert.' -Leslie Knope",
    88: "'There are three acceptable haircuts: high and tight, crew cut, buzz cut.' -Ron Swanson",
    89: "'Ugh. I hate talking to people about things.' -April Ludgate",
    90: "'I’m fine. It’s just that life is pointless and nothing matters and I’m always tired.' -Andy Dwyer",
    91: "'I’m sorry, I have to ask this, but how many legs did that dog have when you found him?' -Ben Wyatt",
    92: "'I promised myself I was not going to cry tonight, and I’ve already broken that promise five times. But I will not break it a sixth.' -Chris Traeger",
    93: "'I wonder who else was born in Eagleton. Voldemort, probably.' -Leslie Knope",
    94: "'The air is so fresh. It’s disgusting.' -April Ludgate",
    95: "'No one achieves anything alone.' -Leslie Knope",
    96: "'On a scale of one to Chris Brown, how pissed is he?' -Tom Haverford",
    97: "'I hope no one minds if I live-tweet this b*tch.' -Donna Meagle",
    98: "'Do you think a depressed person could make this? No!' -Ben Wyatt",
    99: "'She’s the woooooorst!' -Jean-Ralphio",
    100: "'I have no idea what I’m doing, but I know I’m doing it really, really well.' -Andy Dwyer",
    101: "'Calzones are pointless. They’re just pizza that’s harder to eat. No one likes them.' -Leslie Knope",
    102: "'I want to be a giant head and mouth, and just eat rows and rows of junk food pellets.' -Ann Perkins",
    103: "'My body is finely tuned, like a microchip, and the flu is like a grain of sand. It could literally shut down the entire system.' -Chris Traeger",
    104: "'She’s the worst person I’ve ever met. I want to travel the world with her.' -April Ludgate",
    105: "'I guess some people object to powerful depictions of awesome ladies.' -Leslie Knope",
    106: "'Use him. Abuse him. Lose him. That’s the Meagle motto.' -Donna Meagle",
    107: "'I tried to make ramen in the coffee pot and broke everything.' -Andy Dwyer",
    108: "'I call noodles: long-a*s rice.' -Tom Haverford",
    109: "'I care. I care a lot. It’s kinda my thing.' -Leslie Knope",
    110: "'Pizza? Never heard of it.' -Ben Wyatt",
    111: "'I haven’t felt this good in years. And it’s not just because of the supplements he has me taking and the soluble fiber and the increase in regularity. It’s him.' -Ann Perkins",
    112: "'I have the toes I have, let’s leave it at that.' -Ron Swanson",
    113: "'You’re ridiculous and men’s rights is nothing.' -Leslie Knope",
    114: "'I would like a glass of red wine and I’ll take the cheapest one you have because I can’t tell the difference.' -Leslie Knope",
    115: "'What’s Galentine’s Day? Oh, it’s only the best day of the year.' -Leslie Knope",
    116: "'Ladies celebrating ladies. It’s like Lilith Fair, minus the angst.' -Leslie Knope",
    117: "'The less I know about other people’s affairs, the happier I am. I’m not interested in caring about people. I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.' -Ron Swanson",
    118: "'Dear frozen yogurt, you are the celery of desserts. Be ice cream, or be nothing.' -Ron Swanson",
    119: "'When I eat, it is the food that is scared.' -Ron Swanson",
    120: "'If you don’t believe in love, what’s the point of living?' -Ron Swanson",
    121: "'I love games that turn people against each other.' -April Ludgate",
    122: "'I love you guys! And Ann specifically.' -Leslie Knope",
    123: "'Ann, you opalescent tree shark.' -Leslie Knope",
    124: "'Ann, there is nothing harder in the entire world than saying no to your beautiful face.' -Leslie Knope",
    125: "'Ann, you’re so sweet and innocent and pretty.' -Leslie Knope",
    126: "'I got run over by a Lexus!' -Jean-Ralphio",
    127: "'K to the N to the O P E, she’s the dopest littler shorty in all Pawnee. Indiana.' -Jean-Ralphio",
    128: "'I hope you brought a change of clothes. Your eyes are about to piss tears.' -Jean-Ralphio",
    129: "'I had a small part in Argo. As well as the porn version, Our Goo.' -Brandy Maxx",
    130: "'Daddy, someone started a fire in your car because you took too long and (sings) I got bored.' -Mona-Lisa Saperstein",
    131: "'I totally hear you, but erm, I also don’t like what you’re saying. So, if you say no, I’m going to start a fire in the bathroom.' -Mona-Lisa Saperstein",
    132: "'Money pleeeeeeeeeeeeeaaaaasssseeee!' -Mona-Lisa Saperstein",
    133: "'Why don’t you turn that frizown upsidizity.' -Jean-Ralphio",
    134: "'I’ve been quite open about this around the office: I don’t want this parks department to build any parks because I don’t believe in government. I think that all government is a waste of taxpayer money. My dream is to have the park system privatized and run entirely by for-profit corporations, like Chuck E. Cheese. They have an impeccable business model. I would rather work for Chuck E. Cheese.' -Ron Swanson",
    135: "'The Tucker Park Graffiti Removal Project was a great idea that just ran out of steam. We had removed five cartoon penises — not even 10 percent when we were shut down due to lack of funding. To this day, I am haunted by those remaining penises. One penis in particular…' -Leslie Knope",
    136: "'Leslie, I typed your symptoms into the thing up here, and it says you could have network connectivity problems.' -Andy Dwyer",
    137: "'I am big enough to admit that I am often inspired by myself.' -Leslie Knope",
    138: "'Now, go find your team, and get to work.' -Leslie Knope",
}

def get_random_parks_and_rec_quote():
    # 50% chance of using api, 50% chance of using my quote
    api = True if random.randint(0,1) == 1 else False

    url = "https://parks-and-rec-api.frozencoast05.workers.dev/quote/random"
    response = requests.get(url)

    if response.status_code != 200:
        return
    data = response.json()
    print(f'"{data["quote"]}" –{data["character"]}')



# Fetch and print a random Parks and Rec quote
get_random_parks_and_rec_quote()
