import random
import boto3
import tweepy
import os
import json
import re

questions = {
    1: "Who do you support: Rebellion or Empire?",
    2: "Stormtrooper or Clone Trooper?",
    3: "Tie Fighter or X-Wing?",
    4: "Prequels or Sequels?",
    5: "What's your favorite Star Wars movie?",
    6: "Who's your favorite Star Wars character?",
    7: "What are your opinions on the Gonk Droid?",
    8: "Do you want to see Grand Moff Tarkin in future projects?",
    9: "Oh you're a Star Wars fan? Name every Star.",
    10: "What are your thoughts on the KOTOR remake?",
    11: "What are your thoughts on Star Wars Resistance?",
    12: "What are your opinions on Star Wars Rebels?",
    13: "What are your thoughts on the OG Clone Wars show (2003)?",
    14: "Did you like The Clone Wars?",
    15: "What are your thoughts on The Mandalorian TV Show?",
    16: "What are your opinions on the Bad Batch?",
    17: "What are your opinions on Skeleton Crew?",
    18: "What are your thoughts on Tales of the Jedi?",
    19: "What are your thoughts on Tales of the Empire?",
    20: "Which Star Wars character deserved better?",
    21: "What are your opinions on The Acolyte?",
    22: "What are your thoughts on the Ahsoka show?",
    23: "What are your thoughts on the Obi-Wan Kenobi show?",
    24: "What are your thoughts on the Andor TV Show?",
    25: "What are your opinions on Book of Boba Fett?",
    26: "What are your thoughts on The Phantom Menace?",
    27: "What are your thoughts on Attack of the Clones?",
    28: "What are your thoughts on Revenge of the Sith?",
    29: "What are your thoughts on the original Star Wars movie (A New Hope)?",
    30: "What are your thoughts on The Empire Strikes Back?",
    31: "What are your thoughts on The Return of the Jedi?",
    32: "What are your opinions on The Force Awakens?",
    33: "What are your opinions on The Last Jedi?",
    34: "What are your opinions on The Rise of Skywalker?",
    35: "What are your opinions on Rogue One?",
    36: "What are your opinions on the Han Solo movie?",
    37: "What are your opinions on Bendu?",
    38: "Who's your favorite Mandalorian?",
    39: "Who's your favorite Jedi?",
    40: "Who's your favorite Sith?",
    41: "Who's your favorite Bounty Hunter?",
    42: "Who's your favorite Clone Trooper?",
    43: "Who's your favorite Droid?",
    44: "The ending of Rogue One was super good but I'm sad we have to wait until 1977 for a sequel.",
    45: "How old were you when you first discovered Star Wars?",
    46: "We know about order 66, what about the other 65 orders?",
    47: "What are your opinions on Chopper?",
    48: "Clones or Battle Droids?",
    49: "What are your thoughts on Hondo Ohnaka?",
    50: "Jedi or Sith?",
    51: "What are your thoughts on Pong Krell?",
    52: "Is Korkie a Kenobi?",
    53: "What are your opinions on BB-8?",
    54: "What are your opinions on Captain Phasma?",
    55: "What are your opinions on Jar Jar Binks?",
    56: "What are your opinions on the Ewoks?",
    57: "Do you like Star Wars Battlefront 2?", #delete if bad
    58: "What are your opinions on the original Star Wars Battlefront 2 game?",
    59: "Do you like the Lego Star Wars games?",
    60: "Have you played the Skywalker Saga game?",  # i change from opinions it had 28comments, maybe go back idk
    61: "What are your opinions on Jedi Fallen Order?",
    62: "Do you like Star Wars Squadrons game (2020)?",
    # todo maybe go back to "opinion" it had 46 comments and 200 likes and 14k views
    63: "What are your opinions on the Star Wars: Knights Of The Old Republic game?",
    64: "Did you enjoy Jedi Survivor as a SW video game?",
    65: "Do you want to see Cal Kestis in future projects?",
    66: "What are your opinions on Sith Troopers from Ep9?",
    67: "Do you want to see more of Babu Frik?",
    68: "What are your thoughts on Darth Revan?",
    69: "What are your opinions on Reva?",
    70: "If you could create your own Star Wars story - set in any era, featuring any characters - what would be its main focus?",
    71: "BREAKING: Darth Vader is Luke's father!",
    72: "What are your opinions on Dave Filoni?",
    73: "What are your opinions on George Lucas?",
    74: "What are your opinions on Rey being a Skywalker?",
    75: "Everyone has different opinions on different parts of Star Wars. That is okay. We should not hate each other or be rude because of different points of view. We can have open discussion and conversation, and if we disagree we can do so politely.",
    # todo maybe delete
    76: "Tweet like you live on Naboo",
    77: "Should Disney make a new Star Wars trilogy? When would it be set?",
    78: "What are your opinions on Boba Fett", #todo add image
    79: "Tweet like you're Han Solo",
    80: "What are your thoughts on the Star Wars Holiday Special?",
    81: "Which Star Wars ship or vehicle would you most like to pilot?",
    82: "What did you ENJOY about the sequel trilogy?",
    83: "Should Reylo be a thing?",
    84: "Did Mace Windu survive the fall in ROTS?",
    85: "Who is the best Star Wars couple?",
    86: "Favorite Star Wars Trilogy?", #maybe delete
    87: "What is your least favorite Star Wars live action TV show?",  # todo maybe delete
    88: "What is your favorite Star Wars animated TV show?",
    89: "Did you like Yoda as a Puppet in Ep 1?",
    90: "Did you like Ray Park as Darth Maul",
    91: "Did you like Qui-Gon Jinn coming back as a Force Ghost in the Kenobi show??",
    92: "Say something nice about her...",
    93: "What are your thoughts on C-3PO?",
    94: "What are your thoughts on R2-D2?",
    95: "Did you like Ezra Bridger in Rebels",
    96: "Do you want to see Kanan Jarrus in future projects?",
    97: "Would you want to join The First Order?",
    98: "What are your opinions on the Plagueis book?",
    99: "Have you read any of the SW novelizations?",  # todo maybe delete this one
    100: "Have you read any of the Star Wars comics?",
    101: "If you could change one thing about Count Dooku, what would it be?",
    102: "What are your opinions on the Star Wars: Galaxy's Edge theme park?",
    103: "If you could change one thing about Rey, what would it be?",
    104: "Tweet like you're Darth Vader",
    105: "What Star Wars creature would you most want as a pet?",
    106: "Would you rather join the Jedi or the Sith?",
    107: "If you could have any Star Wars weapon, which one would you choose?",
    108: "If you were a bounty hunter in the Star Wars universe, who would you want as a partner?",
    109: "What Star Wars character do you think deserves their own spin-off series?",
    110: "Who do you think is the most underrated character in Star Wars?",
    111: "What is your favorite Star Wars quote?",
    112: "What is your favorite Star Wars planet?",
    113: "What is your favorite Star Wars species?",
    114: "What is your favorite Star Wars ship?",
    115: "What would have happened if Anakin had never turned to the Dark Side?",
    116: "Have you read any of the Star Wars books?",  # todo maybe delete
    117: "What is your favorite Star Wars book?",
    118: "Which is your favorite Star Wars comic series?",
    119: "What is your favorite Star Wars planet?",
    120: "If you could spend a day with any Star Wars character who would it be?",
    121: "If you could rewrite one Star Wars character’s arc, who would it be?",
    122: "What role should politics have in the Star Wars universe?",
    123: "What’s the most emotional moment in Star Wars for you?",
    124: "Which Star Wars character do you think had the most wasted potential?",
    125: "Which Star Wars movie or show has the best soundtrack?",
    126: "Did you like the relationship between Anakin and Padmé?",
    127: "Which Star Wars droid do you think is the most useful?",
    128: "Who had the most tragic backstory?",
    129: "Do you like the idea of a Star Wars story told from the perspective of a stormtrooper?",
    130: "What do you disagree with most Star Wars fans about?",  # maybe generic picture here idk
    131: "Would you want a story set entirely in the criminal underworld?",
    132: "What are your thoughts on using CGI for Leia in Rogue One?",
    133: "Would you want a story told from the perspective of a droid?",
    134: "What are your opinions on the Jedi Council in the prequels?",
    135: "Would you want a story set during the Old Republic era?",
    136: "Say something nice about the Sequels",
    137: "What are your thoughts on the concept of the World Between Worlds?",
    138: "Tweet like you live on Kessel",
    139: "Do you want a Lando TV show staring Donald Glover?",
    140: "What are your opinions on Anakin's fall to the dark side?",
    141: "Do you wanna see more about the Clones after Order 66?",
    142: "How do you feel about Lando Calrissian’s role in the original trilogy?",
    143: "What is your favorite non-canon Star Wars story?",  # maybe delete
    144: "Do you want Mace Windu to return in future projects?",
    145: "What are your opinions on Chancellor Valorum?",
    146: "What are your opinions on Watto?",
    147: "Do you want more of a backstory of Shmi Skywalker?",
    148: "Did you like Jake Lloyd as Anakin Skywalker?",
    149: "Tweet like you're Obi-Wan Kenobi",
    150: "What are your opinions on Jango Fett?",
    151: "What are your thoughts on Count Dooku?",
    152: "What are your opinions on General Grievous?",
    153: "Do you want to see Dexter Jettster return in future projects?",  # if this does bad delete
    154: "What are your opinions on the Kaminoans?",
    155: "Chopper or R2-D2?",
    156: "Did you like Natalie Portman as Padmé Amidala?",
    157: "What are your thoughts on Ki-Adi-Mundi?",
    158: "What are your thoughts on Kit Fisto?",
    159: "What are your thoughts on Aayla Secura?",
    160: "What are your thoughts on Saw Gerrera?",
    161: "Do you want to see more of the Nightsisters?",
    162: "What are your thoughts on Jyn Erso?",
    163: "What are your thoughts on K-2SO?",
    164: "What are your thoughts on Director Krennic?",
    165: "What are your thoughts on Mon Mothma?",
    166: "What are your thoughts of Cassion Andor as a character?",
    167: "Did you enjoy Alden Ehrenreich as Han Solo?",
    168: "Did you like Donald Glover as Lando Calrissian?",
    169: "Do you like Qi'ra in the Solo movie?",
    170: "Comment like it's 2014 and The Force Awakens trailer just dropped.",
    171: "Did you like L3-37 in the Han Solo movie?",
    172: "Did you like James Earl Jones as the voice of Darth Vader?",
    173: "Do you want to see Enfys Nest return in future projects?",  #delete if bad
    174: "Did you like Maul's cameo in the Han Solo Movie?",
    175: "Did you like how Han Solo got his name in the Han Solo Movie?",
    176: "Did you like Han Solo's origin story in the Han Solo Movie?",
    177: "Should we get a sequel to the Han Solo Movie?",
    178: "Did you like how they portrayed Luke Skywalker in the Sequel Trilogy?",
    179: "Did you like Leia in the Sequel Trilogy?",  # todo maybe reword or delete
    180: "Did you like how they portrayed Han Solo in the Sequel Trilogy?",
    181: "Did you enjoy seeing R2-D2 and C-3PO in the Sequels?",
    182: "Did you like Poe Dameron?",
    183: "What are your thoughts on Finn?",
    184: "What are your thoughts on Rey?",
    185: "What are your thoughts on Maz Kanata?",
    186: "What are your thoughts on Snoke in the Sequels?",
    187: "Do you want to see General Hux in future projects?",  # maybe delete
    188: "What are your thoughts on Iden Versio?",
    189: "What are your thoughts on J. J. Abrams?",
    190: "What are your thoughts on Rian Johnson?",
    191: "What are your thoughts on Kathleen Kennedy?",
    192: "Did you enjoy the Sequel Trilogy as a whole?",
    193: "Did you enjoy the Sequel Trilogy's ending?",
    194: "Did you like Rosario Dawson as Ahsoka Tano?",
    195: "Did you enjoy seeing Ahsoka in The Mandalorian?",
    196: "Did you enjoy seeing Bo-Katan in The Mandalorian?",
    197: "Did you enjoy seeing Boba Fett in The Mandalorian?",
    198: "Did you enjoy seeing Luke Skywalker in The Mandalorian?",
    199: "What are your thoughts on Grogu (Baby Yoda) in The Mandalorian?",
    200: "What are your thoughts on Moff Gideon?",
    201: "What are your thoughts on Cara Dune?",
    202: "What are your thoughts on Greef Karga?",
    203: "Did you like Dave Filoni showing up in The Mandalorian?",
    204: "What are your thoughts on Cobb Vanth?",
    205: "Did you like seeing Tusken Raiders in The Mandalorian?",
    206: "What are your thoughts on Fennec Shand?",
    207: "Do you want to see more of Dr. Pershing?",
    208: "What are your thoughts on IG-11?",
    209: "What are your thoughts on Kuiil?",
    210: "What are your thoughts on Bib Fortuna?",
    211: "What are your thoughts on The Armorer?",
    212: "Did you enjoy seeing Bill Burr appearing in The Mandalorian",
    213: "what is a star war?",
    214: "Is the Ahsoka show just Rebels Season 5?",
    215: "Did you like Jod Na Nawood (Jude Law) from Skeleton Crew?",  # todo maybe rewrite or delete
    216: "Do you like Omega from The Bad Batch?",
    217: "Do you like Crosshair from The Bad Batch?",
    218: "Did you like Hunter from The Bad Batch?",  # todo maybe reword or delete
    219: "Did the Ahsoka show live up to your expectations?",
    220: "Do you like Wrecker from The Bad Batch?",
    221: "Did the Obi-Wan Kenobi show live up to your expectations?",
    222: "What are your thoughts on the Bad Batch as a whole?",
    223: "Do you want Billie Lourd to return as Leia?",
    224: "What is the most iconic line from Darth Vader?",
    225: "Did the Acolyte show live up to your expectations?",
    226: "Did you like Leia's portrayal in the Kenobi Show?",
    227: "Did you like the Kenobi Show's portrayal of Obi-Wan Kenobi?",
    228: "Did you like the Kenobi Show's portrayal of Darth Vader?",
    229: "Did you like the Kenobi Show's portrayal of Owen and Beru Lars?",
    230: "Did you enjoy the Kenobi Show's portrayal of the Inquisitors?",
    231: "Do you want to see Senator Organa return in future projects?",
    232: "Did you like the con-Jedi guy in the Obi-Wan Kenobi show?",
    233: "What are your thoughts on Darth Jar Jar?",
    234: "Rebellion or Resistance?",
    235: "Canon or Legends?",
    236: "Do you want to see C-3PO and R2-D2 return in future projects",
    237: "Anakin or Obi-Wan?",
    238: "Darth Vader or Kylo Ren?",
    239: "Darth Maul or Darth Vader?",
    240: "Darth Vader or Darth Sidious?",
    241: "Darth Sidious or Snoke?",
    242: "Did you like Luke coming back as a Force Ghost?",
    243: "Light Side or Dark Side?",
    244: "X-Wing or TIE Fighter?",
    245: "Mandalorian or Jedi?",
    246: "Lightsaber or Blaster?",
    247: "Would you rather live on the Death Star or Starkiller Base?",
    248: "Star Wars or Star Trek?",
    249: "Did you enjoy Lando Calrissian's return in Episode 9?",
    250: "What do you think makes a great Star Wars villain?",
    251: "Would you want a Star Wars story told from the perspective of a smuggler?",
    252: "What role do you think music plays in enhancing the Star Wars experience?",
    253: "I sense a plot to destroy the Jedi", #13 comments, 56 likes Sep 2025
    # maybe get rid of 'in the star wars universe' idk
    254: "If you're stuck in the Star Wars universe for 24 hours, what's the first thing you would do?",
    255: "What will Star Wars look like in 30 years?",
    256: "What are your thoughts on the Star Wars fandom?",
    257: "What role should real world politics have in Star Wars?",
    258: "Tweet like you live on Yavin 4",
    259: "What is Darth Vader saying?",
    # this performed bad last time , 5 comments, maybe delete
    260: "What are your opinions on Admiral Holdo?",
    261: "Do you like Star Wars Lore?",
    262: "Did you like Darth Maul's return in The Clone Wars?",
    263: "Did you like the Nightsister magic in Ahsoka?",  # test
    264: "Do you like the Expanded Universe (EU)?",
    265: "Are you excited for Star Wars: Starfighter coming May 2027?",
    266: "What are your opinions on the Clone Wars movie?",
    267: "Which is a better name: Count Dooku or Darth Tyranus",
    268: "If you could write the next chapter of Star Wars, what direction would you take?",
    269: "Mandalorian Armor or Stormtrooper Armor?",
    270: "Which do you like more: The Droid Army or The Clone Army?",
    271: "Darth Bane or Darth Revan?",
    272: "Do you like the Nightsisters in The Clone Wars?",
    273: "Hoth or Tatooine?",
    274: "Coruscant or Naboo?",
    275: "Battle of Endor or Battle of Hoth?",
    276: "Would you rather fly the Millennium Falcon or Slave 1?",
    277: "The Ghost or Razor Crest?",
    278: "The Ghost or the Millennium Falcon?",
    279: "Do you want to see more Death Troopers in future projects?",
    280: "Did you like the Mortis episodes in The Clone Wars?",
    281: "Did you like the Siege of Mandalore episodes in The Clone Wars?",
    282: "Execute Order 66", #todo add image here
    283: "Did you like the Umbara episodes in The Clone Wars?",
    284: "Do you want Star Wars Battlefront 3?",
    285: "Did you enjoy seeing Boba Fett in The Clone Wars?",
    286: "Did you enjoy seeing the Martez Sisters in The Clone Wars?",
    287: "Chopper or R2-D2?",
    288: "What are your opinions on Kylo Ren?",
    289: "What are your opinions on Jawas?",
    290: "Porgs or Ewoks?",
    291: "What are your opinions on Porgs in The Last Jedi?",
    292: "Blue Lightsaber or Green Lightsaber?",
    293: "What color lightsaber are you?",
    294: "Did The Book of Boba Fett live up to your expectations?",
    295: "Tweet like you're in the Star Wars universe.",
    296: "Do you want to see more from the High Republic era?",
    297: "Which is cooler: Battle of Endor or Battle of Yavin?", #11 comments without prefix, maybe delete if bad
    298: "Battle of Geonosis or Battle of Naboo?",
    299: "What are your opinions of Crait?",
    300: "Would you want to live on Geonois?",  # todo maybe delete
    301: "What are your opinions of Kamino?",
    302: "What are your opinions of Mustafar?",
    303: "What are your opinions of Scarif?",
    304: "What are your opinions of Exegol?",
    305: "What are your opinions of Hoth?",
    306: "What are your opinions of Tatooine?",
    307: "Would you want to live on Coruscant?",
    308: "Would you want to live on Naboo?",
    309: "What are your opinions of the Forest Moon of Endor?",
    310: "Is Yavin 4 a good rebel base?",
    # todo maybe re-word, the generic "what are your opinions on..." didn't do that good
    311: "What are your opinions of Dagobah?",
    312: "What are your opinions of Bespin?",
    313: "OPINION: The Clone Wars show is my favorite Star Wars content. What do you think?",
    314: "Tweet like you work on the Death Star",
    315: "Would you want to live on Dathomir?", #delete if bad
    316: "What are your opinions of Starkiller Base?",
    317: "Do you like Mandalore?",  # delete if bad
    318: "What is your favorite quote from Obi-Wan Kenobi?",
    319: "Tweet like you live on Geonosis",
    320: "Did you like seeing Kessel in the Solo movie?",  # todo maybe rewrite or delete
    321: "What are your opinions of Felucia?",
    322: "What is your favorite quote from Darth Vader?",
    323: "It's over Anakin, I have the high ground", #todo add image here
    324: "What are your opinions of Jakku?",
    325: "Would you want to live on Takodana?",
    326: "Would you want to live on Ahch-To?",
    327: "Would you want to live on Canto Bight?",
    328: "Which hallway scene is your favorite?",
    329: "If you're in the Star Wars universe, what would your job be?",
    330: "How did Palpatine kill these Jedi so easily?",
    331: "Jedi Temple or Sith Temple?",
    # 332: "Astromech or Protocol Droid?",
    332: "Do you want to see Director Krennic in future projects?",
    333: "Inquisitors or Knights of Ren?",
    334: "What are your opinions on the Inquisitors?",
    335: "What are your opinions on the Knights of Ren?",
    336: "Rebel Alliance or New Republic?",
    337: "First Order or Galactic Empire?",
    338: "What are your opinions on the First Order?",
    339: "Do you support the Galactic Empire?",
    340: "Do you support the Rebel Alliance?",  # todo maybe change idk
    341: "What are your opinions on Wedge Antilles?",
    342: "What are your opinions on Grand Admiral Thrawn?",
    343: "What are your opinions on Grand Moff Tarkin?",
    344: "What are your opinions on Admiral Ackbar?",
    345: "What are your opinions on Captain Rex?",
    346: "Do you like Commander Cody?", #delete if bad
    347: "OPINION: The Han Solo movie was very well done and I would love to see a sequel in some form. What do you think?",
    348: "Do you want to see Luminara Unduli return in future projects?",
    349: "What is your biggest Star Wars hot take?",
    350: "Did you like Ahsoka in The Clone Wars?",
    351: "Do you want to see Asajj Ventress in future projects?",  # todo maybe delete
    352: "What are your opinions on Cad Bane?",
    353: "What are your opinions on Nute Gunray?",
    354: "Which Anakin / Vader is your favorite?", #todo ANAKING VADER ADD IMAGE HERE
    355: "Do you want to see more Bo-Katan?",  # todo maybe delete
    356: "Did you like Sabine Wren in Rebels?",
    357: "What are your opinions on Zeb?",
    358: "Did you like Agent Kallus in Rebels?",
    359: "What are your opinions on John Williams?",
    360: "Do you want to see the Grand Inquisitor return in future projects?",
    361: "If you could change one thing about The Phantom Menace what would it be?",
    362: "If you could change one thing about Attack of the Clones what would it be?",
    363: "If you could change one thing about Revenge of the Sith what would it be?",
    364: "If you could change one thing about A New Hope what would it be?",
    365: "If you could change one thing about The Empire Strikes Back what would it be?",
    366: "If you could change one thing about The Return of the Jedi what would it be?",
    367: "If you could change one thing about The Force Awakens what would it be?",
    368: "If you could change one thing about The Last Jedi what would it be?",
    369: "If you could change one thing about The Rise of Skywalker what would it be?",
    370: "If you could change one thing about Rogue One what would it be?",
    371: "If you could change one thing about the Solo movie, what would it be?",
    372: "What is your Star Wars Unpopular Opinion?",
    373: "Palpatine did nothing wrong. Change my mind.",
    374: "Should they make a GTA style Star Wars video game?",
    375: "Did you enjoy seeing Count Dooku in the Tales of the Jedi?",
    376: "What are your opinions on Yaddle?",
    377: "If Disney sold Star Wars, who would you want to buy it?",
    378: "What Star Wars Lego sets do you own?",  # maybe reword or delete
    379: "Did you enjoy seeing Bariss Offee in Tales of the Empire?",
    380: "Did you enjoy seeing Asajj Ventress in Tales of the Underworld?",
    381: "Did you enjoy seeing Cad Bane in Tales of the Underworld?",  # maybe delete
    382: "Do you want to see Ahmed Best return in future projects?",
    383: "Do you want to see Cad Bane return in future projects?",
    384: "Did you enjoy seeing seeing Ezra Bridger in live action?",
    385: "Did you enjoy seeing seeing Sabine Wren in live action?",
    386: "Did you enjoy seeing Hera Syndulla in live action?",
    387: "Do you want to see more of Zeb in future projects?",
    # todo maybe reword, i already tried "did you enjoy seeing Zeb in live action?" but it got 10 comments
    388: "Tweet like you live on Mandalore",
    389: "Did the Andor show live up to your expectations?",
    390: "Tweet like you live on Jakku",
    391: "Did you like the CGI used for Luke in The Mandalorian?",
    392: "Who is your favorite character from the Prequels?",
    393: "Who is your least favorite character from the Prequels?",
    394: "Who is your favorite character from the Original Trilogy?",
    395: "Who is your least favorite character from the Original Trilogy?",
    396: "Who is your favorite character from the Sequels?",
    397: "Who is your least favorite character from the Sequels?",
    398: "What are your opinions on recasting of Bail Organa in Andor season 2?",
    399: "Andor: Season 1 or Season 2?",
    400: "Do you want a season 2 of The Book of Boba Fett?",
    401: "Do you want a season 2 of Obi-Wan Kenobi?",
    402: "Do you want a season 2 of The Acolyte?",
    403: "Do you want a season 2 of Ahsoka?",
    404: "Do you want a season 2 of Skeleton Crew?",
    405: "What is the most iconic line from Yoda?",
    406: "What is the most iconic line from Obi-Wan Kenobi?",
    # todo i have an favorite quote from obi wan, can't have both
    407: "What is the most iconic line from Padme?",
    408: "What is the most iconic line from Ahsoka Tano?",
    409: "What is the most iconic line from Mace Windu?",
    410: "What is the most iconic line from Sheev Palpatine?",
    411: "What is the most iconic line from C-3PO?",
    412: "Did you like Hayden Christensen's as Anakin Skywalker?",
    413: "What are your thoughts on Han Solo?",
    414: "What are your thoughts on Luke Skywalker?",
    415: "What are your thoughts on Leia Organa?",
    416: "What are your thoughts on Qui-Gon Jinn?",
    417: "Did Mandalorian Season 3 live up to your expectations?",
    418: "If you could change one thing about Ahsoka Tano, what would it be?",
    419: "Do you want to see Poe Dameron in future projects?",
    # everything below here is a test / new
    420: "Which inquisitor do you want to see more?",  # todo maybe delete, or reword
    421: "Would you rather be Force-sensitive or a skilled pilot?",
    422: "What is the definition of peak Star Wars?",
    423: "What are your opinions on the Star Wars: Force Unleashed games?",
    424: "What is your favorite Star Wars location?",
    425: "Tweet like you live on Kamino",
    426: "What are your opinions on Force Ghosts?",
    427: "What is your favorite Star Wars vehicle?",
    428: "What is your favorite Star Wars battle?",
    429: "Would you want a Star Wars story about ancient Jedi?",
    430: "Who's your favorite bounty hunter besides Boba Fett?",
    431: "Tweet like you live on Coruscant",
    432: "Tweet like you work in Starkiller Base",
    433: "Would you rather wield a double-bladed lightsaber or dual lightsabers?",
    434: "What is your favorite Star Wars quote from a droid?",
    435: "Who's your favorite Jedi who survived Order 66?",
    436: "What are your thoughts on the concept of gray Jedi?",
    437: "Who's your favorite Sith Lord from Legends?",
    438: "Which ship is your favorite?",
    439: "What are your thoughts on the Jedi Code?",
    440: "What is your favorite Star Wars Force ability?",
    441: "What is your favorite Star Wars lightsaber color?",
    442: "What is your favorite Star Wars lightsaber duel?",
    443: "Would you rather train under Yoda or Obi-Wan?",
    444: "Do you like the idea of midi-chlorians?",
    445: "Who was your favorite cameo in The Mandalorian?",
    446: "Tweet like you live on Mustafar",
    447: "Who's your favorite character from Rogue One?",
    448: "What are your opinions on the Tusken Raiders?",
    449: "What are your thoughts on Force healing?",
    450: "Tweet like you live on Scarif",
    451: "Did you like the Yoda v. Palpatine battle in Ep 3?",
    452: "Did you like the Mustafar Duel in Ep 3?",
    453: "Would you want a series about the Knights of Ren?",
    454: "What are your thoughts on Rose Tico?",
    455: "Would you ever want to yield the Darksaber?",
    456: "What are your opinions on the ending of Rogue One?",
    457: "What are your opinions on the ending of The Rise of Skywalker?",
    458: "What are your opinions on Luke's training of Rey?",
    459: "What are your opinions on Luke dying at the end of The Last Jedi?",
    460: "What are your opinions on Leia's Force abilities?",
    # 461: "What is your least favorite Star Wars species?",
    461: "Do you want to see Rey return in future projects?",
    462: "Do you want to see Cara Dune return in future projects?",
    # 463: "What is your least favorite ",
    463: "What Star Wars opinion do you have that will have people like this?",
    464: "What is your least favorite Star Wars weapon?",
    465: "What is your least favorite Star Wars battle?",
    466: "What is your least favorite Star Wars location?",  # todo this seems to perform well
    467: "Who is your least favorite Star Wars character?",
    468: "What is your least favorite Star Wars movie?",
    469: "Why do you like Star Wars?",
    470: "What is your least favorite Star Wars game?",
    471: "Have you read the Thrawn trilogy?",
    472: "Do you want to see Thrawn in future projects?",
    473: "What is your least favorite Star Wars Force ability?",
    474: "What is your least favorite Star Wars lightsaber duel?",
    475: "Would you want to be a Jedi during the Prequel era?",
    476: "Who's your favorite member of the Bad Batch squad?",
    477: "What is your favorite moment from the Obi-Wan Kenobi series?",
    478: "What is your favorite moment from the Ahsoka series?",
    479: "What is your favorite moment from the Andor series?",
    480: "Did you like Kylo Ren's redemption?",
    481: "What is your favorite moment from the Mandalorian series?",
    482: "What is your favorite moment from the Clone Wars series?",
    483: "Would you rather train as a Sith or a Jedi?",
    484: "Did you like Thrawn in the Ahsoka series?",
    485: "Who's your favorite character from Star Wars Rebels?",
    486: "What is your favorite moment from the Star Wars Rebels series?",
    487: "Would you want to live on Mandalore?",
    488: "Who's your favorite Jedi Council member?", #todo add pic
    489: "Do you want to see more of Iden Versio in future projects?",
    490: "Do you want to see more of Saw Gerrera in future projects?",
    491: "Who should return as a Force Ghost?", #maybe delete
    492: "On a scale from 1-10, how would you rate The Phantom Menace?",
    493: "On a scale from 1-10, how would you rate Attack of the Clones?",
    494: "On a scale from 1-10, how would you rate Revenge of the Sith?",
    495: "On a scale from 1-10, how would you rate A New Hope?",
    496: "On a scale from 1-10, how would you rate The Empire Strikes Back?",
    497: "On a scale from 1-10, how would you rate The Return of the Jedi?",
    498: "On a scale from 1-10, how would you rate The Force Awakens?",
    499: "On a scale from 1-10, how would you rate The Last Jedi?",
    500: "On a scale from 1-10, how would you rate The Rise of Skywalker?",
    501: "On a scale from 1-10, how would you rate Rogue One?",
    502: "On a scale from 1-10, how would you rate the Solo movie?",
    503: "On a scale from 1-10, how would you rate The Mandalorian?",
    504: "On a scale from 1-10, how would you rate The Clone Wars show?",
    505: "On a scale from 1-10, how would you rate Star Wars Rebels show?",
    506: "On a scale from 1-10, how would you rate The Bad Batch show?",
    507: "On a scale from 1-10, how would you rate the Ahsoka show?",
    508: "On a scale from 1-10, how would you rate the Obi-Wan Kenobi show?",
    509: "On a scale from 1-10, how would you rate the Andor show?",
    510: "On a scale from 1-10, how would you rate The Book of Boba Fett?",
    511: "On a scale from 1-10, how would you rate The Acolyte?",
    512: "On a scale from 1-10, how would you rate Skeleton Crew?",
    513: "On a scale from 1-10, how would you rate Star Wars Visions?",
    514: "On a scale from 1-10, how would you rate Star Wars: Resistance?",
    515: "Do you want to see Finn return in future projects?",
    516: "Do you want to see Kylo Ren return in future projects?",
    517: "Do you want to see Hondo Ohnaka return in future projects?",
    518: "Do you want to see Omega return in future projects?",
    519: "Do you want to see Qi'ra return in future projects?",
    520: "Do you want to see Lando Calrissian return in future projects?",
    521: "Say something nice about this movie...",
    522: "Say something nice about her...",
    523: "Do you want to see Rose Tico return in future projects?",
    524: "What are your opinions of Darth Vader as a villain?",
    525: "Is Darth Vader the ultimate villain in all of Cinema?",
    526: "Do you want to see more Darth Vader in future projects?",
    527: "What are your opinions on Death Troopers?",
    528: "Do you want to see Hayden Christensen return as Anakin Skywalker in future projects?",
    529: "Did you like Ewan McGregor as Obi-Wan Kenobi?",
    530: "Did you like Hayden Christensen as Anakin Skywalker?",
    531: "Did you like Carrie Fisher as Leia Organa?",
    532: "Did you like Mark Hamill as Luke Skywalker?",
    533: "Did you like Harrison Ford as Han Solo?",
    534: "Is Frank Oz a good voice for Yoda?",
    535: "Did you like Daisy Ridley as Rey?",
    536: "Did you like Adam Driver as Kylo Ren?",
    537: "Did you like John Boyega as Finn?",
    538: "Did you like Oscar Isaac as Poe Dameron?",
    539: "Did you like Kelly Marie Tran as Rose Tico?",
    540: "Did you like Diego Luna as Cassian Andor?",
    541: "Is Andy Serkis a good voice for Snoke?",
    542: "Did you like Alden Ehrenreich as Han Solo?",
    543: "Did you like Billy Dee Willaims as Lando Calrissian?",
    544: "Did you like Emilia Clarke as Qi'ra?",
    545: "Is Anthony Daniels a good voice for C-3PO?",
    546: "What are your opinions on Leia?",
    547: "What are your opinions on Luke?",
    548: "What are your opinions on Yoda?",
    549: "Do you want to see Yoda return in future projects?",
    550: "Did you like how Palpatine returned in The Rise of Skywalker?",
    551: "Which Vader helmet do you like the most?",
    552: "Who's lightsaber is your favorite?",
    553: "This is the way",
    554: "Which version do you prefer?",
    555: "Which Jabba was the best?",
    556: "It is never okay to bully/harass an actor or actress because of the character they played.",
    557: "Tweet like you're Ahsoka Tano", #delete if bad
    558: "Tweet like you're Captain Phasma",
    559: "Tweet like you're Count Dooku",
    560: "Tweet like you're Darth Maul",
    561: "Tweet like you're Director Krennic",
    562: "Tweet like you're Finn",
    563: "Tweet like you're Kylo Ren",
    564: "Tweet like you're Lando Calrissian",
    565: "Tweet like you're Leia Organa",
    566: "Tweet like you're Luke Skywalker",
    567: "Tweet like you're Mace Windu",
    568: "Tweet like you're Palpatine",
    569: "Tweet like you're Rey",
    570: "Tweet like you're Saw Gerrera",
    571: "Tweet like you're Thrawn",
    572: "Tweet like you're Yoda",
    573: "Tweet like you live on Tatooine",
    574: "Tweet like you live on Hoth",
    575: "Tweet like you live on Endor",
    576: "Tweet like you live on Canto Bight", #delete if bad
    577: "Tweet like you live on Crait",
    578: "Tweet like you live on Dagobah",
    579: "Would you want to live on Jakku?",








    # todo next do more favorite quote or iconic line from main characters
    # todo or next do some what - if's like Obiwan turnign to darkside or something? idk something to get conversation
}


def SW_question(event, context):
    # maybe questions if you could change one thing about [character] what would it be?

    # s3 bucket files look up
    lookup = {
        1: "None",
        2: "None",
        3: "None",
        4: "None",
        5: "None",
        6: "None",
        7: "questions/GonkDroid/",
        8: "questions/char_Tarkin/",
        9: "None",
        10: "questions/game_KOTOR/",
        11: "questions/show_resistance/",
        12: "questions/show_rebels/",
        13: "questions/show_cw2003/",
        14: "questions/show_cw/",
        15: "questions/show_mandalorian/",
        16: "questions/show_BadBatch/",
        17: "questions/show_SkeletonCrew/",
        18: "questions/show_TalesOfTheJedi/",
        19: "questions/show_TalesOfTheEmpire/",
        20: "None",
        21: "questions/show_Acolyte/",
        22: "questions/show_Ahsoka/",
        23: "questions/show_Kenobi/",
        24: "questions/show_Andor/",
        25: "questions/show_BOBF/",
        26: "questions/movie_ep1/",
        27: "questions/movie_ep2/",
        28: "questions/movie_ep3/",
        29: "questions/movie_ep4/",
        30: "questions/movie_ep5/",
        31: "questions/movie_ep6/",
        32: "questions/movie_ep7/",
        33: "questions/movie_ep8/",
        34: "questions/movie_ep9/",
        35: "questions/movie_RogueOne",
        36: "questions/movie_Solo/",
        37: "questions/char_Bendu/",
        38: "None",
        39: "questions/other_Jedi/",
        40: "questions/other_SithLordall/",
        41: "None",
        42: "questions/generic_clones/",
        43: "None",
        44: "None",
        45: "None",
        46: "None",
        47: "questions/char_Chopper/",
        48: "questions/generic_droidclone/",
        49: "questions/char_Hondo/",
        50: "None",
        51: "questions/char_PongKrell/",
        52: "questions/char_KorkieKryze/",
        53: "questions/char_BB8/",
        54: "questions/char_CaptainPhasma/",
        55: "questions/char_JarJarBinks/",
        56: "questions/char_Ewoks/",
        57: "questions/game_swbf2(2017)/",
        58: "questions/game_swbf2(og)/",
        59: "questions/game_LegoStarWars/",
        60: "questions/game_SkywalkerSaga(2022)/",
        61: "questions/game_JediFallenOrder/",
        62: "questions/game_Squadrons/",
        63: "questions/game_KOTORgame/",
        64: "questions/game_JediSurvivor/",
        65: "questions/char_CalKestis/",
        66: "questions/SithTroopers/",
        67: "questions/char_BabuFrik/",
        68: "questions/char_DarthRevan/",
        69: "questions/char_Reva/",
        70: "None",
        71: "questions/other_NoFatherSceneEp5/",
        72: "questions/char_DaveFiloni/",
        73: "questions/char_GeorgeLucas/",
        74: "questions/char_Rey/",
        75: "None",
        76: "questions/planet_Naboo/",
        77: "None",
        78: "None",
        79: "questions/char_HanSolo",
        80: "questions/movie_holidayspecial/",
        81: "None",
        82: "None",
        83: "questions/Reylo/",
        84: "questions/char_MaceWindu(death)/",
        85: "None",
        86: "None",
        87: "None",
        88: "None",
        89: "questions/char_Yoda(puppet)/",
        90: "questions/char_DarthMaul(ep1)/",
        91: "questions/char_Qui-gonJinn(FORCE_GHOST)/",
        92: "questions/char_Rey/",
        93: "questions/char_C-3PO/",
        94: "questions/char_R2-D2/",
        95: "questions/char_EzraBridger/",
        96: "questions/char_KananJarrus/",
        97: "questions/other_FirstOrder/",
        98: "questions/book_Plagueis/",
        99: "None",
        100: "None",
        101: "questions/char_CountDooku/",
        102: "questions/GalaxyEdge/",
        103: "questions/char_Rey/",
        104: "questions/char_DarthVader",
        105: "None",
        106: "None",
        107: "None",
        108: "None",
        109: "None",
        110: "None",
        111: "None",
        112: "None",
        113: "None",
        114: "None",
        115: "questions/other_AnakinNeverTurned/",
        116: "questions/other_books/",
        117: "questions/other_books/",
        118: "None",
        119: "None",
        120: "None",
        121: "None",
        122: "None",
        123: "None",
        124: "None",
        125: "None",
        126: "questions/other_anakinPadmeRelationship/",
        127: "None",
        128: "None",
        129: "None",
        130: "None",
        131: "questions/other_UnderWorld/",
        132: "questions/char_LeiaCGI/",
        133: "None",
        134: "questions/other_JediCouncil/",
        135: "None",
        136: "None",
        137: "questions/other_WorldBetweenWorlds/",
        138: "None",
        139: "questions/show_Lando/",
        140: "None",
        141: "questions/other_ClonesAfterOrder66/",
        142: "questions/char_LandoCalrissian/",
        143: "None",
        144: "questions/char_MaceWindu/",
        145: "questions/char_Valorum/",
        146: "questions/char_Watto/",
        147: "questions/char_ShmiSkywalker/",
        148: "questions/char_Anakin(ep1)/",
        149: "questions/char_ObiWan",
        150: "questions/char_JangoFett/",
        151: "questions/char_CountDooku/",
        152: "questions/char_GeneralGrievous/",
        153: "questions/char_DexterJettster/",
        154: "questions/char_Kaminoan/",
        155: "questions/char_ChopperORr2d2/",
        156: "questions/char_Padme(NataliePortman)/",
        157: "questions/char_KiAdiMundi/",
        158: "questions/char_KitFisto/",
        159: "questions/char_AaylaSecura/",
        160: "questions/char_SawGerrera/",
        161: "questions/char_NightSisters/",
        162: "questions/char_JynErso/",
        163: "questions/char_K2-S0/",
        164: "questions/char_DirectorKrennic/",
        165: "questions/char_MonMothma(new)/",
        166: "questions/char_Andor/",
        167: "questions/char_HanSolo(SoloMovie)/",
        168: "questions/char_Lando(SoloMovie)/",
        169: "questions/char_Qira/",
        170: "questions/movie_ep7",
        171: "questions/char_L3-37/",
        172: "questions/char_DarthVader",
        173: "questions/char_EnfysNest/",
        174: "questions/char_Maul(SoloMovie)/",
        175: "questions/char_HanSolo(SoloMovie)/",
        176: "questions/char_HanSolo(SoloMovie)/",
        177: "questions/char_HanSolo(SoloMovie)/",
        178: "questions/char_Luke(Sequels)/",
        179: "questions/char_Leia(Sequels)/",
        180: "questions/char_HanSolo(Sequels)/",
        181: "questions/char_r2-c3po(sequels)/",
        182: "questions/char_PoeDameron/",
        183: "questions/char_Finn/",
        184: "questions/char_Rey/",
        185: "questions/char_MazKanata/",
        186: "questions/char_Snoke/",
        187: "questions/char_GeneralHux/",
        188: "questions/char_IdenVersio/",
        189: "questions/char_JJAbrams/",
        190: "questions/char_RianJohnson/",
        191: "questions/char_KathleenKennedy/",
        192: "None",
        193: "None",
        194: "questions/char_Ahsoka(live-action)/",
        195: "questions/char_Ahsoka(live-action)/",
        196: "questions/char_Bo-Katan(live-action)/",
        197: "questions/char_BobaFett(Mandalorian-show)/",
        198: "questions/char_Luke(Mandalorian)/",
        199: "questions/char_Grogu/",
        200: "questions/char_MoffGideon/",
        201: "questions/char_CaraDune/",
        202: "questions/char_GreefKarga/",
        203: "questions/char_DaveFiloni(Mandalorian)/",
        204: "questions/char_CobbVanth/",
        205: "questions/char_TuskenRaiders(Mandalorian)/",
        206: "questions/char_FennecShand/",
        207: "questions/char_DrPershing/",
        208: "questions/char_IG11/",
        209: "questions/char_Kuiil/",
        210: "questions/char_BibFortuna/",
        211: "questions/char_Armorer/",
        212: "questions/char_BillBurr/",
        213: "None",
        214: "questions/show_Ahsoka/",
        215: "questions/char_JudeLaw/",
        216: "questions/char_Omega/",
        217: "questions/char_Crosshair/",
        218: "questions/char_Hunter/",
        219: "questions/show_Ahsoka/",
        220: "questions/char_Wrecker/",
        221: "questions/show_Kenobi/",
        222: "questions/other_BadBatch/",
        223: "questions/char_BillieLourd/",
        224: "questions/char_Vader(Kenobi-show)/",
        225: "questions/show_Acolyte/",
        226: "questions/char_Leia(Kenobi-show)/",
        227: "questions/char_Obi-Wan(Kenobi-Show)/",
        228: "questions/char_Vader(Kenobi-show)/",
        229: "questions/char_OwenBeruLars(Kenobi-show)/",
        230: "questions/char_Inquisitors(KenobiShow)/",
        231: "questions/char_SenatorOrgana(Kenobi-Show)/",
        232: "questions/char_Kumail(Kenobi-Show)/",
        233: "questions/char_DarthJarJar/",
        234: "None",
        235: "None",
        236: "questions/char_r2c3po/",
        237: "questions/char_ObiwanAnakin/",
        238: "questions/char_VaderKyloRen/",
        239: "None",
        240: "questions/char_VaderSidious/",
        241: "questions/char_SnokeSidious/",
        242: "None",
        243: "None",
        244: "None",
        245: "None",
        246: "None",
        247: "questions/other_DeathStar-StarKiller/",
        248: "questions/other_StarWars-StarTrek/",
        249: "questions/char_LandoCalrissianEP9/",
        250: "None",
        251: "None",
        252: "questions/char_JohnWilliams/",
        253: "None",
        254: "None",
        255: "None",
        256: "None",
        257: "None",
        258: "questions/planet_Yavin4/",
        259: "questions/other_Whatisdarthvadersaying/",
        260: "questions/char_AdmiralHoldo/",
        261: "None",
        262: "questions/char_DarthMaul(CW)/",
        263: "None",
        264: "None",
        265: "questions/movie_Starfighter/",
        266: "questions/move_TCW/",
        267: "questions/char_CountDooku/",
        268: "None",
        269: "None",
        270: "None",
        271: "questions/char_Revan-Bane/",
        272: "questions/char_NightSisters(CW)/",
        273: "None",
        274: "questions/other_Coruscant-Naboo/",
        275: "None",
        276: "questions/other_Falcon-Slave1/",
        277: "None",
        278: "questions/other_Ghost-Falcon/",
        279: "questions/char_DeathTroopers/",
        280: "questions/other_MortisArc(CW)/",
        281: "questions/other_SiegeofMandalore(CW)/",
        282: "None",
        283: "questions/other_CloneWarsUmbara/",
        284: "questions/game_SWBF3/",
        285: "questions/char_BobaFettCloneWars/",
        286: "questions/other_MartezSisters/",
        287: "None",
        288: "questions/char_KyloRen/",
        289: "questions/char_Jawa/",
        290: "None",
        291: "questions/other_Porgs/",
        292: "None",
        293: "None",
        294: "questions/show_BOBF/",
        295: "None",
        296: "None",
        297: "None",
        298: "None",
        299: "questions/planet_Crait/",
        300: "questions/planet_Geonosis/",
        301: "questions/planet_Kamino/",
        302: "questions/planet_Mustafar/",
        303: "questions/planet_Scarif/",
        304: "questions/planet_Exegol/",
        305: "questions/planet_Hoth/",
        306: "questions/planet_Tatooine/",
        307: "questions/planet_Coruscant/",
        308: "questions/planet_Naboo/",
        309: "questions/planet_Endor/",
        310: "questions/planet_Yavin4/",
        311: "questions/planet_Dagobah/",
        312: "questions/planet_Bespin/",
        313: "None",
        314: "None",
        315: "questions/planet_Dathomir/",
        316: "questions/planet_StarkillerBase/",
        317: "questions/planet_Mandalore/",
        318: "questions/char_ObiWan/",
        319: "questions/planet_Geonosis/",
        320: "questions/planet_Kessel/",
        321: "questions/planet_Felucia/",
        322: "questions/char_Vader(Kenobi-show)/",
        323: "None",
        324: "questions/planet_Jakku/",
        325: "questions/planet_Takodana/",
        326: "questions/planet_Ahch-to/",
        327: "questions/planet_CantoBight/",
        328: "questions/other_Hallway/",
        329: "None",
        330: "questions/other_4JediKillPalpatine/",
        331: "None",
        332: "questions/char_DirectorKrennic/",
        333: "None",
        334: "questions/char_Inquisitors/",
        335: "questions/other_KnightsOfRen/",
        336: "None",
        337: "None",
        338: "questions/other_FirstOrder/",
        339: "questions/other_EmpireLogo/",
        340: "questions/other_RebelAlliance/",
        341: "questions/char_WedgeAntilles/",
        342: "questions/char_Thrawn/",
        343: "questions/char_Tarkin/",
        344: "questions/char_AdmiralAckbar/",
        345: "questions/char_CaptainRex/",
        346: "questions/char_CommanderCody/",
        347: "questions/movie_Solo",
        348: "questions/char_LuminaraUnduli/",
        349: "None",
        350: "questions/char_Ahsoka(CW)/",
        351: "questions/char_AsajjVentress/",
        352: "questions/char_CadBane/",
        353: "questions/char_NuteGunray/",
        354: "None",
        355: "questions/char_SabineWrenCWRebels/",
        356: "questions/char_SabineWren/",
        357: "questions/char_Zeb/",
        358: "questions/char_AgentKallus/",
        359: "questions/char_JohnWilliams/",
        360: "questions/char_GrandInquisitor/",
        361: "questions/movie_ep1/",
        362: "questions/movie_ep2/",
        363: "questions/movie_ep3/",
        364: "questions/movie_ep4/",
        365: "questions/movie_ep5/",
        366: "questions/movie_ep6/",
        367: "questions/movie_ep7/",
        368: "questions/movie_ep8/",
        369: "questions/movie_ep9/",
        370: "questions/movie_RogueOne",
        371: "questions/movie_Solo/",
        372: "None",
        373: "questions/char_PalpatinePrequels/",
        374: "None",
        375: "questions/char_CountDookuTalesOfJedi/",
        376: "questions/char_Yaddle/",
        377: "None",
        378: "questions/other_Lego/",
        379: "questions/char_BarissOffeeUnderworld/",
        380: "questions/char_AsajjVentressUnderworld/",
        381: "questions/char_CadBaneUnderworld/",
        382: "questions/char_AhmedBest/",
        383: "questions/char_CadBaneLiveAction/",
        384: "questions/char_EzraBridgerLiveAction/",
        385: "questions/char_SabineWrenLiveAction/",
        386: "questions/char_HeraLiveAction/",
        387: "questions/char_ZebLiveAction/",
        388: "questions/planet_Mandalore/",
        389: "questions/show_Andor/",
        390: "questions/planet_Jakku/",
        391: "questions/char_LukeCGI/",
        392: "None",
        393: "None",
        394: "None",
        395: "None",
        396: "None",
        397: "None",
        398: "questions/other_BailOrganaRecast/",
        399: "questions/show_Andor/",
        400: "questions/show_BOBF/",
        401: "questions/show_Kenobi/",
        402: "questions/show_Acolyte/",
        403: "questions/show_Ahsoka/",
        404: "questions/show_SkeletonCrew/",
        405: "questions/char_Yoda(puppet)/",
        406: "questions/char_ObiWan/",
        407: "questions/char_Padme(NataliePortman)/",
        408: "questions/char_Ahsoka(CW)/",
        409: "questions/char_MaceWindu/",
        410: "questions/char_PalpatinePrequels/",
        411: "questions/char_C-3PO/",
        412: "questions/char_HaydenChristiansen/",
        413: "questions/char_HanSolo/",
        414: "None",
        415: "None",
        416: "questions/char_QuiGonJinn/",
        417: "None",
        418: "questions/char_Ahsoka(CW)/",
        419: "questions/char_PoeDameron/",
        420: "None",
        421: "None",
        422: "None",
        423: "None",
        424: "None",
        425: "None",
        426: "None",
        427: "None",
        428: "None",
        429: "None",
        430: "None",
        431: "questions/planet_Coruscant/",
        432: "None",
        433: "None",
        434: "None",
        435: "None",
        436: "None",
        437: "questions/other_SithLordall/",
        438: "questions/other_WhichShipisyourfavorite/",
        439: "None",
        440: "None",
        441: "None",
        442: "None",
        443: "None",
        444: "None",
        445: "None",
        446: "questions/planet_Mustafar/",
        447: "questions/movie_RogueOne",
        448: "questions/char_TuskenRaiders(Mandalorian)/",
        449: "None",
        450: "None",
        451: "None",
        452: "questions/other_MustafarBattle/",
        453: "questions/other_KnightsOfRen/",
        454: "questions/char_RoseTico/",
        455: "questions/other_Darksaber/",
        456: "questions/movie_RogueOne",
        457: "questions/movie_ep9/",
        458: "questions/other_LukeTrainingRey/",
        459: "questions/other_LukeDeath/",
        460: "questions/other_LeiaForce/",
        461: "questions/char_Rey/",
        462: "questions/char_CaraDune/",
        463: "questions/other_unpopularOpinion/",
        464: "None",
        465: "None",
        466: "None",
        467: "None",
        468: "None",
        469: "None",
        470: "None",
        471: "questions/char_Thrawn/",
        472: "questions/char_Thrawn/",
        473: "None",
        474: "None",
        475: "questions/other_Jedi/",
        476: "questions/show_BadBatch/",
        477: "questions/show_ObiWanKenobi/",
        478: "questions/show_Ahsoka/",
        479: "questions/show_Andor/",
        480: "questions/char_KyloRen/",
        481: "questions/show_Mandalorian/",
        482: "questions/show_CloneWars/",
        483: "None",
        484: "questions/char_ThrawnAhsoka/",
        485: "questions/show_Rebels/",
        486: "questions/show_Rebels/",
        487: "questions/planet_Mandalore/",
        488: "questions/other_JediCouncil/",
        489: "questions/char_IdenVersio/",
        490: "questions/char_SawGerrera/",
        491: "None",
        492: "questions/movie_ep1/",
        493: "questions/movie_ep2/",
        494: "questions/movie_ep3/",
        495: "questions/movie_ep4/",
        496: "questions/movie_ep5/",
        497: "questions/movie_ep6/",
        498: "questions/movie_ep7/",
        499: "questions/movie_ep8/",
        500: "questions/movie_ep9/",
        501: "questions/movie_RogueOne",
        502: "questions/movie_Solo/",
        503: "questions/show_Mandalorian/",
        504: "questions/show_CloneWars/",
        505: "questions/show_Rebels/",
        506: "questions/show_BadBatch/",
        507: "questions/show_Ahsoka/",
        508: "questions/show_Kenobi/",
        509: "questions/show_Andor/",
        510: "questions/show_BOBF/",
        511: "questions/show_Acolyte/",
        512: "questions/show_SkeletonCrew/",
        513: "questions/show_Visions/",
        514: "questions/show_Resistance/",
        515: "questions/char_Finn/",
        516: "questions/char_KyloRen/",
        517: "questions/char_Hondo/",
        518: "questions/char_Omega/",
        519: "questions/char_Qira/",
        520: "questions/char_LandoCalrissianEP9/",
        521: "questions/movie_ep8/",
        522: "questions/char_RoseTico/",
        523: "questions/char_RoseTico/",
        524: "questions/char_DarthVader/",
        525: "questions/char_DarthVader/",
        526: "questions/char_DarthVader/",
        527: "questions/char_DeathTroopers/",
        528: "questions/char_HaydenChristiansen/",
        529: "questions/char_ObiWan/",
        530: "questions/char_HaydenChristiansen/",
        531: "questions/char_Leia/",
        532: "questions/char_Luke/",
        533: "questions/char_HanSolo/",
        534: "questions/char_Yoda/",
        535: "questions/char_Rey/",
        536: "questions/char_KyloRen/",
        537: "questions/char_Finn/",
        538: "questions/char_PoeDameron/",
        539: "questions/char_RoseTico/",
        540: "questions/char_Andor/",
        541: "questions/char_Snoke/",
        542: "questions/char_HanSolo(SoloMovie)/",
        543: "questions/char_Lando(SoloMovie)/",
        544: "questions/char_Qira/",
        545: "questions/char_C-3PO/",
        546: "questions/char_Leia",
        547: "questions/char_Luke/",
        548: "questions/char_Yoda/",
        549: "questions/char_Yoda/",
        550: "questions/char_PalpatineEp9/",
        551: "questions/other_VaderHelmet/",
        552: "questions/other_CharacterLightsabers/",
        553: "questions/other_thisisthewaythread/",
        554: "questions/other_ep6endings/",
        555: "questions/other_JabbaVersion/",
        556: "None",
        557: "None",
        558: "questions/char_CaptainPhasma",
        559: "questions/char_CountDooku",
        560: "questions/char_DarthMaul(CW)",
        561: "questions/char_DirectorKrennic",
        562: "questions/char_Finn",
        563: "questions/char_KyloRen",
        564: "questions/char_LandoCalrissian",
        565: "questions/char_Leia",
        566: "questions/char_Luke",
        567: "questions/char_MaceWindu",
        568: "questions/char_PalpatinePrequels",
        569: "questions/char_Rey",
        570: "questions/char_SawGerrera",
        571: "questions/char_Thrawn",
        572: "questions/char_Yoda",
        573: "questions/planet_Tatooine/",
        574: "questions/planet_Hoth/",
        575: "questions/planet_Endor/",
        576: "None",
        577: "questions/planet_Crait/",
        578: "questions/planet_Dagobah/",
        579: "questions/planet_Jakku/",
        580: "None",
        581: "None",
        582: "None",
        583: "None",
        584: "None",
        585: "None",
        586: "None",
        587: "None",
        588: "None",
        589: "None",
    }


    bucket_name = 'starwars.photos'
    file_key = 'notes/SW_questions.txt'
    s3 = boto3.client('s3')


    API_KEY = os.environ["API_KEY"]
    API_SECRET_KEY = os.environ["API_SECRET_KEY"]
    ACCESS_TOKEN = os.environ["ACCESS_TOKEN"]
    ACCESS_TOKEN_SECRET = os.environ["ACCESS_TOKEN_SECRET"]
    BEARER_TOKEN = os.environ["BEARER_TOKEN"]

    # X credentials stored in env variables

    auth = tweepy.OAuth1UserHandler(API_KEY, API_SECRET_KEY, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
    api = tweepy.API(auth)

    client = tweepy.Client(
        bearer_token=BEARER_TOKEN,
        consumer_key=API_KEY,
        consumer_secret=API_SECRET_KEY,
        access_token=ACCESS_TOKEN,
        access_token_secret=ACCESS_TOKEN_SECRET
    )

    try:
        # Fetch the current file from S3
        response = s3.get_object(Bucket=bucket_name, Key=file_key)
        file_content = response['Body'].read().decode('utf-8')

        # Convert the file content (string) into a Python list
        question_indices = json.loads(file_content)
        print(question_indices)

        index = random.randint(1, len(questions))

        # try again until we get new item not in list
        while index in question_indices:
            index = random.randint(1, len(questions))

        # index = 154 #hard code
        path = lookup[index]

        question_indices.insert(0, index)
        if len(question_indices) > 400:
            question_indices.pop()  # Remove the last element

        updated_content = json.dumps(question_indices)

        s3.put_object(Bucket=bucket_name, Key=file_key, Body=updated_content)
        question = questions[index]

        print("BEFORE")
        print(question)
        # this replaces 'thoughts' or 'opinions' with 50% chance of either
        contains_thoughts = "thoughts" in question.lower()
        contains_opinions = "opinions" in question.lower()

        # Only proceed if at least one of the words is present
        if contains_thoughts or contains_opinions:
            # Replace "thoughts" with randomly chosen word
            ran = random.random()
            if contains_thoughts:
                replacement = "thoughts"
                if random.random() < 0.5:
                    replacement = "opinions"
                if random.random() < 0.3:
                    replacement = "honest " + replacement

                pattern = r'\bthoughts\b'
                question = re.sub(pattern, replacement, question)
                print("REPLACED")

            # Replace "opinions" with randomly chosen word
            if contains_opinions:
                replacement = "thoughts"
                if random.random() < 0.5:
                    replacement = "opinions"
                if random.random() < 0.3:
                    replacement = "honest " + replacement
                pattern = r'\bopinions\b'
                question = re.sub(pattern, replacement, question)
                print("REPLACED")
        # done replacing
        print("AFTER")
        print(question)

        if path == "None":  # upload just text, no image
            client.create_tweet(text=question)
            return f"POSTED TWEET {question} with no image"

        response = s3.list_objects_v2(Bucket=bucket_name, Prefix=path)
        if 'Contents' not in response:
            return {
                'statusCode': 404,
                'body': 'No files found in the specified directory.'
            }
        # Extract file keys (paths) from the response
        file_keys = [obj['Key'] for obj in response['Contents'] if obj['Key'] != path]
        # Check if there are files to choose from
        if not file_keys:
            return {
                'statusCode': 404,
                'body': 'No files found in the specified directory.'
            }

        # Pick a random file from the list
        random_file = random.choice(file_keys)

        # these 4 are for image, not implemented yet:
        download_path = f"/tmp/{os.path.basename(random_file)}"
        s3.download_file(bucket_name, random_file, download_path)
        media = api.media_upload(download_path)
        # client.create_tweet(text=question, media_ids=[media.media_id])

        # less than 1% chance of being called a subscriber only tweet
        if random.random() < 0.00555: # 1% a month being called at 6 questions a day
            client.create_tweet(text=question, media_ids=[media.media_id], for_super_followers_only=True)
            return f"tweeted image with question {question} (subscribers only)"

        client.create_tweet(text=question, media_ids=[media.media_id])
        return f"tweeted image with question {question}"



    except Exception as e:
        print(e)
