#this is an exact copy of what is in AWS Lambda "SW_video"
import random
import tweepy
import os

API_KEY = os.environ["API_KEY"]
API_SECRET_KEY = os.environ["API_KEY_SECRET"]
ACCESS_TOKEN = os.environ["ACCESS_TOKEN"]
ACCESS_TOKEN_SECRET = os.environ["ACCESS_TOKEN_SECRET"]
BEARER_TOKEN = os.environ["BEARER_TOKEN"]

client = tweepy.Client(bearer_token = BEARER_TOKEN,
                                consumer_key = API_KEY, consumer_secret = API_SECRET_KEY,
                                access_token = ACCESS_TOKEN, access_token_secret = ACCESS_TOKEN_SECRET)

def PostQuote(event, context):
    dict = {
        0: "I’ve been waiting for you, Obi-Wan. We meet again, at last. The circle is now complete. When I left you, I was but the learner; now I am the master.\" -Darth Vader ",
        1: "Don't get technical with me. What mission? What are you talking about? I've just about had enough of you. Go that way, you'll be malfunctioning in a day you near-sighted scrap pile.\" -C-3PO ",
        2: "When 900 years old, you reach… Look as good, you will not.\" -Yoda ",
        3: "The Dark Side of the Force is the pathway to many abilities some consider to be... Unnatural.\" -Palpatine ",
        4: "He’s holding a thermal detonator!\" -C-3PO",
        5: "I sense great fear in you, Skywalker. You have hate... you have anger... but you don’t use them.\" -Count Dooku ",
        6: "Great, kid. Don’t get cocky.\" -Han Solo ",
        7: "Luke, you can destroy the Emperor. He has foreseen this. It is your destiny. Join me, and together we can rule the galaxy as father and son.\" -Darth Vader ",
        8: "You can’t win, Darth. If you strike me down, and I will become more powerful than you could possibly imagine.\" -Ben Kenobi, ",
        9: "Aren't you a little short for a storm trooper?\" -Leia ",
        10: "Mmm. Lost a planet, Master Obi-Wan has. How embarrassing.\" -Yoda ",
        11: "Lando’s not a system he’s a man!\" -Han Solo ",
        12: "These aren’t the droids you’re looking for...\" -Ben Kenobi ",
        13: "Traveling through hyperspace ain't like dusting crops, farm boy.\" -Han Solo ",
        14: "If there's a bright centre to the universe, you're on the planet that it's farthest from.\" -Luke Skywalker ",
        15: "Hello. I don't believe we have been introduced. R2-D2? A pleasure to meet you. I am C-3PO, Human-Cyborg Relations.\" -C-3PO ",
        16: "Master Kenobi, you disappoint me. Yoda holds you in such high esteem. Surely you can do better!\" -Count Dooku ",
        17: "Wipe them out...all of them.\" -Darth Sidious ",
        18: "Steady. Steady.\" -Jar Jar ",
        19: "We’ll take the long way.\" -Padmé ",
        20: "Now, Viceroy, we will discuss a new treaty.\" -Padmé ",
        21: "Now, this is podracing!\" -Anakin ",
        22: "And you, young Skywalker. We will watch your career with great interest.\" -Palpatine ",
        23: "I will train Anakin. Without the approval of the Council if I must.\" -Obi-Wan Kenobi ",
        24: "Always two there are...no more...no less. A master and an apprentice.\" -Yoda ",
        25: "But Master Yoda says I should be mindful of the future...\" -Obi-Wan Kenobi ",
        26: "I will make it legal.\" -Darth Sidious ",
        27: "You were right about one thing, Master. The negotiations were short.\" -Obi-Wan Kenobi ",
        28: "A communications disruption can mean only one thing. Invasion!\" -Sio Bibble ",
        29: "The ability to speak does not make you intelligent.\" -Qui-Gon Jinn ",
        30: "How wude.\" -Jar Jar ",
        31: "There’s always a bigger fish.\" -Qui-Gon Jinn ",
        32: "Are you an angel?\" -Anakin ",
        33: "What, you think you’re some kind of Jedi, waving your hand around like that?\" -Watto ",
        34: "At last we will reveal ourselves to the Jedi. At last we will have revenge.\" -Darth Maul ",
        35: "I can assure you they will never get me onto one of those dreadful starships.\" -C-3PO ",
        36: "This is so wizard, Ani!\" -Kitster ",
        37: "But you can’t stop the change any more than you can stop the suns from setting.\" -Shmi Skywalker ",
        38: "I was not elected to watch my people suffer and die while you discuss this invasion in a committee.\" -Padmé ",
        39: "Fear is the path to the dark side...fear leads to anger...anger leads to hate...hate leads to suffering.\" -Yoda ",
        40: "...always remember, your focus determines your reality.\" -Qui-Gon Jinn ",
        41: "Yousa no tinken yousa greater den da Gungans... Meesa lika dis. Maybe wesa bein friends.\" -Boss Nass ",
        42: "Fear leads to anger. Anger leads to hate. Hate leads to suffering.\" -Yoda ",
        43: "Always two there are, no more, no less. A master and an apprentice.\" -Yoda ",
        44: "The ability to speak does not make you intelligent. Now get out of here.\" -Qui-Gon Jinn ",
        45: "I was not elected to watch my people suffer and die while you discuss this invasion in a committee.\" -Padmé ",
        46: "I will not let this Republic that has stood for a thousand years be split in two.\" -Palpatine ",
        47: "Sometimes we must let go of our pride and do what is requested of us.\" -Padmé ",
        48: "You must join me, Obi-Wan, and together, we will destroy the Sith!\" -Count Dooku ",
        49: "I killed them. I killed them all. They’re dead, every single one of them. And not just the men, but the women and the children too. They’re like animals, and I slaughtered them like animals. I hate them!\" -Anakin ",
        50: "Victory? Victory, you say? Master Obi-Wan, not victory. The shroud of the dark side has fallen. Begun, the Clone War has.\" -Yoda ",
        51: "Why do I get the feeling you’re going to be the death of me?\" -Obi-Wan Kenobi ",
        52: "To be angry is to be human.\" -Padmé ",
        53: "I'm a Jedi. I know I'm better than this.\" -Anakin ",
        54: "You don't want to sell me death sticks. You want to go home and rethink your life.\" -Obi-Wan Kenobi ",
        55: "Truly wonderful, the mind of a child is.\" -Yoda ",
        56: "This party's over.\" -Mace Windu ",
        57: "You have made a commitment to the Jedi order, a commitment not easily broken.\" -Obi-Wan Kenobi ",
        58: "We live in a real world, come back to it.\" -Padmé  ",
        59: "The day we stop believing democracy can work is the day we lose it.\" -Queen Jamillia ",
        60: "Well, if droids could think, there’d be none of us here, would there?\" -Obi-Wan Kenobi ",
        61: "In grave danger, you are.\" -Yoda ",
        62: "The dark side clouds everything. Impossible to see the future is.\" -Yoda ",
        63: "The thought of losing you is unbearable.\" -Anakin ",
        64: "I'm just a simple man trying to make my way in the universe.\" -Jango Fett ",
        65: "I have a bad feeling about this.\" -Obi-Wan Kenobi ",
        66: "So this is how liberty dies... with thunderous applause.\" -Padmé ",
        67: "You were the Chosen One! It was said that you would destroy the Sith, not join them! Bring balance to the force, not leave it in darknes...\" -Obi-Wan Kenobi ",
        68: "I have brought peace, freedom, justice, and security to my new empire.\" -Anakin ",
        69: "Only a Sith deals in absolutes.\" -Obi-Wan Kenobi ",
        70: "You were my brother, Anakin. I loved you.\" -Obi-Wan Kenobi ",
        71: "Execute Order 66.\" -Palpatine ",
        72: "I am the Senate.\" -Palpatine ",
        73: "Anakin, you're breaking my heart!\" -Padmé ",
        74: "This is where the fun begins.\" -Anakin ",
        75: "It's over, Anakin. I have the high ground.\" -Obi-Wan Kenobi ",
        76: "Do it.\" -Palpatine ",
        77: "I'm too weak... Don't kill me. Please!\" -Palpatine, ",
        78: "Twisted by the dark side, young Skywalker has become. The boy you trained, gone he is... Consumed by Darth Vader.\" -Yoda ",
        79: "I feel lost.\" -Anakin ",
        80: "Power! Unlimited power!\" -Palpatine ",
        81: "Henceforth, you shall be known as Darth Vader.\" -Palpatine ",
        82: "You underestimate my power!\" -Anakin ",
        83: "Something’s happening. I’m not the Jedi I should be. I want more, and I know I shouldn’t.\" -Anakin ",
        84: "Not if anything to say about it, I have.\" -Yoda ",
        85: "Your arrogance blinds you, Master Yoda. Now you will experience the full power of the dark side.\" -Palpatine ",
        86: "If you're not with me, then you're my enemy.\" -Anakin ",
        87: "Anakin, Chancellor Palpatine is evil!\" -Obi-Wan Kenobi ",
        88: "The attempt on my life has left me scarred and deformed.\" -Palpatine ",
        89: "The Jedi turned against me. Don’t you turn against me!\" -Anakin ",
        90: "Destroy the Sith, we must.\" -Yoda ",
        91: "This is the end for you, my master.\" -Anakin ",
        92: "You were the chosen one!\" -Obi-Wan Kenobi ",
        93: "I sense a plot to destroy the Jedi.\" -Mace Windu ",
        94: "This is where the fun begins.\" -Anakin ",
        95: "Rebellions are built on hope.\" -Jyn Erso ",
        96: "I am one with the Force and the Force is with me.\" -Chirrut Îmwe ",
        97: "I've got a bad feeling about this.\" -K-2SO ",
        98: "We have hope. Rebellions are built on hope.\" -Jyn Erso ",
        99: "Make ten men feel like a hundred.\" -Cassian Andor ",
        100: "I'm not used to people sticking around when things go bad.\" -Jyn Erso ",
        101: "Congratulations. You are being rescued. Please do not resist.\" -K-2SO ",
        102: "The Force is with me, and I fear nothing.\" -Chirrut Îmwe ",
        103: "Save the Rebellion! Save the dream!\" -Saw Gerrera ",
        104: "Are you kidding me? I'm blind!\" -Chirrut Îmwe ",
        105: "Every time I walked away from something I wanted to forget, I told myself it was for a cause that I believed in. A cause that was worth it.\" -Cassian Andor ",
        106: "The time to fight is now!\" -Jyn Erso ",
        107: "What chance do we have? The question is 'what choice.' Run, hide, plead for mercy, scatter your forces. You give way to an enemy this evil with this much power and you condemn the galaxy to an eternity of submission.\" -Jyn Erso ",
        108: "I find that answer vague and unconvincing.\" -K-2SO ",
        109: "There is more than one sort of prison, Captain. I sense that you carry yours wherever you go.\" -Chirrut Îmwe ",
        110: "I'm one with the Force. The Force is with me.\" -Chirrut Îmwe ",
        111: "Be careful not to choke on your aspirations, Director.\" -Darth Vader ",
        112: "The strongest stars have hearts of kyber.\" -Chirrut Îmwe ",
        113: "We’re not here to make friends.\" -Cassian Andor",
        114: "There’s a problem on the horizon. There is no horizon.\" -K-2SO ",
        115: "You will never win.\" -Jyn Erso ",
        116: "You know the odds better than anyone.\" -Cassian Andor ",
        117: "I am taking them all down.\" -Baze Malbus ",
        118: "He means well.\" -Bodhi Rook ",
        119: "Jyn, I’ll be there for you. Cassian said I had to.\" -K-2SO ",
        120: "The Force will be with you. Always.\" -Ben Kenobi ",
        121: "I find your lack of faith disturbing.\" -Darth Vader ",
        122: "Help me, Obi-Wan Kenobi. You’re my only hope.\" -Princess Leia ",
        123: "I’ve got a bad feeling about this.\" -Luke Skywalker ",
        124: "Stay on target.\" -Gold Five ",
        125: "You don’t need to see his identification.\" -Ben Kenobi ",
        126: "Mos Eisley spaceport. You will never find a more wretched hive of scum and villainy. We must be cautious.\" -Ben Kenobi ",
        127: "In my experience, there’s no such thing as luck.\" -Ben Kenobi ",
        128: "That’s no moon. It’s a space station.\" -Obi-Wan Kenobi ",
        129: "Don’t be too proud of this technological terror you’ve constructed. The ability to destroy a planet is insignificant next to the power of the Force.\" -Darth Vader ",
        130: "You know, sometimes I amaze even myself.\" -Han Solo ",
        131: "I suggest a new strategy, R2: let the Wookiee win.\" -C-3PO ",
        132: "It’s not impossible. I used to bullseye womp rats in my T-16 back home. They’re not much bigger than two meters.\" -Luke Skywalker ",
        133: "Use the Force, Luke.\" -Ben Kenobi ",
        134: "Evacuate? In our moment of triumph? I think you overestimate their chances.\" -Grand Moff Tarkin ",
        135: "You’re all clear, kid. Now let’s blow this thing and go home.\" -Han Solo ",
        136: "Hokey religions and ancient weapons are no match for a good blaster at your side, kid.\" -Han Solo ",
        137: "She may not look like much, but she’s got it where it counts, kid.\" -Han Solo ",
        138: "What a piece of junk!\" -Luke Skywalker ",
        139: "The Force is strong with this one.\" -Darth Vader ",
        140: "When I left you, I was but the learner. Now I am the master.\" -Darth Vader ",
        141: "You're braver than I thought.\" -Leia ",
        142: "This will be a day long remembered. It has seen the end of Kenobi; it will soon see the end of the Rebellion.\" -Darth Vader ",
        143: "I sense something. A presence I’ve not felt since...\" -Darth Vader ",
        144: "Who's the more foolish, the fool or the fool who follows him?\" -Ben Kenobi ",
        145: "Do or do not. There is no try.\" -Yoda ",
        146: "No. I am your father.\" -Darth Vader ",
        147: "Why, you stuck-up, half-witted, scruffy-looking nerf-herder!\" -Princess Leia ",
        148: "Never tell me the odds!\" -Han Solo ",
        149: "The Force is with you, young Skywalker, but you are not a Jedi yet.\" -Darth Vader ",
        150: "You have failed me for the last time, Admiral.\" -Darth Vader ",
        151: "I know.\" -Han Solo ",
        152: "Adventure. Excitement. A Jedi craves not these things.\" -Yoda ",
        153: "He’s as clumsy as he is stupid.\" -Darth Vader ",
        154: "You will be. You will be.\" -Yoda ",
        155: "I thought they smelled bad on the outside.\" -Han Solo ",
        156: "All too easy.\" -Darth Vader ",
        157: "You must unlearn what you have learned.\" -Yoda ",
        158: "Size matters not. Look at me. Judge me by my size, do you?\" -Yoda ",
        159: "Sir, the possibility of successfully navigating an asteroid field is approximately 3,720 to 1.\" -C-3PO ",
        160: "Impressive. Most impressive.\" -Darth Vader ",
        161: "Luke, you can destroy the Emperor. He has foreseen this. It is your destiny.\" -Darth Vader ",
        162: "I am altering the deal. Pray I don’t alter it any further.\" -Darth Vader ",
        163: "You look absolutely beautiful. You truly belong here with us among the clouds.\" -Lando Calrissian ",
        164: "He's no good to me dead.\" -Boba Fett ",
        165: "Luke, it's a trap!\" -Leia ",
        166: "I have a bad feeling about this.\" -Leia ",
        167: "Control, control, you must learn control!\" -Yoda ",
        168: "We would be honored if you would join us.\" -Darth Vader ",
        169: "It's a trap!\" -Admiral Ackbar ",
        170: "The Force is strong in my family. My father has it. I have it. And... my sister has it. Yes. It's you, Leia.\" -Luke Skywalker ",
        171: "So be it... Jedi.\" -Palpatine ",
        172: "Your overconfidence is your weakness.\" -Luke Skywalker ",
        173: "You were right about me. Tell your sister... you were right.\" -Darth Vader ",
        174: "I will not fight you, father.\" -Luke Skywalker ",
        175: "Good. I can feel your anger. I am defenseless. Take your weapon! Strike me down with all of your hatred, and your journey towards the dark side will be complete!\" -Palpatine ",
        176: "Boba Fett? Boba Fett? Where?\" -Han Solo ",
        177: "If I told you half the things I've heard about this Jabba the Hutt, you'd probably short-circuit.\" -C-3PO ",
        178: "There is good in him. I've felt it.\" -Luke Skywalker ",
        179: "I must speak with Jabba.\" -Luke Skywalker ",
        180: "You have that power too. In time, you'll learn to use it as I have.\" -Luke Skywalker ",
        181: "I am a Jedi Knight, like my father before me.\" -Luke Skywalker ",
        182: "Now, young Skywalker, you will die.\" -Palpatine ",
        183: "Soon I'll be dead, and you with me.\" -Luke Skywalker ",
        184: "I've just made a deal that'll keep the Empire out of here forever.\" -Lando Calrissian ",
        185: "You may dispense with the pleasantries, Commander. I'm here to put you back on schedule.\" -Darth Vader ",
        186: "It is too late for me, son.\" -Darth Vader ",
        187: "I'm endangering the mission. I shouldn't have come.\" -Luke Skywalker ",
        188: "Many Bothans died to bring us this information.\" -Mon Mothma ",
        189: "The Emperor's made a critical error, and the time for our attack has come.\" -Mon Mothma ",
        190: "I'm gonna be a pilot... best in the galaxy.\" -Han Solo ",
        191: "Everything you heard about me is true.\" -Lando Calrissian ",
        192: "I have a really good feeling about this.\" -Han Solo ",
        193: "I’m Han Solo. I’m captain of the Millennium Falcon.\" -Han Solo ",
        194: "Let me give you some advice. Assume everyone will betray you. And you will never be disappointed.\" -Tobias Beckett ",
        195: "You might want to buckle up, baby.\" -Lando Calrissian ",
        196: "190 years old? You look great!\" -Han Solo ",
        197: "I’ve waited a long time for a shot like this.\" -Han Solo ",
        198: "I've got a really good feeling about this.\" -Han Solo ",
        199: "You’re after something. Is it revenge? Money? Or is it something else?\" -Qi'ra ",
        200: "The galaxy's a dangerous place.\" -Tobias Beckett ",
        201: "Buckle up, baby.\" -Lando Calrissian ",
        202: "We're fine. We're all fine here now, thank you. How are you?\" -Han Solo ",
        203: "Chewie, get us out of here!\" -Han Solo ",
        204: "You look good. A little rough around the edges, but good.\" -Qi'ra ",
        205: "Chewie, we're home.\" -Han Solo ",
        206: "That's not how the Force works!\" -Han Solo ",
        207: "I never knew there was this much green in the whole galaxy.\" -Rey ",
        208: "The belonging you seek is not behind you; it is ahead.\" -Maz Kanata ",
        209: "You know, no matter how much we fought, I've always hated watching you leave.\" -Leia ",
        210: "That's one hell of a pilot!\" -Finn ",
        211: "You will remove these restraints and leave this cell with the door open.\" -Rey ",
        212: "Where do you come from? Classified, really? Me too.\" -Rey ",
        213: "I am no one.\" -Rey ",
        214: "You. You're afraid. That you will never be as strong as Darth Vader.\" -Rey ",
        215: "The garbage will do!\" -Rey ",
        216: "I can do this. I can do this.\" -Finn ",
        217: "You need a teacher! I can show you the ways of the Force!\" -Kylo Ren ",
        218: "Hope is not lost today. It is found.\" -Leia ",
        219: "Escape now. Hug later.\" -Han Solo ",
        220: "You have no place in this story. You come from nothing.\" -Kylo Ren ",
        221: "Let the past die. Kill it, if you have to. That’s the only way to become what you are meant to be.\" -Kylo Ren ",
        222: "This is not going to go the way you think.\" -Luke Skywalker ",
        223: "We are the spark that will light the fire that will burn the First Order down.\" -Poe Dameron ",
        224: "The greatest teacher, failure is.\" -Yoda ",
        225: "I only know one truth. It’s time for the Jedi to end.\" -Luke Skywalker ",
        226: "No one’s ever really gone.\" -Luke Skywalker ",
        227: "Insolence! We are pirates! We don’t even know what that means.\" -Hondo Ohnaka ", #added in, out of order
        228: "You’re demoted.\" -Leia ",
        229: "The war is just beginning, and I will not be the last Jedi.\" -Luke Skywalker ",
        230: "That's how we're gonna win. Not fighting what we hate, saving what we love.\" -Rose Tico #Cringe",
        231: "Fulfill your destiny!\" -Snoke ",
        232: "I’ve seen this raw strength only once before. It didn’t scare me enough then. It does now.\" -Luke Skywalker ",
        233: "Darkness rises and light to meet it.\" -Snoke ",
        234: "The Rebellion is reborn today. The war is just beginning.\" -Luke Skywalker ",
        235: "I need someone to show me my place in all this.\" -Rey ",
        236: "If you strip away the myth and look at their deeds, the legacy of the Jedi is failure, hypocrisy, hubris.\" -Luke Skywalker ",
        237: "I've failed you, Ben. I'm sorry.\" -Luke Skywalker ",
        238: "The Force will be with you. Always.\" -Leia ",
        239: "We’re all in this. Till the end.\" -Poe Dameron ",
        240: "I’ve come to end the conflict.\" -Rey ",
        241: "Confronting fear is the destiny of a Jedi.\" -Luke Skywalker ",
        242: "I am all the Sith.\" -Palpatine ",
        243: "And I... am all the Jedi.\" -Rey ",
        244: "The dark side is in our nature. Surrender to it.\" -Kylo Ren ",
        245: "Stand together, die together.\" -Palpatine ",
        246: "You are a Palpatine.\" -Kylo Ren ",
        247: "We had each other. That’s how we won.\" -Lando Calrissian ",
        248: "Taking one last look, sir, at my friends.\" -C-3PO ",
        249: "There are more of us.\" -Lando Calrissian ",
        250: "I know what I have to do, but I don’t know if I have the strength to do it.\" -Kylo Ren ",
        251: "As I served you in the old wars, I serve you now.\" -General Pryde ",
        252: "I can bring you in warm, or I can bring you in cold.\" -Din Djarin ",
        253: "I have spoken.\" -Kuiil ",
        254: "This is the way.\" -Din Djarin ",
        255: "I've been quested with returning this child to the Jedi.\" -Din Djarin ",
        256: "Wherever I go, he goes.\" -Din Djarin ",
        257: "Do the magic hand thing.\" -Greef Karga ",
        258: "I'm a Mandalorian. Weapons are part of my religion.\" -Din Djarin ",
        259: "The kid's coming with me.\" -Din Djarin ",
        260: "A Mandalorian and a Jedi? They'll never see it coming.\" -Bo-Katan Kryze ",
        261: "You have something I want.\" -Moff Gideon ",
        262: "He means more to me than you will ever know.\" -Moff Gideon ",
        263: "Your song is not yet written. I will serve you until it is.\" -Kuiil ",
        264: "I've seen what such feelings can do to a fully trained Jedi Knight. To the best of us.\" -Ahsoka Tano ",
        265: "You expect me to search the galaxy and deliver this creature to a race of enemy sorcerers?\" -Din Djarin ",
        266: "I like those odds.\" -Din Djarin ",
        267: "I'm sorry, lady. I don't understand frog.\" -Din Djarin ",
        268: "A jetpack. I like it.\" -Cobb Vanth ",
        269: "When one chooses to walk the way of the Mandalore, you are both hunter and prey.\" -The Armorer ",
        270: "I will initiate self-destruct.\" -IG-11 ",
        271: "I would like to see the baby.\" -The Client ",
        272: "The time of the Jedi is over.\" -Obi-Wan Kenobi ",
        273: "You can't escape him!\" -Reva ",
        274: "You are of no further use.\" -Darth Vader ",
        275: "Anakin is gone. I am what remains.\" -Darth Vader ",
        276: "You didn't kill Anakin Skywalker. I did.\" -Darth Vader ",
        277: "You can't keep me here, my father is Bail Organa. He's a Senator.\" -Leia ",
        278: "If ever I needed guidance, Master, it is now.\" -Obi-Wan Kenobi ",
        279: "The Jedi are cowards.\" -The Grand Inquisitor ",
        280: "I am what you made me.\" -Darth Vader ",
        281: "You're bleeding all over my floor.\" -Haja Estree ",
        282: "Your strength has returned, but the weakness still remains.\" -Darth Vader ",
        283: "If you want to live, you'll tell me where the Jedi is.\" -Reva ",
        284: "The years have made you weak.\" -Darth Vader ",
        285: "The light will fade, but is never forgotten.\" -Obi-Wan Kenobi ",
        286: "I am not your failure, Obi-Wan.\" -Darth Vader ",
        287: "When the time comes, he must be trained.\" -Obi-Wan Kenobi ",
        288: "I’ve been in this fight since I was six years old.\" -Cassian Andor ",
        289: "The Empire is a disease that thrives in darkness. It is never more alive than when we sleep.\" -Luthen Rael ",
        290: "We need the fear. We need them to overreact.\" -Luthen Rael ",
        291: "Better to spit in their food and steal their trinkets. It's all we can do.\" -Cassian Andor ",
        292: "Oppression breeds rebellion.\" -Maarva Andor ",
        293: "The axe forgets, but the tree remembers.\" -Vel Sartha ",
        294: "The day will come when all these skirmishes and battles, these moments of defiance, will have flooded the banks of the Empire’s authority.\" -Luthen Rael ",
        295: "Freedom is a pure idea.\" -Nemik ",
        296: "There are pockets of fermenting rebellion all over the galaxy.\" -Mon Mothma ",
        297: "We need heroes, Senator. And spies. Savoteurs. Assassins. Everything I did, I did for the Rebellion.\" -Luthen Rael ",
        298: "People are standing up.\" -Cassian Andor ",
        299: "The Imperial need for control is so desperate because it is so unnatural.\" -Nemik ",
        300: "Power doesn't panic.\" -Luthen Rael ",
        301: "There is no small job at the Empire\". -Kino Loy ",
        302: "The more you tighten your grip, the more star systems will slip through your fingers.\" -Mon Mothma ",
        303: "I am no Jedi.\" -Ahsoka Tano ",
        304: "Sometimes the right path is not the easiest one.\" -Ahsoka Tano ",
        305: "The Force is what gives a Jedi his power. It's an energy field created by all living things. It surrounds us, penetrates us, and binds the galaxy together.\" -Ahsoka Tano ",
        306: "In my experience, when you think you understand the Force, you realize just how little you know.\" -Ahsoka Tano ",
        307: "You have to be willing to fight for the things you believe in.\" -Ahsoka Tano ",
        308: "Sometimes, to find the light, you have to touch the darkness.\" -Ahsoka Tano ",
        309: "We must stand up to fear and defeat it.\" -Ahsoka Tano ",
        310: "You don't have to carry a sword to be powerful. Some leaders' strength is inspiring others.\" -Ahsoka Tano ",
        311: "Courage isn’t the absence of fear, it’s the resolve to act in spite of it.\" -Ahsoka Tano ",
        312: "To defeat your enemy, you have to understand them.\" -Ahsoka Tano ",
        313: "We are not defined by our past, but by our actions.\" -Ahsoka Tano ",
        314: "We have hope. Hope that things can get better. And they will.\" -Hera Syndulla ",
        315: "There are some things far more frightening than death.\" -Grand Inquisitor ",
        316: "I am no Jedi.\" -Ahsoka Tano ",
        317: "An object cannot make you good or evil. The temptation of power, forbidden knowledge, even the desire to do good can lead some down that path.\" -Bendu ",
        318: "We are the balance, Ezra. We were meant to be Jedi so we could be here now—when Lothal needs us most.\" -Kanan Jarrus ",
        319: "There is always a bit of truth in legends.\" -Ahsoka Tano ",
        320: "Jabba ruled with fear. I intend to rule with respect.\" -Boba Fett ",
        321: "The mission. The nightmares. They're... finally... over.\" -Fives ",
        322: "A great leap forward often requires first taking two steps back.\" -Obi-Wan Kenobi ",
        323: "Sometimes, in war, it's hard to be the one that survives.\" -Commander Cody ",
        324: "In my book, experience outranks everything.\" -Captain Rex ",
        325: "The best way I can protect you is to teach you how to protect yourself.\" -Anakin Skywalker ",
        326: "It takes strength to resist the dark side. Only the weak embrace it.\" -Obi-Wan Kenobi ",
        327: "We're just clones, sir. We're meant to be expendable.\" -Clone ",
        328: "I am a Jedi. We are peacekeepers, not soldiers.\" -Ahsoka Tano ",
        329: "To die for one's people is a great sacrifice. To live for one's people, an even greater sacrifice.\" -Senator Chuchi ",
        330: "Ahsoka, you are making a mistake!\" -Anakin Skywalker ",
        331: "I would kill you both right now if I did not have to drag your bodies.\" -Count Dooku ",
        332: "Senators, I presume you are acquainted with the collection of half-truths and hyperbole known as Obi-Wan Kenobi?\" -Duchess Satine ",
        333: "You cannot imagine the depths I would go to to stay alive, fueled by my singular hatred for you.\" -Maul ",
        334: "Remember the first and only reality of the Sith: There can only be two. And you are no longer my apprentice.\" -Darth Sidious ",
        335: "I have to sort this out on my own, without the Council and without you.\" -Ahsoka Tano  ",
        336: "No longer certain that one ever does win a war, I am.\" -Yoda ",
        337: "How charming that you actually believe that statement to be true.\" -Maul ",
        338: "Clones, bred for combat. All part of the plan... THE Plan. The only Plan that matters. Not even I was made aware of its grand design, but I played my part. And do you know what happened to me? I was cast aside. I was forgotten. But I survived, and I can thrive in the chaos that is to come.\" -Maul ",
        339: "There is no justice, now law, no order... except for the one that will replace it!\" -Maul ",
        340: "You're lucky Anakin didn't show up. The way you're fighting, you wouldn't have lasted long\" -Ahsoka Tano ",
        341: "As a Jedi, we were trained to be keepers of the peace, not soldiers. But all I've been since I was a padawn is a soldier.\" -Ahsoka Tano ",
        342: "You're A Good Soldier Rex. So Is Every One Of Those Men Down There. They May Be Willing To Die, But I Am Not The One Who Is Going To Kill Them.\" -Ahsoka Tano ",
    }

    tweet_text = "\"" + dict[random.randint(0,342)]

    ran = random.random()
    if ran < 0.02:
        tweet_text += "#StarWars"
    elif ran < 0.04:
        tweet_text += "#swtwt"
    elif ran < 0.05:
        tweet_text += "#StarWarsQuotes"
    client.create_tweet(text=tweet_text)
