import random
import tweepy
import os
import requests


# Authenticate to Twitter using Client for v2 API
client = tweepy.Client(
    bearer_token = bearer_token,
    consumer_key = API_KEY,
    consumer_secret = API_SECRET_KEY,
    access_token = access_token,
    access_token_secret = access_token_secret
)
temp_filename = '/tmp/temp_media.gif'

#
# Authenticate to Twitter using OAuth1UserHandler for media upload (v1.1)
auth = tweepy.OAuth1UserHandler(API_KEY, API_SECRET_KEY, access_token,access_token_secret)
api = tweepy.API(auth)



def SW_gif_post(event,context):
    gif_dict = {
        "1_eP1_yoda_senseMuchFear.gif": "",
        "ahsoka-v-maul-cw-s7.gif": "",
        "anakin-ep1-no-one-kill-jedi.gif": "",
        "bad-feeling-kenobi.gif": "",
        "bad-feeling-luke.gif": "",
        "begun-clone-wars-yoda.gif": "",
        "don't-like-sand.gif": "",
        "dooku-looking-forward.gif": "",
        "empire-reorganized.gif": "",
        "execute-order-66.gif": "",
        "force-ghost-luke.gif": "",
        "fun-begins.gif": "",
        "good-soldiers-starwars.gif": "",
        "half-ship.gif": "",
        "high-ground.gif": "",
        "i-love-democracy.gif": "",
        "kenobi-bar-ep2.gif": "",
        "lack-of-faith.gif": "",
        "maul-cw-s7.gif": "",
        "maul-death.gif": "",
        "more-powerful-ben-kenobi.gif": "",
        "name-no-meaning-vader-ep6.gif": "",
        "not-how-force-works.gif": "",
        "obiwan-brother.gif": "",
        "order66-cw.gif": "",
        "palpatine-ep5.gif": "",
        "pod-racing.gif": "",
        "power-dark-side.gif": "",
        "q_Ahsoka_ezra.gif": "",
        "q_Ep1_itsWorking.gif": "",
        "q_Ep2_begunclonewar.gif": "",
        "q_Ep2_simplemantryingto.gif": "",
        "q_Ep3_anakin_wegotemr2.gif": "",
        "q_Ep3_flyingisfordroids.gif": "",
        "q_Ep3_souncivilized.gif": "",
        "q_Ep5_Yoda_mine.gif": "",
        "q_Ep5_leia_goback.gif": "",
        "q_Ep5_vader.gif": "",
        "q_Ep5_vaderVlukesurpirses.gif": "",
        "q_Ep6_Ewok_Grr.gif": "",
        "q_Ep6_Sheilddeactive.gif": "",
        "q_Ep6_Vader_hopeso.gif": "",
        "q_Ep6_c3p0.gif": "",
        "q_Ep6_doublefforts.gif": "",
        "q_Ep6_freeusordie.gif": "",
        "q_Ep6_leia_freeze.gif": "",
        "q_Ep6_leia_someonewholovesyou.gif": "",
        "q_Ep6_monthmaunprotected.gif": "",
        "q_Ep6_yoda_luke_Forceinfamily.gif": "",
        "q_Ep7_c3p0missyou.gif": "",
        "q_Ep7_finn_escape.gif": "",
        "q_Ep7_finn_usetheforce.gif": "",
        "q_Ep7_nothowtheforceworks.gif": "",
        "q_ahsoka_Forceanakin.gif": "",
        "q_ahsoka_ahsoka.gif": "",
        "q_ahsoka_ahsoka2.gif": "",
        "q_ahsoka_ahsoka3.gif": "",
        "q_ahsoka_ahsoka4.gif": "",
        "q_ahsoka_anakin.gif": "",
        "q_ahsoka_cw.gif": "",
        "q_ahsoka_droid.gif": "",
        "q_ahsoka_droid2.gif": "",
        "q_ahsoka_droid3.gif": "",
        "q_ahsoka_droid4.gif": "",
        "q_ahsoka_droid5.gif": "",
        "q_ahsoka_ezra2.gif": "",
        "q_ahsoka_ezra3.gif": "",
        "q_ahsoka_ezra4.gif": "",
        "q_ahsoka_flashb.gif": "",
        "q_ahsoka_hera.gif": "",
        "q_ahsoka_hera2.gif": "",
        "q_ahsoka_hera_mtfbwy.gif": "",
        "q_ahsoka_nightsiste.gif": "",
        "q_ahsoka_sabine.gif": "",
        "q_ahsoka_sabine2.gif": "",
        "q_ahsoka_sabine3.gif": "",
        "q_ahsoka_sabine4.gif": "",
        "q_ahsoka_sabine5.gif": "",
        "q_ahsoka_sith.gif": "",
        "q_ahsoka_sith2.gif": "",
        "q_ahsoka_sith3.gif": "",
        "q_ahsoka_sith4.gif": "",
        "q_ahsoka_thrawn.gif": "",
        "q_ahsoka_thrawn2.gif": "",
        "q_ahsoka_thrawn3.gif": "",
        "q_ahsoka_thrawn4.gif": "",
        "q_ahsoka_thrawn5.gif": "",
        "q_ahsoka_thrawn6.gif": "",
        "q_ahsoka_thrawn7.gif": "",
        "q_ahsoka_thrawn_fortheempire.gif": "",
        "q_ahsoka_thrawn_longliveempire.gif": "",
        "q_ahsoka_wbw.gif": "",
        "q_ahsoka_wbw2.gif": "",
        "q_ep1_3p0PartsShowing.gif": "",
        "q_ep1_AniYoureAJediToo.gif": "",
        "q_ep1_ahVictory.gif": "",
        "q_ep1_anakinMeetObiwan.gif": "",
        "q_ep1_angel.gif": "",
        "q_ep1_biggerFish.gif": "",
        "q_ep1_c3p0JarJarlittleOdd.gif": "",
        "q_ep1_c3p0WhereIsEverybody.gif": "",
        "q_ep1_council_mtfbwy.gif": "",
        "q_ep1_doesntCompute.gif": "",
        "q_ep1_endingPEACE.gif": "",
        "q_ep1_endingYouwillbejediOBiwan.gif": "",
        "q_ep1_gunray.gif": "",
        "q_ep1_jarjar.gif": "",
        "q_ep1_jarjar_3.gif": "",
        "q_ep1_jarjar_4.gif": "",
        "q_ep1_jarjar_5.gif": "",
        "q_ep1_jarjar_7.gif": "",
        "q_ep1_jarjar_8.gif": "",
        "q_ep1_mass.gif": "",
        "q_ep1_mass_!.gif": "",
        "q_ep1_mass_2.gif": "",
        "q_ep1_mass_3.gif": "",
        "q_ep1_mass_4.gif": "",
        "q_ep1_mass_5.gif": "",
        "q_ep1_momSaidPeopleDontHelp.gif": "",
        "q_ep1_no1killJedi.gif": "",
        "q_ep1_nowthisispodracing.gif": "",
        "q_ep1_padmeANAKIN.gif": "",
        "q_ep1_personNameIsAnakin.gif": "",
        "q_ep1_podracing.gif": "",
        "q_ep1_podracing_1.gif": "",
        "q_ep1_quigon.gif": "",
        "q_ep1_tryspinning_goodtrick.gif": "",
        "q_ep1_watchcareerwithgreatinterest.gif": "",
        "q_ep1_yippe.gif": "",
        "q_ep1_yoda_FearPathDarkside.gif": "",
        "q_ep1_yoda_HardToSeeDarkSide.gif": "",
        "q_ep2_anakin_badfeelingaboutthis.gif": "",
        "q_ep2_anakin_dontworrywehaver2.gif": "",
        "q_ep2_anakin_obiwangrumpyifcaughtme.gif": "",
        "q_ep2_anakin_youreexactlyasirememberinmydreams.gif": "",
        "q_ep2_boba_yep.gif": "",
        "q_ep2_c3p0_droid_programmedforetiquette.gif": "",
        "q_ep2_c3p0confused.gif": "",
        "q_ep2_c3p0terriblysorry.gif": "",
        "q_ep2_darkSideCloudsEverythingYoda.gif": "",
        "q_ep2_dex.gif": "",
        "q_ep2_dexHeyOldBuddy.gif": "",
        "q_ep2_dex_whattyaknow.gif": "",
        "q_ep2_diplomaticSolution.gif": "",
        "q_ep2_dontmindFlyingButSuicide.gif": "",
        "q_ep2_dooku_sorryoldfriend.gif": "",
        "q_ep2_goHomeRethinkLife.gif": "",
        "q_ep2_goodcallyoungpadawan.gif": "",
        "q_ep2_iSenseitToo.gif": "",
        "q_ep2_idontlikesand.gif": "",
        "q_ep2_ilovedemocracy.gif": "",
        "q_ep2_impossibleToSeeFuture.gif": "",
        "q_ep2_jango_alwayspleasuretomeetjedi.gif": "",
        "q_ep2_jango_packbags.gif": "",
        "q_ep2_kenobi_goodjob.gif": "",
        "q_ep2_kenobi_possibly.gif": "",
        "q_ep2_mace_keepersofPeaceNotSoldiers.gif": "",
        "q_ep2_mace_thispartysover.gif": "",
        "q_ep2_negotationsNotFailPalpatine.gif": "",
        "q_ep2_obiwan.gif": "",
        "q_ep2_obiwanAniLittleOnEdge.gif": "",
        "q_ep2_obiwanSweatingTakeDeepBreath.gif": "",
        "q_ep2_obiwanUseTheForceThink.gif": "",
        "q_ep2_obiwanWHAT.gif": "",
        "q_ep2_obiwan_goodnews.gif": "",
        "q_ep2_obiwan_hateitwhenhedoeshtat.gif": "",
        "q_ep2_obiwan_kamino.gif": "",
        "q_ep2_padme_dontgrowuptoofast.gif": "",
        "q_ep2_padme_dontlookatmelikethat.gif": "",
        "q_ep2_padme_makingfunofme.gif": "",
        "q_ep2_personalFeelings.gif": "",
        "q_ep2_rogerroger.gif": "",
        "q_ep2_suchdrag.gif": "",
        "q_ep2_yoda_howembarassing.gif": "",
        "q_ep2_yoda_muchtolearnyoustillhave.gif": "",
        "q_ep3_Crawl.gif": "",
        "q_ep3_Dooku_twicepridedoublefall.gif": "",
        "q_ep3_ExecuteOrder66.gif": "",
        "q_ep3_allegience.gif": "",
        "q_ep3_alwaysonthemove.gif": "",
        "q_ep3_anakinSoBeautiful.gif": "",
        "q_ep3_badfeelingaboutthis.gif": "",
        "q_ep3_chosenone.gif": "",
        "q_ep3_doit.gif": "",
        "q_ep3_donttryit.gif": "",
        "q_ep3_dookuSenseMuchFear.gif": "",
        "q_ep3_failedYouAnakin.gif": "",
        "q_ep3_fearispathtodarkside.gif": "",
        "q_ep3_forcestronginyou.gif": "",
        "q_ep3_goodbyeOldFriend.gif": "",
        "q_ep3_grevious.gif": "",
        "q_ep3_happylanding.gif": "",
        "q_ep3_heldhostageutapau.gif": "",
        "q_ep3_helpmehelpme.gif": "",
        "q_ep3_highground.gif": "",
        "q_ep3_intoexile.gif": "",
        "q_ep3_isenseatrap.gif": "",
        "q_ep3_ishouldnt.gif": "",
        "q_ep3_itstreasonthen.gif": "",
        "q_ep3_killhim.gif": "",
        "q_ep3_libertydies.gif": "",
        "q_ep3_lostwill.gif": "",
        "q_ep3_mtfbwya.gif": "",
        "q_ep3_mustrealizedoome.gif": "",
        "q_ep3_nonono.gif": "",
        "q_ep3_noooo.gif": "",
        "q_ep3_nowthatsbetter.gif": "",
        "q_ep3_ohidontthinkso.gif": "",
        "q_ep3_ohitsyou.gif": "",
        "q_ep3_ohthisgoingtobeeasy.gif": "",
        "q_ep3_order66.gif": "",
        "q_ep3_padmeAnakinMustafar.gif": "",
        "q_ep3_palpatine_goodnews.gif": "",
        "q_ep3_patiencerayshield.gif": "",
        "q_ep3_planb.gif": "",
        "q_ep3_resolve.gif": "",
        "q_ep3_senatedecidefate.gif": "",
        "q_ep3_shorterthaniexpected.gif": "",
        "q_ep3_takeaseat.gif": "",
        "q_ep3_tragedy.gif": "",
        "q_ep3_underarrest.gif": "",
        "q_ep3_underestimatemypower.gif": "",
        "q_ep3_unlimitedPOwer.gif": "",
        "q_ep3_usemyknowledge.gif": "",
        "q_ep3_yodasidious.gif": "",
        "q_ep4_Forceweakminded.gif": "",
        "q_ep4_Vader_partrebelalliance.gif": "",
        "q_ep4_Vader_passengersalive.gif": "",
        "q_ep4_ben.gif": "",
        "q_ep4_ben_beforeempire.gif": "",
        "q_ep4_ben_comeherelittlefriend.gif": "",
        "q_ep4_ben_dontseehisid.gif": "",
        "q_ep4_ben_fearsomethingterrible.gif": "",
        "q_ep4_ben_forcewillbewithyou.gif": "",
        "q_ep4_ben_hellothere.gif": "",
        "q_ep4_ben_iknowhimheme.gif": "",
        "q_ep4_ben_learnforceluke.gif": "",
        "q_ep4_ben_learnthewaysofforce.gif": "",
        "q_ep4_ben_oncejediknight.gif": "",
        "q_ep4_ben_strikemedown.gif": "",
        "q_ep4_c3p0_Regretthis.gif": "",
        "q_ep4_c3p0noescapeprincess.gif": "",
        "q_ep4_elegantweapon.gif": "",
        "q_ep4_han_donteveryonethankme.gif": "",
        "q_ep4_han_imhansolo.gif": "",
        "q_ep4_han_neverheardofmilleniumfalcon.gif": "",
        "q_ep4_han_shipmadekesselrun12parsecs.gif": "",
        "q_ep4_han_yahoo.gif": "",
        "q_ep4_hologramleia.gif": "",
        "q_ep4_leia_dontknowhoyouare.gif": "",
        "q_ep4_leia_helpmeobiwanekenobi.gif": "",
        "q_ep4_leia_sass.gif": "",
        "q_ep4_leia_senatenotstand.gif": "",
        "q_ep4_leia_shortforastormtrooper.gif": "",
        "q_ep4_luke_badfeelingaboutthis.gif": "",
        "q_ep4_luke_fightagainstempire.gif": "",
        "q_ep4_luke_force.gif": "",
        "q_ep4_luke_foughtinclonewars.gif": "",
        "q_ep4_luke_whoisshebeautiful.gif": "",
        "q_ep4_lukebecomejedi.gif": "",
        "q_ep4_namenotheardinlongtime.gif": "",
        "q_ep4_notdroidsyoulookingfor.gif": "",
        "q_ep4_oncefatherlightsaber.gif": "",
        "q_ep4_tarkin_Fearkeeptheminline.gif": "",
        "q_ep4_tarkin_crushrebellion.gif": "",
        "q_ep4_tarkinandleia.gif": "",
        "q_ep4_vader_Transmissionchoke.gif": "",
        "q_ep4_vader_destroyplanetforce.gif": "",
        "q_ep4_vader_facehimalone.gif": "",
        "q_ep4_vader_happenedtoplans.gif": "",
        "q_ep4_vader_lackoffaith.gif": "",
        "q_ep4_vaderwemeetagainatlast.gif": "",
        "q_ep4_wonderifhemeansben.gif": "",
        "q_ep4_wretchedhive.gif": "",
        "q_ep5_Ben2.gif": "",
        "q_ep5_Vader_Destroyyou.gif": "",
        "q_ep5_Vader_mostimpressive.gif": "",
        "q_ep5_Yoda.gif": "",
        "q_ep5_Yoda_Thatiswhyyoufail.gif": "",
        "q_ep5_Yoda_energysurroundsus.gif": "",
        "q_ep5_ben.gif": "",
        "q_ep5_c3p0_waitforme.gif": "",
        "q_ep5_doordonot.gif": "",
        "q_ep5_han.gif": "",
        "q_ep5_han_punchit.gif": "",
        "q_ep5_han_watchthis.gif": "",
        "q_ep5_lando.gif": "",
        "q_ep5_leia.gif": "",
        "q_ep5_leia_iloveyou.gif": "",
        "q_ep5_leia_vaderwantsusdead.gif": "",
        "q_ep5_luke_nooo.gif": "",
        "q_ep5_lukeforce.gif": "",
        "q_ep5_palpatine.gif": "",
        "q_ep5_palpatine2.gif": "",
        "q_ep5_r2.gif": "",
        "q_ep5_vader_Destiny.gif": "",
        "q_ep5_vader_Failedmelasttime.gif": "",
        "q_ep5_vader_dontfailme.gif": "",
        "q_ep5_vader_iamyourfather.gif": "",
        "q_ep5_xwing.gif": "",
        "q_ep5_yeti.gif": "",
        "q_ep5_yoda_judgemebysize.gif": "",
        "q_ep6_Deathstaronschedule.gif": "",
        "q_ep6_akbar_force.gif": "",
        "q_ep6_badfeeling.gif": "",
        "q_ep6_boba.gif": "",
        "q_ep6_greetingsexaltedone.gif": "",
        "q_ep6_grr.gif": "",
        "q_ep6_han.gif": "",
        "q_ep6_han_gl.gif": "",
        "q_ep6_han_ohgreat.gif": "",
        "q_ep6_luke.gif": "",
        "q_ep6_luke_vaderonthatship.gif": "",
        "q_ep6_palpatine.gif": "",
        "q_ep6_palpatine_compassion.gif": "",
        "q_ep6_trap.gif": "",
        "q_ep7_Rey_jedimindtrick.gif": "",
        "q_ep7_c3p0.gif": "",
        "q_ep7_escapenow_huglater.gif": "",
        "q_ep7_finishwhatstarted.gif": "",
        "q_ep7_finn_phasma.gif": "",
        "q_ep7_finn_poeineedurhelp.gif": "",
        "q_ep7_finn_stormtrooper.gif": "",
        "q_ep7_fn2187.gif": "",
        "q_ep7_galaxycountingonus.gif": "",
        "q_ep7_han.gif": "",
        "q_ep7_han2.gif": "",
        "q_ep7_han_chewiegetready.gif": "",
        "q_ep7_hanstolefalcon.gif": "",
        "q_ep7_kylo.gif": "",
        "q_ep7_kylo_lightsaberbelongstome.gif": "",
        "q_ep7_kylo_show.gif": "",
        "q_ep7_kylo_traitor.gif": "",
        "q_ep7_leia.gif": "",
        "q_ep7_leia_mtfwbwy.gif": "",
        "q_ep7_leia_tellme.gif": "",
        "q_ep7_leiafinn.gif": "",
        "q_ep7_leialuke.gif": "",
        "q_ep7_maz.gif": "",
        "q_ep7_maz2.gif": "",
        "q_ep7_needpilot.gif": "",
        "q_ep7_poe.gif": "",
        "q_ep7_poe_xwing.gif": "",
        "q_ep7_poejacket.gif": "",
        "q_ep7_poetalkfirst.gif": "",
        "q_ep7_programmedfrombirth.gif": "",
        "q_ep7_rey.gif": "",
        "q_ep7_rey_lukemyth.gif": "",
        "q_ep7_rey_withresistance.gif": "",
        "q_ep7_worse.gif": "",
        "q_ep8_bb8.gif": "",
        "q_ep8_salt.gif": "",
        "q_ep8_yoda_greatestteacher.gif": "",
        "q_han_driver.gif": "",
        "q_mando_Exactly_jackblack.gif": "",
        "q_mando_Feelingyouhatedme.gif": "",
        "q_mando_badbaby.gif": "",
        "q_mando_billbur.gif": "",
        "q_mando_bokatan_thisistheway.gif": "",
        "q_mando_dontbebaby.gif": "",
        "q_mando_fly_mtfbwy.gif": "",
        "q_mando_fool.gif": "",
        "q_mando_interesting.gif": "",
        "q_mando_jedi.gif": "",
        "q_mando_karga.gif": "",
        "q_mando_playtimeover.gif": "",
        "q_mando_pogsoup.gif": "",
        "q_mando_thisistheway.gif": "",
        "q_mando_thisistheway2.gif": "",
        "q_mando_tuesdays.gif": "",
        "q_mando_wait.gif": "",
        "q_mando_welcomeback.gif": "",
        "q_mando_yes.gif": "",
        "q_roge1_k2s0.gif": "",
        "q_rogue1_akbar_mtfbwy.gif": "",
        "q_rogue1_backup.gif": "",
        "q_rogue1_explosion.gif": "",
        "q_rogue1_farming.gif": "",
        "q_rogue1_jyn.gif": "",
        "q_rogue1_k2s0.gif": "",
        "q_rogue1_k2s01.gif": "",
        "q_rogue1_krennic.gif": "",
        "q_rogue1_krennic2.gif": "",
        "q_rogue1_myachievement.gif": "",
        "q_rogue1_onewithforce.gif": "",
        "q_rogue1_rebel.gif": "",
        "q_rogue1_rescued.gif": "",
        "q_rogue1_vader.gif": "",
        "q_rogue1_vaderhelpus.gif": "",
        "q_solo_inthislifeforgood.gif": "",
        "q_solo_lando.gif": "",
        "roger-roger.gif": "",
        "rose-cringe-ep8.gif": "",
        "sense-fear-yoda.gif": "",
        "simple-man-trying-to.gif": "",
        "somehow-palpatine-returned.gif": "",
        "take-a-seat.gif": "",
        "the-senate.gif": "",
        "this-is-the-way.gif": "",
        "verge-of-greatness.gif": ""
    }

    random_key = random.choice(list(gif_dict.keys()))
    gif_url = "https://raw.githubusercontent.com/spencermarshall/StarWarsTwitterPost/main/images/quote-or-meme/" + random_key

    temp_filename = '/tmp/temp_media.gif'

    # Download the GIF
    response = requests.get(gif_url)
    if response.status_code == 200:
        with open(temp_filename, 'wb') as temp_file:
            temp_file.write(response.content)

        media = api.media_upload(temp_filename)

        tweet_text = ""

        ran = random.random()
        if ran < 0.10:
            tweet_text += "Star Wars"
        elif ran < 0.11:
            tweet_text += "#StarWars"
        elif ran < 0.12:
            tweet_text += "#swtwt"

        client.create_tweet(text=tweet_text, media_ids=[media.media_id])

        os.remove(temp_filename)

        return "Tweet posted successfully!"
    else:
        return "Failed to download GIF."
