import random
import boto3
import tweepy
import os
import json

# X credentials stored in env variables
API_KEY = os.environ["API_KEY"]
API_SECRET_KEY = os.environ["API_SECRET_KEY"]
ACCESS_TOKEN = os.environ["ACCESS_TOKEN"]
ACCESS_TOKEN_SECRET = os.environ["ACCESS_TOKEN_SECRET"]
BEARER_TOKEN = os.environ["BEARER_TOKEN"]

auth = tweepy.OAuth1UserHandler(API_KEY, API_SECRET_KEY, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

client = tweepy.Client(
    bearer_token=BEARER_TOKEN,
    consumer_key=API_KEY,
    consumer_secret=API_SECRET_KEY,
    access_token=ACCESS_TOKEN,
    access_token_secret=ACCESS_TOKEN_SECRET
)


def BB_question(event, context):
    questions = {
        1: "What's the most underrated episode in Breaking Bad?",
        2: "What's the most underrate episode in Better Call Saul?",
        3: "How many times have you watched Better Call Saul?",
        4: "How do you view Jesse’s struggle in Breaking Bad?",
        5: "What makes Saul so intriguing in Breaking Bad/Better Call Saul?",
        6: "Does Kim Wexler resonate with you in Better Call Saul?",
        7: "Which moment shocked you the most in Breaking Bad?",
        8: "What’s the most iconic scene in Breaking Bad?",
        9: "Which Breaking Bad character is most relatable?",
        10: "What fuels Gus Fring’s cold nature in Breaking Bad?",
        11: "What's the most controversial decision in Breaking Bad?",
        12: "Which character had the most satisfying arc in Breaking Bad?",
        13: "Is Better Call Saul better than Breaking Bad?",
        14: "Do you like how law enforcement is portrayed in Breaking Bad?",
        15: "When does Jimmy turn into Saul in Better Call Saul?",
        16: "Is Jimmy’s dual nature intriguing in Better Call Saul?",
        17: "Does humor lighten Better Call Saul’s dark tone?",
        18: "Who’s the most tragic character in Better Call Saul?",
        19: "Did you like the ending of Better Call Saul?",
        20: "Are the moral gray areas in Breaking Bad compelling?",
        21: "What are your thoughts on how Breaking Bad addresses addiction?",
        22: "What’s your favorite episode of Better Call Saul?",
        23: "Is Breaking Bad’s pacing effective?",
        24: "What are your thoughts on how the cartel is depicted in Breaking Bad?",
        25: "Most underrated character in Better Call Saul?",
        26: "To what extent does family actually influence Walter’s choices in Breaking Bad?",
        27: "Most overrated character in Better Call Saul?",
        28: "Who is the best written character in Better Call Saul?",
        29: "How do you view Breaking Bad’s overall pacing?",
        30: "What’s the most compelling subplot in Better Call Saul?",
        31: "Did Jesse Pinkman get the ending he deserved in Breaking Bad / El Camino?",
        32: "Which Breaking Bad character transforms most dramatically?",
        33: "Is foreshadowing effective in Breaking Bad?",
        34: "Is Better Call Saul a worthy spin-off?",
        35: "What is the most memorable quote from Breaking Bad?",
        36: "What is the most memorable quote from Better Call Saul?",
        37: "Who is your favorite character in Better Call Saul?",
        38: "Who is your favorite character in Breaking Bad?",
        39: "Who is your least favorite character in Better Call Saul?",
        40: "What are your thoughts on how the legal system is portrayed in Better Call Saul?",
        41: "Are the subtle hints in Breaking Bad effective or confusing?",
        42: "Who is your favorite Breaking Bad villain?",
        43: "How is desperation portrayed as survival in Breaking Bad?",
        44: "Who is your least favorite character in Breaking Bad?",
        45: "What is your favorite Walter White quote?",
        46: "What is your favorite Jesse Pinkman quote?",
        47: "What is your favorite Saul Goodman quote?",
        48: "Which Breaking Bad character is most misunderstood?",
        49: "What’s your take on Jimmy’s legal evolution in Better Call Saul?",
        50: "What legacy do Breaking Bad and Better Call Saul leave?",
        51: "What is your favorite comedic moment in Breaking Bad?",
        52: "What is your favorite comedic moment from Better Call Saul",
        53: "Does Albuquerque set the right mood in Breaking Bad?",
        54: "Which is your favorite Breaking Bad Season?",
        55: "What’s the most memorable moment in Better Call Saul?",
        56: "Which is your favorite Better Call Saul Season?",
        57: "Which is your favorite Breaking Bad episode?",
        58: "Which is your favorite Better Call Saul episode?",
        59: "What stands out in Jesse’s evolution in Breaking Bad?",
        60: "Is trust built or broken in Better Call Saul?",
        61: "What are your thoughts on the relationship between Walter White and Jesse in Breaking Bad?",
        62: "What are your thoughts on the relationship between Jimmy and Kim in Better Call Saul?",
        63: "What are your thoughts on the relationship between Walter White and Skyler in Breaking Bad?",
        64: "What are your thoughts on the relationship between Walter White and Hank in Breaking Bad?",
        65: "What are your thoughts on the relationship between Walter White and Gustavo Fring in Breaking Bad?",
        66: "What are your thoughts on the relationship between Walter White and Saul Goodman in Breaking Bad?",
        67: "What are your thoughts on the relationship between Jesse Pinkman and Jane in Breaking Bad?",
        68: "Are Breaking Bad’s color cues effective?",
        69: "Is Saul Goodman’s inflatable Statue of Liberty odd or iconic in Better Call Saul?",
        70: "What are your thoughts on Saul Goodman’s office in Better Call Saul?",
        71: "What lessons on power stand out in Breaking Bad?",
        72: "Are Saul Goodman’s commercials memorable in Better Call Saul?",
        73: "What’s your take on Saul Goodman in Breaking Bad?",
        74: "How does Saul differ in Better Call Saul compared to Breaking Bad?",
        95: "What is your favorite moment involving Walter White?",
        96: "What is your favorite moment involving Jesse Pinkman?",
        97: "What is your favorite moment involving Gus Fring?",
        98: "What is your favorite moment involving Saul Goodman?",
        99: "What is your favorite moment involving Mike Ehrmantraut?",
        100: "What is your favorite moment involving Hank Schrader?",
        101: "What is your favorite moment involving Skyler White?",
        102: "Walter White or Jimmy McGill?",
        103: "Breaking Bad or Better Call Saul?",
        104: "What’s your favorite Breaking Bad episode?",
        105: "What’s your favorite Better Call Saul episode?",
        106: "Who is your favorite Breaking Bad character?",
        107: "Who is your favorite Better Call Saul character?",
        108: "What are your thoughts on Walter’s transformation in Breaking Bad?",
        109: "What are your thoughts on Jimmy turning into Saul in Better Call Saul?",
        110: "Is Gus Fring the top villain in Breaking Bad?",
        111: "How did Skyler White impact Breaking Bad’s story?",
        112: "Are Jimmy & Kim the best duo in Better Call Saul?",
        113: "Did you like the ending of Breaking Bad?",
        114: "What are your thoughts on the finale of Better Call Saul?",
        115: "What are your views on the Salamanca family in Breaking Bad?",
        116: "Is the bond between Walt & Jesse strong in Breaking Bad?",
        117: "What are your thoughts on Lalo Salamanca in Better Call Saul?",
        118: "What are your thoughts on Nacho in Better Call Saul?",
        119: "Is Hank Schrader the top DEA in Breaking Bad?",
        120: "What are your thoughts on Bryan Cranston's portrayl of Walter White?",
        121: "What are your thoughts on Aaron Paul's portrayal of Jesse Pinkman?",
        122: "What are your thoughts on Bob Odenkirk's portrayal of Saul Goodman?",
        123: "What are your thoughts on Jonathan Banks' portrayal of Mike Ehrmantraut?",
        124: "What are your thoughts on Giancarlo Esposito's portrayal of Gus Fring?",
        125: "What are your thoughts on Dean Norris' portrayal of Hank Schrader?",
        126: "What are your thoughts on Anna Gunn's portrayal of Skyler White?",
        127: "What are your thoughts on Rhea Seehorn's portrayal of Kim Wexler?",
        128: "What are your thoughts on Patrick Fabian's portrayal of Howard Hamlin?",
        129: "What are your thougths on Michael McKean's portrayal of Chuck McGill?",
        130: "How many times have you watched Breaking Bad?",
        131: "What are your thoughts on Hector Salamanca in Breaking Bad?",
        132: "What are your thoughts on Mike Ehrmantraut in Breaking Bad?",
        133: "What are your thoughts on Jesse Pinkman in Breaking Bad?",
        134: "What are your thoughts on the Cameo's in Better call Saul?",
        135: "What are your thoughts on the music in Breaking Bad?",
        136: "What are your thoughts on Walter White Jr. in Breaking Bad?",
        137: "What are your thoughts on Steven Gomez in Breaking Bad?",
        138: "What are your thoughts on Marie Schrader in Breaking Bad?",
        139: "What are your thoughts on Tuco Salamanca in Breaking Bad?",
        140: "What are your thoughts on Todd Alquist in Breaking Bad?",
        141: "What are your thoughts on Lydia Rodarte-Quayle in Breaking Bad?",
        142: "What are your thoughts on Howard Hamlin in Better Call Saul?",
        143: "What are your thoughts on Chuck McGill in Better Call Saul?",
        144: "What are your thoughts on Gene Takavic as a character in Better Call Saul?",
        145: "What are your thoughts on Francesca in Better Call Saul?",
        146: "What are your thoughts on Huell Babineaux in Breaking Bad?",
        147: "What are your thoughts on Krazy-8 in Breaking Bad?",
        148: "What are your thoughts on Jane from Breaking Bad?",
        149: "What are your thoughts on Gale Boetticher in Breaking Bad?",
        150: "What are your thoughts on Don Eladio in Breaking Bad?",
        151: "What are your thoughts on Wendy in Breaking Bad?",
        152: "Thoughts on Tyrus Kitt in Breaking Bad?",
        153: "What are your thoughts on Skinny Pete in Breaking Bad?",
        154: "What are your thoughts on Badger in Breaking Bad?",
        155: "What are your thoughts on Combo in Breaking Bad?",
        156: "What are your thoughts on RJ Mitte's portrayal of Walter White Jr. in Breaking Bad?",
        157: "What are your thoughts on Betsy Brandt's performance as Marie Schrader in Breaking Bad?",
        158: "What are your thoughts on Tony Dalton's portrayal of Lalo Salamanca in Better Call Saul?",
        159: "What are your thoughts on Mark Margolis's performance as Hector Salamanca in Breaking Bad?",
        160: "What are your thoughts on David Costabile's portrayal of Gale Boetticher in Breaking Bad?",
        161: "What are your thoughts on Michael Mando's performance as Nacho Varga in Better Call Saul?",
        162: "What are your thoughts on Bill Burr's cameo in Breaking Bad?",
        163: "What is your overall opinion on the main actors in Breaking Bad and Better Call Saul?",
        164: "How do you feel about the actors' chemistry in high-tension scenes in Better Call Saul?",
        165: "What are your thoughts on the casting choices in Better Call Saul?",
        166: "Which actor's performance in Breaking Bad surprised you the most?",
        167: "Which actor's performance in Better Call Saul surprised you the most?",
        168: "What are your thoughts on the character development in Breaking Bad?",
        169: "How do you rate the overall performances of the main actors in Breaking Bad?",
        170: "How do you rate the overall performances of the main actors in Better Call Saul?",
        171: "Why do you think Breaking Bad has such a strong fanbase?",
        172: "Should there be a sequel to Breaking Bad? What would it be about?",
        173: "If you could meet one character from Breaking Bad, who would it be?",
        174: "If you could change one thing about Breaking Bad, what would it be?",
        175: "On a scale of 1-10, how would you rate Breaking Bad?",
        176: "On a scale of 1-10, how would you rate Better Call Saul?",
        177: "How old were you when you first watched Breaking Bad?",
        178: "How did you first hear about Breaking Bad?",
        179: "What were your thoughts after watching the first episode of Breaking Bad?",
        180: "What were your thoughts after watching the first episode of Better Call Saul?",
        181: "What are your thoughts on El Camino?",
        182: "How do you feel about Jesse Pinkman's character development in El Camino?",
        183: "What are your thoughts on the ending of El Camino?",
        184: "What are your thoughts on the cameos in El Camino?",
        185: "On a scale of 1-10, how would you rate El Camino?",
        186: "What is your favorite part from El Camino?",
        187: "What is your least favorite part from El Camino?",
        188: "What are your thoughts on the future of the Breaking Bad universe?",
        189: "Should we get another Breaking Bad Spinoff Show?",
        #was todd justified in killing the kid
        #fly episode
    }

    # s3 bucket files look up
    lookup = {
        1: "None",
        2: "None",
        3: "None",
        4: "None",
        5: "None",
        6: "None",
        7: "None",
        8: "None",
        9: "None",
        10: "None",
        11: "None",
        12: "None",
        13: "None",
        14: "None",
        15: "None",
        16: "None",
        17: "None",
        18: "None",
        19: "None",
        20: "None",
        21: "None",
        22: "None",
        23: "None",
        24: "None",
        25: "None",
        26: "None",
        27: "None",
        28: "None",
        29: "None",
        30: "None",
        31: "None",
        32: "None",
        33: "None",
        34: "None",
        35: "None",
        36: "None",
        37: "None",
        38: "None",
        39: "None",
        40: "None",
        41: "None",
        42: "None",
        43: "None",
        44: "None",
        45: "None",
        46: "None",
        47: "None",
        48: "None",
        49: "None",
        50: "None",
        51: "None",
        52: "None",
        53: "None",
        54: "None",
        55: "None",
        56: "None",
        57: "None",
        58: "None",
        59: "None",
        60: "None",
        61: "None",
        62: "None",
        63: "None",
        64: "None",
        65: "None",
        66: "None",
        67: "None",
        68: "None",
        69: "None",
        70: "None",
        71: "None",
        72: "None",
        73: "None",
        74: "None",
        75: "None",
        76: "None",
        77: "None",
        78: "None",
        79: "None",
        80: "None",
        81: "None",
        82: "None",
        83: "None",
        84: "None",
        85: "None",
        86: "None",
        87: "None",
        88: "None",
        89: "None",  # "questions/char_Yoda(puppet)/", #yoda puppet
        90: "None",
        91: "None",
        92: "None",
        93: "None",
        94: "None",
        95: "None",
        96: "None",
        97: "None",
        98: "None",
        99: "None",
        100: "None",
        101: "None",
        102: "None",
        103: "None",
        104: "None",
        105: "None",
        106: "None",
        107: "None",
        108: "None",
        109: "None",
        110: "None",
        111: "None",
        112: "None",
        113: "None",
        114: "None",
        115: "None",
        116: "None",
        117: "None",
        118: "None",
        119: "None",
        120: "None",
        121: "None",
        122: "None",
        123: "None",
        124: "None",
        125: "None",
        126: "None",
        127: "None",
        128: "None",
        129: "None",
        130: "None",
        131: "None",
        132: "None",
        133: "None",
        134: "None",
        135: "None",
        136: "None",
        137: "None",
        138: "None",
        139: "None",
        140: "questions/char_ToddAlquist/",
        141: "None",
        142: "None",
        143: "None",
        144: "None",
        145: "None",
        146: "None",
        147: "None",
        148: "None",
        149: "None",
        150: "None",
        151: "None",
        152: "None",
        153: "None",
        154: "None",
        155: "None",
        156: "None",
        157: "None",
        158: "None",
        159: "None",
        160: "None",
        161: "None",
        162: "None",
        163: "None",
        164: "None",
        165: "None",
        166: "None",
        167: "None",
        168: "None",
        169: "None",
        170: "None",
        171: "None",
        172: "None",
        173: "None",
        174: "None",
        175: "None",
        176: "None",
        177: "None",
        178: "None",
        179: "None",
        180: "None",
        181: "None",
        182: "None",
        183: "None",
        184: "None",
        185: "None",
        186: "None",
        187: "None",
        188: "None",
        189: "None",
        190: "None",
        191: "None",
        192: "None",
        193: "None",
        194: "None",
        195: "None",
        196: "None",
        197: "None",
        198: "None",
        199: "None",
        200: "None",
        201: "None",
        202: "None",
        203: "None",
        204: "None",
        205: "None",
        206: "None",
        207: "None",
        208: "None",
        209: "None",
        210: "None",
        211: "None",
        212: "None",
        213: "None",
        214: "None",
        215: "None",  # "questions/char_JudeLaw/",
        216: "None",  # "questions/char_Omega/",
        217: "None",  # "questions/char_Crosshair/",
        218: "None",  # "questions/char_Hunter/",
        219: "None",  # "questions/char_Tech/",
        220: "None",  # "questions/char_Wrecker/",
        221: "None",  # "questions/char_Echo/",
        222: "None",
        223: "None",
        224: "None",
        225: "None",
        226: "None",  # "questions/char_Leia(Kenobi-show)/",
        227: "None",  # "questions/char_Obi-Wan(Kenobi-Show)/",
        228: "None",  # "questions/char_Vader(Kenobi-show)/",
        229: "None",  # "questions/char_OwenBeruLars(Kenobi-show)/",
        230: "None",
        231: "None",  # "questions/char_SenatorOrgana(Kenobi-Show)/",
        232: "None",  # "questions/char_Kumail(Kenobi-Show)/",
        233: "None"  # "questions/char_DarthJarJar/"
    }

    bucket_name = 'bb.photos'
    file_key = 'notes/BB_questions.txt'
    s3 = boto3.client('s3')

    try:
        # Fetch the current file from S3
        response = s3.get_object(Bucket=bucket_name, Key=file_key)
        file_content = response['Body'].read().decode('utf-8')

        # Convert the file content (string) into a Python list
        question_indices = json.loads(file_content)
        print(question_indices)

        index = random.randint(1, len(questions))

        # try again until we get new item not in list
        while index in question_indices:
            index = random.randint(1, len(questions))

        path = lookup[index]

        question_indices.insert(0, index)
        if len(question_indices) > 100:
            question_indices.pop()  # Remove the last element

        updated_content = json.dumps(question_indices)

        s3.put_object(Bucket=bucket_name, Key=file_key, Body=updated_content)
        question = questions[index]

        if path == "None":  # upload just text, no image
            client.create_tweet(text=question)
            return f"POSTED TWEET {question} with no image"

        response = s3.list_objects_v2(Bucket=bucket_name, Prefix=path)
        if 'Contents' not in response:
            return {
                'statusCode': 404,
                'body': 'No files found in the specified directory.'
            }
        # Extract file keys (paths) from the response
        file_keys = [obj['Key'] for obj in response['Contents'] if obj['Key'] != path]
        # Check if there are files to choose from
        if not file_keys:
            return {
                'statusCode': 404,
                'body': 'No files found in the specified directory.'
            }

        # Pick a random file from the list
        random_file = random.choice(file_keys)

        # these 4 are for image, not implemented yet:
        download_path = f"/tmp/{os.path.basename(random_file)}"
        s3.download_file(bucket_name, random_file, download_path)
        media = api.media_upload(download_path)
        client.create_tweet(text=question, media_ids=[media.media_id])
        return f"tweeted image with question {question}"
    except Exception as e:
        print(e)
