import random
import boto3
import tweepy
import os
import json

# X credentials stored in env variables
API_KEY = os.environ["API_KEY"]
API_SECRET_KEY = os.environ["API_SECRET_KEY"]
ACCESS_TOKEN = os.environ["ACCESS_TOKEN"]
ACCESS_TOKEN_SECRET = os.environ["ACCESS_TOKEN_SECRET"]
BEARER_TOKEN = os.environ["BEARER_TOKEN"]

auth = tweepy.OAuth1UserHandler(API_KEY, API_SECRET_KEY, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

client = tweepy.Client(
    bearer_token=BEARER_TOKEN,
    consumer_key=API_KEY,
    consumer_secret=API_SECRET_KEY,
    access_token=ACCESS_TOKEN,
    access_token_secret=ACCESS_TOKEN_SECRET
)


def BB_question(event, context):
    questions = {
        1: "Breaking Bad or Better Call Saul?",
        2: "Walter White or Jimmy McGill? Who has the more compelling transformation?",
        3: "What are your thoughts on Walter White's descent into Heisenberg?",
        4: "How do you interpret Jesse Pinkman’s struggle throughout Breaking Bad?",
        5: "What do you think makes Saul Goodman such an intriguing character?",
        6: "How does Kim Wexler’s journey in Better Call Saul resonate with you?",
        7: "Which moment in Breaking Bad shocked you the most and why?",
        8: "What are your opinions on the ethical dilemmas faced by the characters?",
        9: "How does the visual style of Breaking Bad enhance its storytelling?",
        10: "What motivates Gus Fring’s cold, calculated nature?",
        11: "Which decision made by a Breaking Bad character do you find the most controversial?",
        12: "How would you describe the relationship between Walter White and Jesse Pinkman?",
        13: "What do you think about Mike Ehrmantraut’s role in the criminal underworld?",
        14: "How is law enforcement portrayed in both Breaking Bad and Better Call Saul?",
        15: "At what point do you think Jimmy McGill truly begins his transformation into Saul Goodman?",
        16: "How do you feel about the dual nature of Jimmy McGill’s character?",
        17: "What role does humor play in balancing the darker themes of Better Call Saul?",
        18: "Which character in Better Call Saul do you believe faced the most tragic fate?",
        19: "How do you interpret the complex relationship between Chuck and Jimmy McGill?",
        20: "What are your thoughts on the moral gray areas explored in these shows?",
        21: "How does Breaking Bad tackle the subject of addiction and its impact on characters?",
        22: "Which episode of Better Call Saul left a lasting impression on you?",
        23: "What do you think about the narrative structure of Breaking Bad?",
        24: "How is the influence of the cartel developed throughout Breaking Bad?",
        25: "What distinguishes Better Call Saul from other legal dramas, in your view?",
        26: "How do family dynamics influence Walter White's decisions?",
        27: "What are your thoughts on supporting characters becoming central figures in these stories?",
        28: "How is legal ethics portrayed in Better Call Saul?",
        29: "What do you think about the pacing and structure of Breaking Bad’s storyline?",
        30: "Which subplot in Better Call Saul do you find most compelling?",
        31: "How are ambition and its consequences depicted in both series?",
        32: "Which character undergoes the most significant transformation, and why?",
        33: "How is foreshadowing used to build tension in Breaking Bad?",
        34: "What is the significance of silence in some key scenes of these shows?",
        35: "How do these series comment on the American Dream?",
        36: "In what ways do fate and free will conflict in the characters’ journeys?",
        37: "What are your opinions on how power dynamics are explored?",
        38: "How do you view Hank Schrader’s moral choices in Breaking Bad?",
        39: "What commentary do the shows offer on capitalism and greed?",
        40: "How does the legal system's portrayal in Better Call Saul shape your perception of justice?",
        41: "What do you think about the subtle hints dropped about future events?",
        42: "Which Breaking Bad villain fascinates you the most and why?",
        43: "How is desperation portrayed as a driving force for survival in the series?",
        44: "What are your thoughts on the tragic consequences stemming from the characters' choices?",
        45: "How does dark humor balance with drama in Better Call Saul?",
        46: "What role do visual motifs play in conveying themes in Breaking Bad?",
        47: "How do these shows explore the idea of personal identity?",
        48: "Which episode do you consider a turning point in Breaking Bad’s narrative?",
        49: "How does Jimmy McGill's legal career evolution affect your view of his character?",
        50: "What legacy do you think Breaking Bad and Better Call Saul leave for modern TV storytelling?",
        51: "What are your thoughts on the portrayal of loyalty in the series?",
        52: "How does the evolution of Walter White's character challenge traditional hero narratives?",
        53: "What impact does the setting (Albuquerque) have on the overall tone of Breaking Bad?",
        54: "How do you interpret the symbolism behind Walter's blue meth?",
        55: "In what ways does Better Call Saul explore the concept of redemption?",
        56: "How do the legal challenges faced by Jimmy McGill mirror his personal struggles?",
        57: "What role does family play in shaping the characters’ decisions in these series?",
        58: "How does Breaking Bad critique the healthcare system and its effects on the characters?",
        59: "What do you think about the transformation of Jesse Pinkman over the course of the series?",
        60: "How is trust built and broken among characters in Better Call Saul?",
        61: "What are your impressions of the relationship between Saul Goodman and his clients?",
        62: "How do you view the evolution of the drug trade as depicted in Breaking Bad?",
        63: "What significance do you find in the recurring themes of consequence and regret?",
        64: "How do moments of humor serve as relief in the midst of tension in these shows?",
        65: "What are your thoughts on the portrayal of moral ambiguity in the character arcs?",
        66: "How does Better Call Saul incorporate elements of tragedy into its narrative?",
        67: "What do you think drives the decisions of Mike Ehrmantraut beyond mere survival?",
        68: "How do the series use flashbacks to deepen the backstories of key characters?",
        69: "What role does fate play in the downfall of characters in Breaking Bad?",
        70: "How does the cinematography contribute to the mood and themes in Better Call Saul?",
        71: "What lessons do you think the characters learn about power and corruption?",
        72: "How do the shows address the theme of ambition, both personal and professional?",
        73: "What are your thoughts on the evolution of law enforcement characters in Breaking Bad?",
        74: "How do you feel the series handle the intersection of personal and professional lives?",
        75: "What role does mentorship play in shaping the destinies of characters in these shows?",
        76: "How do the series portray the cost of living a double life?",
        77: "What are your thoughts on the recurring motif of time and its impact on the characters?",
        78: "How does the dynamic between criminals and the law create tension in Breaking Bad?",
        79: "What narrative techniques do you appreciate in Better Call Saul's storytelling?",
        80: "How do the series explore the concept of identity through their characters’ transformations?",
        81: "What are your interpretations of the complex relationship between law and morality?",
        82: "How does the series use secondary characters to highlight the main themes?",
        83: "What impact do you think the series have had on the portrayal of antiheroes in television?",
        84: "How do the characters’ past experiences influence their present decisions?",
        85: "What are your thoughts on the evolution of the character arcs in both series?",
        86: "How does the use of color symbolism enhance the narrative in Breaking Bad?",
        87: "What parallels do you see between the legal battles in Better Call Saul and larger societal issues?",
        88: "How do the shows use moments of vulnerability to develop character depth?",
        89: "What role does deception play in the downfall of key characters?",
        90: "How does the evolving power structure in the drug trade affect the storyline of Breaking Bad?",
        91: "What are your thoughts on the portrayal of second chances in Better Call Saul?",
        92: "How do you interpret the recurring theme of sacrifice in the characters' journeys?",
        93: "What are your opinions on the portrayal of ambition as a double-edged sword?",
        94: "How do the series balance moments of intense drama with lighter, humanizing elements?",
        95: "What do you think the characters' journeys say about the cost of personal ambition?",
        96: "How does Better Call Saul challenge traditional narratives of legal success?",
        97: "What are your thoughts on the series' commentary on the American justice system?",
        98: "How do the shows incorporate real-world issues into their fictional narratives?",
        99: "What impact do you think the series have on modern television storytelling?",
        100: "How do Breaking Bad and Better Call Saul redefine the concept of a tragic hero?",
        101: "Walter White or Saul Goodman?",
        102: "Jesse Pinkman or Kim Wexler?",
        103: "Breaking Bad or Better Call Saul?",
        104: "What's your favorite episode of Breaking Bad?",
        105: "What's your favorite episode of Better Call Saul?",
        106: "Who's your favorite Breaking Bad character and why?",
        107: "Who's your favorite Better Call Saul character and why?",
        108: "What are your thoughts on Walter White's transformation throughout Breaking Bad?",
        109: "What are your thoughts on Jimmy McGill's transformation into Saul Goodman?",
        110: "What are your opinions on Gus Fring as a villain?",
        111: "What are your thoughts on Mike Ehrmantraut's moral code?",
        112: "What are your opinions on the relationship between Jimmy McGill and Kim Wexler?",
        113: "What are your thoughts on the ending of Breaking Bad?",
        114: "What are your thoughts on the ending of Better Call Saul?",
        115: "What are your opinions on the Salamanca family?",
        116: "What are your thoughts on Hector Salamanca's character?",
        117: "What are your opinions on Lalo Salamanca?",
        118: "What are your thoughts on Nacho Varga's arc in Better Call Saul?",
        119: "What are your opinions on Hank Schrader as a DEA agent?",
        120: "What are your thoughts on Skyler White's role in Breaking Bad?",
        121: "What are your opinions on the relationship between Walter White and Jesse Pinkman?",
        122: "What are your thoughts on the role of morality in Breaking Bad?",
        123: "What are your thoughts on the role of morality in Better Call Saul?",
        124: "What are your opinions on the cinematography in Breaking Bad?",
        125: "What are your opinions on the cinematography in Better Call Saul?",
        126: "What are your thoughts on the use of color symbolism in Breaking Bad?",
        127: "What are your thoughts on the use of color symbolism in Better Call Saul?",
        128: "What are your opinions on the character of Tuco Salamanca?",
        129: "What are your thoughts on the character of Todd Alquist?",
        130: "What are your opinions on the character of Lydia Rodarte-Quayle?",
        131: "What are your thoughts on the character of Howard Hamlin?",
        132: "What are your opinions on the character of Chuck McGill?",
        133: "What are your thoughts on the character of Saul Goodman in Breaking Bad?",
        134: "What are your opinions on the character of Saul Goodman in Better Call Saul?",
        135: "What are your thoughts on the character of Gene Takavic?",
        136: "What are your opinions on the character of Francesca Liddy?",
        137: "What are your thoughts on the character of Huell Babineaux?",
        138: "What are your opinions on the character of Krazy-8?",
        139: "What are your thoughts on the character of Jane Margolis?",
        140: "What are your opinions on the character of Gale Boetticher?",
        141: "What are your thoughts on the character of Don Eladio?",
        142: "What are your opinions on the character of Victor?",
        143: "What are your thoughts on the character of Tyrus Kitt?",
        144: "What are your opinions on the character of Skinny Pete?",
        145: "What are your thoughts on the character of Badger?",
        146: "What are your opinions on the character of Combo?",
        147: "What are your thoughts on the character of Wendy?",
        148: "What are your opinions on the character of Saul Goodman's commercials?",
        149: "What are your thoughts on the character of Saul Goodman's office?",
        150: "What are your opinions on the character of Saul Goodman's inflatable Statue of Liberty?",
        151: "What are your thoughts on the opening scenes of Breaking Bad and Better Call Saul?",
        152: "What are your opinions on the relationship between Mike Ehrmantraut and his granddaughter Kaylee?",
        153: "What is the significance of Walter White’s 'I am the one who knocks' declaration in redefining his character?",
        154: "How does Jesse Pinkman’s journey from a small-time cook to a tortured soul explore themes of guilt and redemption?",
        155: "In 'Ozymandias', how do Walt’s actions catalyze his downfall and what do they reveal about his hubris?",
        156: "How does Gus Fring’s meticulous control of his business mirror the duality of order and chaos in the show?",
        157: "What role does color symbolism—such as Walter’s wardrobe—play in charting his transformation?",
        158: "How does Hank Schrader’s pursuit of justice add tension and moral complexity to Breaking Bad?",
        159: "How does the scene where Walt recites Walt Whitman contribute to the theme of legacy in Breaking Bad?",
        160: "In what ways does Albuquerque itself enhance the gritty atmosphere of Breaking Bad?",
        161: "How do settings like the meth lab and the car wash serve as visual metaphors for Walt’s double life?",
        162: "How does the 'Pilot' episode establish the series’ core themes of desperation and transformation?",
        163: "What narrative purpose does Saul Goodman serve in Breaking Bad, especially as his character foreshadows future events?",
        164: "How does Breaking Bad use cinematography and framing to intensify tension during critical moments?",
        165: "In what ways does Mike Ehrmantraut’s quiet moral code complicate the world of criminality in the series?",
        166: "How does the plane crash in Season 2 symbolize the far-reaching consequences of Walt’s decisions?",
        167: "What is the importance of recurring imagery such as watches and time in illustrating the characters’ fates?",
        168: "How does the final season recast Walter White as a tragic antihero through his irreversible choices?",
        169: "What impact do minor characters have in reflecting the fallout of Walt’s actions throughout Breaking Bad?",
        170: "How does the show explore the duality of Walter White’s identity as both family man and criminal mastermind?",
        171: "What makes the episode 'Fly' a turning point for Walt’s internal struggle and self-awareness?",
        172: "How does Breaking Bad’s portrayal of the drug trade comment on larger issues within American society?",
        173: "What techniques does the series use to build suspense during cartel operations and violent confrontations?",
        174: "How is betrayal depicted in the shifting alliances between Walt, Jesse, and their associates?",
        175: "What does Walt’s moral decline say about the corrupting influence of unchecked ambition?",
        176: "How do flashbacks enrich our understanding of Jesse’s background and his gradual loss of innocence?",
        177: "How does the use of silence in key scenes amplify the emotional weight of Breaking Bad’s narrative?",
        178: "In what ways does Breaking Bad blend dark humor with tragedy to underscore its thematic depth?",
        179: "How does the use of classical music in dramatic scenes enhance the emotional impact of Breaking Bad?",
        180: "How do Walt’s personal losses propel his evolution from a meek teacher to a ruthless drug lord?",
        181: "How does Breaking Bad challenge conventional hero narratives through its portrayal of moral ambiguity?",
        182: "What role does Skyler White play in highlighting the personal costs of Walt’s secret life?",
        183: "How does the motif of masks and hidden identities underscore the themes of deception in Breaking Bad?",
        184: "How do Walt’s extended monologues reveal the internal conflicts driving his transformation?",
        185: "What narrative function does Todd Alquist serve in illustrating the escalating brutality of the criminal world?",
        186: "How is the tension between fate and free will explored through Walt’s critical decisions?",
        187: "How do the desert landscapes serve as visual metaphors for the isolation and moral decay of the characters?",
        188: "What role does the science of chemistry play as both a literal and metaphorical element in Breaking Bad?",
        189: "How do emotionally charged scenes—like the bathtub confession—capture the series’ weighty themes?",
        190: "What moral implications arise from Walt’s justifications for his increasingly dangerous actions?",
        191: "How does Marie Schrader’s character add nuance to the familial and ethical conflicts in the series?",
        192: "What does Walt’s gradual transformation reveal about the nature of ambition in Breaking Bad?",
        193: "How does Walt’s struggle to maintain a double life drive the central conflicts in Breaking Bad?",
        194: "What is the narrative importance of Walt’s cancer diagnosis as a catalyst for his choices?",
        195: "How are themes of family loyalty versus personal ambition explored through the White family dynamics?",
        196: "Why is the 'Box Cutter' episode pivotal in redefining the show's exploration of violence and power?",
        197: "How do background characters, such as lab technicians, contribute to the authentic feel of Breaking Bad’s criminal world?",
        198: "How is the theme of betrayal woven throughout the series, particularly in Walt’s closest relationships?",
        199: "How does Jesse Pinkman’s arc serve as a counterbalance to Walt’s descent into darkness?",
        200: "In what ways does Breaking Bad critique the American healthcare system through Walt’s initial motivations?",
        201: "How does the recurring motif of the car wash symbolize Walt’s struggle with his public versus private identity?",
        202: "How does Gustavo Fring’s character exemplify the intersection of business acumen and criminal ruthlessness?",
        203: "What is the effect of juxtaposing high-stakes action with introspective moments in Breaking Bad?",
        204: "How does the meth lab setting function as a metaphor for the moral decay at the heart of Breaking Bad?",
        205: "What does the scene where Walt burns money reveal about his internal conflict and shifting priorities?",
        206: "How does Breaking Bad portray the inevitability of consequences for those involved in the drug trade?",
        207: "What is the significance of recurring visuals, like broken glass, in symbolizing shattered lives in Breaking Bad?",
        208: "How does Breaking Bad use Walt’s transformation to critique the notion of the American dream?",
        209: "How does the tension in 'To’hajiilee' highlight the conflict between loyalty and betrayal in the series?",
        210: "What role does Jesse’s existential crisis play in reflecting the larger moral dilemmas of Breaking Bad?",
        211: "How does Hector Salamanca embody the dangers of unchecked pride and the consequences of vendettas?",
        212: "What does the imagery of flies and infestations suggest about the spreading corruption in Breaking Bad?",
        213: "How does the pink teddy bear function as a symbol of the unforeseen collateral damage of Walt’s actions?",
        214: "In what ways is Walter White’s pride portrayed as his ultimate undoing in Breaking Bad?",
        215: "How does Saul Goodman’s arc integrate into the Breaking Bad universe to illuminate its darker themes?",
        216: "How does the interplay of light and shadow enhance the moral ambiguities depicted in Breaking Bad?",
        217: "What impact does Walt’s transformation have on the dynamics within his family?",
        218: "How does 'Granite State' encapsulate the irreversible decline of Walter White’s character?",
        219: "How are dreams and hallucinations used to portray Jesse’s internal torment in Breaking Bad?",
        220: "In what ways does Breaking Bad depict the slow erosion of Walt’s ethical boundaries?",
        221: "How does Lydia Rodarte-Quayle intensify themes of paranoia and obsessive control in the series?",
        222: "What does Breaking Bad reveal about the personal costs of leading a double life?",
        223: "How do the final scenes of Breaking Bad serve as a commentary on redemption and retribution?",
        224: "How is community and individual identity affected by the pervasive violence in Breaking Bad?",
        225: "How do Walt’s ambitions collide with his humanity throughout the series?",
        226: "How does the breakdown of trust among criminal allies propel the narrative of Breaking Bad?",
        227: "What does the episode 'Phoenix' reveal about the personal sacrifices demanded by a criminal lifestyle?",
        228: "How do flashbacks in Breaking Bad provide deeper insight into Walt’s internal struggles?",
        229: "What narrative effect is achieved through the gradual escalation of tension in key Breaking Bad episodes?",
        230: "How does Breaking Bad portray the disintegration of moral values within the drug trade?",
        231: "How is the duality of Walter White’s persona explored through his conflicting roles at home and in crime?",
        232: "How do climactic confrontations in the desert encapsulate the series’ central conflicts?",
        233: "What does Jesse’s enduring guilt suggest about the show’s commentary on the cost of a life of crime?",
        234: "How does Breaking Bad use pointed dialogue to expose the inner conflicts of its characters?",
        235: "What does Walt’s complete transformation into Heisenberg suggest about the corrupting nature of power?",
        236: "How does Jesse’s development throughout the series serve as a foil to Walt’s descent?",
        237: "How do minor visual details enrich the storytelling and underscore themes in Breaking Bad?",
        238: "In what ways does Breaking Bad explore fate versus destiny through Walter’s life choices?",
        239: "How is the moral complexity of characters like Mike Ehrmantraut used to challenge traditional heroism?",
        240: "What do critical moments under extreme pressure reveal about the true nature of the characters in Breaking Bad?",
        241: "How does the scene where Walt confronts his own mortality drive home the series’ existential themes?",
        242: "How do the personal losses of characters reflect the overarching themes of ambition and regret in Breaking Bad?",
        243: "What narrative role does the collapse of Walt’s family serve in highlighting the costs of his criminal life?",
        244: "How does Breaking Bad illustrate the corrosive effects of power and corruption within its criminal enterprises?",
        245: "How do stark visual contrasts, such as dark versus light imagery, enhance the thematic tension in Breaking Bad?",
        246: "What does Breaking Bad suggest about the struggle for dominance in the criminal underworld through its key figures?",
        247: "How is isolation used as a recurring motif to underscore the internal emptiness of Breaking Bad’s characters?",
        248: "What does the psychological toll of a criminal lifestyle look like through the eyes of characters like Walt and Jesse?",
        249: "How does Walt’s final transformation complete his tragic arc and redefine his legacy in Breaking Bad?",
        250: "How do the final episodes of Breaking Bad encapsulate the clash between personal ambition and moral responsibility?",
    }


    # s3 bucket files look up
    lookup = {
        1: "None",
        2: "None",
        3: "None",
        4: "None",
        5: "None",
        6: "None",
        7: "None",
        8: "None",
        9: "None",
        10: "None",
        11: "None",
        12: "None",
        13: "None",
        14: "None",
        15: "None",
        16: "None",
        17: "None",
        18: "None",
        19: "None",
        20: "None",
        21: "None",
        22: "None",
        23: "None",
        24: "None",
        25: "None",
        26: "None",
        27: "None",
        28: "None",
        29: "None",
        30: "None",
        31: "None",
        32: "None",
        33: "None",
        34: "None",
        35: "None",
        36: "None",
        37: "None",
        38: "None",
        39: "None",
        40: "None",
        41: "None",
        42: "None",
        43: "None",
        44: "None",
        45: "None",
        46: "None",
        47: "None",
        48: "None",
        49: "None",
        50: "None",
        51: "None",
        52: "None",
        53: "None",
        54: "None",
        55: "None",
        56: "None",
        57: "None",
        58: "None",
        59: "None",
        60: "None",
        61: "None",
        62: "None",
        63: "None",
        64: "None",
        65: "None",
        66: "None",
        67: "None",
        68: "None",
        69: "None",
        70: "None",
        71: "None",
        72: "None",
        73: "None",
        74: "None",
        75: "None",
        76: "None",
        77: "None",
        78: "None",
        79: "None",
        80: "None",
        81: "None",
        82: "None",
        83: "None",
        84: "None",
        85: "None",
        86: "None",
        87: "None",
        88: "None",
        89: "None",  # "questions/char_Yoda(puppet)/", #yoda puppet
        90: "None",
        91: "None",
        92: "None",
        93: "None",
        94: "None",
        95: "None",
        96: "None",
        97: "None",
        98: "None",
        99: "None",
        100: "None",
        101: "None",
        102: "None",
        103: "None",
        104: "None",
        105: "None",
        106: "None",
        107: "None",
        108: "None",
        109: "None",
        110: "None",
        111: "None",
        112: "None",
        113: "None",
        114: "None",
        115: "None",
        116: "None",
        117: "None",
        118: "None",
        119: "None",
        120: "None",
        121: "None",
        122: "None",
        123: "None",
        124: "None",
        125: "None",
        126: "None",
        127: "None",
        128: "None",
        129: "None",
        130: "None",
        131: "None",
        132: "None",
        133: "None",
        134: "None",
        135: "None",
        136: "None",
        137: "None",
        138: "None",
        139: "None",
        140: "None",
        141: "None",
        142: "None",
        143: "None",
        144: "None",
        145: "None",
        146: "None",
        147: "None",
        148: "None",
        149: "None",
        150: "None",
        151: "None",
        152: "None",
        153: "None",
        154: "None",
        155: "None",
        156: "None",
        157: "None",
        158: "None",
        159: "None",
        160: "None",
        161: "None",
        162: "None",
        163: "None",
        164: "None",
        165: "None",
        166: "None",
        167: "None",
        168: "None",
        169: "None",
        170: "None",
        171: "None",
        172: "None",
        173: "None",
        174: "None",
        175: "None",
        176: "None",
        177: "None",
        178: "None",
        179: "None",
        180: "None",
        181: "None",
        182: "None",
        183: "None",
        184: "None",
        185: "None",
        186: "None",
        187: "None",
        188: "None",
        189: "None",
        190: "None",
        191: "None",
        192: "None",
        193: "None",
        194: "None",
        195: "None",
        196: "None",
        197: "None",
        198: "None",
        199: "None",
        200: "None",
        201: "None",
        202: "None",
        203: "None",
        204: "None",
        205: "None",
        206: "None",
        207: "None",
        208: "None",
        209: "None",
        210: "None",
        211: "None",
        212: "None",
        213: "None",
        214: "None",
        215: "None",  # "questions/char_JudeLaw/",
        216: "None",  # "questions/char_Omega/",
        217: "None",  # "questions/char_Crosshair/",
        218: "None",  # "questions/char_Hunter/",
        219: "None",  # "questions/char_Tech/",
        220: "None",  # "questions/char_Wrecker/",
        221: "None",  # "questions/char_Echo/",
        222: "None",
        223: "None",
        224: "None",
        225: "None",
        226: "None",  # "questions/char_Leia(Kenobi-show)/",
        227: "None",  # "questions/char_Obi-Wan(Kenobi-Show)/",
        228: "None",  # "questions/char_Vader(Kenobi-show)/",
        229: "None",  # "questions/char_OwenBeruLars(Kenobi-show)/",
        230: "None",
        231: "None",  # "questions/char_SenatorOrgana(Kenobi-Show)/",
        232: "None",  # "questions/char_Kumail(Kenobi-Show)/",
        233: "None"  # "questions/char_DarthJarJar/"
    }

    bucket_name = 'starwars.photos'
    file_key = 'notes/SW_questions.txt'
    s3 = boto3.client('s3')

    try:
        # Fetch the current file from S3
        response = s3.get_object(Bucket=bucket_name, Key=file_key)
        file_content = response['Body'].read().decode('utf-8')

        # Convert the file content (string) into a Python list
        question_indices = json.loads(file_content)
        print(question_indices)

        index = random.randint(1, len(questions))

        # try again until we get new item not in list
        while index in question_indices:
            index = random.randint(1, len(questions))

        path = lookup[index]

        question_indices.insert(0, index)
        if len(question_indices) > 100:
            question_indices.pop()  # Remove the last element

        updated_content = json.dumps(question_indices)

        s3.put_object(Bucket=bucket_name, Key=file_key, Body=updated_content)
        question = questions[index]

        if path == "None":  # upload just text, no image
            client.create_tweet(text=question)
            return f"POSTED TWEET {question} with no image"

        response = s3.list_objects_v2(Bucket=bucket_name, Prefix=path)
        if 'Contents' not in response:
            return {
                'statusCode': 404,
                'body': 'No files found in the specified directory.'
            }
        # Extract file keys (paths) from the response
        file_keys = [obj['Key'] for obj in response['Contents'] if obj['Key'] != path]
        # Check if there are files to choose from
        if not file_keys:
            return {
                'statusCode': 404,
                'body': 'No files found in the specified directory.'
            }

        # Pick a random file from the list
        random_file = random.choice(file_keys)

        # these 4 are for image, not implemented yet:
        download_path = f"/tmp/{os.path.basename(random_file)}"
        s3.download_file(bucket_name, random_file, download_path)
        media = api.media_upload(download_path)
        client.create_tweet(text=question, media_ids=[media.media_id])
        return f"tweeted image with question {question}"
    except Exception as e:
        print(e)

        #test

