import random
import tweepy
import os
from datetime import datetime

# Twitter API authentication setup
API_KEY = 'iUKkGWeeWWgb7VQHWj44mROSV'
API_SECRET_KEY = 'TjVMwO0NrDjT8aIFQttg4xy5NlzHIs4Askx2Eu5mAVEMv5l4x7'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAN9VxwEAAAAALxyzkCe3PuUNDZxlMJ8E3MUYnLU%3DbJDU9CWl88fyQi6C5K0GWd7cOxekRCEBpGYh7yOYQBfY3PyF7R'
ACCESS_TOKEN = '1831488681640857600-7OjuKVNuY5IsFLZJ1lNE4QW1tHWDGv'
ACCESS_TOKEN_SECRET = 'KpEzU8IarTH4HrifXzpuzHRHGsMgtGXI81x6IdhSAbslZ'
client_id = 'd3JHWnRNbUY2V2p0VjdaZXgzQ0g6MTpjaQ'
client_secret = 'gmTsDtmh1Xcvfmxe8FeIVlTLcQ-x9CAF9FD8qrx2bKWvbmRrG8'

client = tweepy.Client(bearer_token=BEARER_TOKEN,
                       consumer_key=API_KEY, consumer_secret=API_SECRET_KEY,
                       access_token=ACCESS_TOKEN, access_token_secret=ACCESS_TOKEN_SECRET)


def bom_daily_verse(event, context):
    today = datetime.today()
    day_num = today.timetuple().tm_yday
    print(day_num)
    print(today)

    daily_verse = {
        1: "But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God. -Matthew 4:4",
        2: "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you -Matthew 5:44",
        3: "Be ye therefore perfect, even as your Father which is in heaven is perfect. -Matthew 5:48",
        4: "Therefore whosoever heareth these sayings of mine, and doeth them, I will liken him unto a wise man, which built his house upon a rock. -Matthew 7:24",
        5: "Blessed are the peacemakers: for they shall be called the children of God. -Matthew 5:9",
        6: "And Jesus, when he was baptized, went up straightway out of the water: and, lo, the heavens were opened unto him, and he saw the Spirit of God descending like a dove, and lighting upon him. -Matthew 3:16",
        7: "And every one that heareth these sayings of mine, and doeth them not, shall be likened unto a foolish man, which built his house upon the sand. -Matthew 7:26",
        8: "Blessed are the pure in heart: for they shall see God. -Matthew 5:8",
        9: "For what is a man profited, if he shall gain the whole world, and lose his own soul? or what shall a man give in exchange for his soul? -Matthew 16:26",
        10: "Whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart. -Matthew 5:28",
        11: "Blessed are the meek: for they shall inherit the earth. -Matthew 5:5",
        12: "And said, Verily I say unto you, Except ye be converted, and become as little children, ye shall not enter into the kingdom of heaven. -Matthew 18:3",
        13: "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost -Matthew 28:19",
        14: "Come unto me, all ye that labour and are heavy laden, and I will give you rest. -Matthew 11:28",
        15: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you. -Matthew 6:33",
        16: "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. -Matthew 22:37",
        17: "Not every one that saith unto me, Lord, Lord, shall enter into the kingdom of heaven; but he that doeth the will of my Father which is in heaven. -Matthew 7:21",
        18: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you. -Matthew 7:7",
        19: "Lay not up for yourselves treasures upon earth, where moth and rust doth corrupt, and where thieves break through and steal. -Matthew 6:19",
        20: "For every one that asketh receiveth; and he that seeketh findeth; and to him that knocketh it shall be opened. -Matthew 7:8",
        21: "Beware of false prophets, which come to you in sheep's clothing, but inwardly they are ravening wolves. -Matthew 7:15",
        22: "Therefore I say unto you, Take no thought for your life, what ye shall eat, or what ye shall drink; nor yet for your body, what ye shall put on. Is not the life more than meat, and the body than raiment? -Matthew 6:25",
        23: "And she shall bring forth a son, and thou shalt call his name JESUS: for he shall save his people from their sins. -Matthew 1:21",
        24: "No man can serve two masters: for either he will hate the one, and love the other; or else he will hold to the one, and despise the other. Ye cannot serve God and mammon. -Matthew 6:24",
        25: "Take heed that ye do not your alms before men, to be seen of them: otherwise ye have no reward of your Father which is in heaven. -Matthew 6:1",
        26: "For where two or three are gathered together in my name, there am I in the midst of them. -Matthew 18:20",
    }
    # 16: "After ye have received the Holy Ghost ye can speak with the tongue of angels. -2 Nephi 32:2",
    # 17: "He inviteth them all to come unto him and partake of his goodness. -2 Nephi 26:33",
    # 18: "In the strength of the Lord thou canst do all things which are expedient unto him. -Moroni 7:33",
    # 19: "Awake, my sons; put on the armor of righteousness. -2 Nephi 1:23",
    # 20: "If ye have faith ye can do all things which are expedient unto me. -Moroni 10:23",
    # 21: "If ye would hearken unto the Spirit which teacheth a man to pray, ye would know that ye must pray. -2 Nephi 32:8",
    # 22: "There is no other name given whereby salvation cometh; therefore, take upon you the name of Christ. -Mosiah 5:8",
    # 23: "They never did look upon death with any degree of terror, for their hope was in Christ and the resurrection. -Alma 27:28",
    # 24: "I know that I am nothing; therefore I will not boast of myself, but I will boast of my God. -Alma 26:12",
    # 25: "Remember, remember that there is no other way nor means whereby man can be saved, only through Christ. -Helaman 5:9",
    # 26: "For behold, I have refined thee, I have chosen thee in the furnace of affliction. -1 Nephi 20:10",
    # 27: "We labor diligently to write, to persuade our children and brethren to believe in Christ. -2 Nephi 25:23",
    # 28: "Whosoever shall put their trust in God shall be supported in their trials, troubles, and afflictions. -Alma 36:3",
    # 29: "Counsel with the Lord in all thy doings, and he will direct thee for good. -Alma 37:37",
    # 30: "I know that God loveth his children; nevertheless, I do not know the meaning of all things. -1 Nephi 11:17",
    # 31: "If this be the desire of your hearts, what have you against being baptized in the name of the Lord? -Mosiah 18:10",
    # 32: "Adam fell that men might be; and men are, that they might have joy. -2 Nephi 2:25",
    # 33: "Wherefore, ye must press forward with a steadfastness in Christ, having a perfect brightness of hope, and a love of God and of all men. -2 Nephi 31:20",
    # 34: "Yea, and are willing to mourn with those that mourn; yea, and comfort those that stand in need of comfort. -Mosiah 18:9",
    # 35: "And now, my sons, remember, remember that it is upon the rock of our Redeemer, who is Christ, the Son of God, that ye must build your foundation. -Helaman 5:12",
    # 36: "This life is the time for men to prepare to meet God. -Alma 34:32",
    # 37: "We talk of Christ, we rejoice in Christ, we preach of Christ. -2 Nephi 25:26",
    # 38: "The natural man is an enemy to God. -Mosiah 3:19",
    # 39: "Wickedness never was happiness. -Alma 41:10",
    # 40: "Press forward with a steadfastness in Christ. -2 Nephi 31:20",
    # 41: "Ye receive no witness until after the trial of your faith. -Ether 12:6",
    # 42: "Know ye not that ye are in the hands of God? -Mormon 5:23",
    # 43: "By small and simple things are great things brought to pass. -Alma 37:6",
    # 44: "When ye are in the service of your fellow beings ye are only in the service of your God. -Mosiah 2:17",
    # 45: "And moreover, I would desire that ye should consider on the blessed and happy state of those that keep the commandments of God. For behold, they are blessed in all things, both temporal and spiritual. -Mosiah 2:41",
    # 46: "And now, my beloved brethren, I would that ye should come unto Christ, who is the Holy One of Israel, and partake of his salvation, and the power of his redemption. -2 Nephi 31:13",
    # 47: "Men are free according to the flesh; they can choose liberty and eternal life, or captivity and death. -2 Nephi 2:27",
    # 48: "My soul delighteth in the scriptures, and my heart pondereth them. -2 Nephi 4:15",
    # 49: "If ye believe all these things see that ye do them. -Mosiah 4:10",
    # 50: "Believe in God; believe that he is, and that he created all things, both in heaven and in earth. -Mosiah 4:9",
    # 51: "Have ye spiritually been born of God? -Alma 5:14",
    # 52: "If ye have felt to sing the song of redeeming love, I would ask, can ye feel so now? -Alma 5:26",
    # 53: "Faith is not to have a perfect knowledge of things; ye hope for things which are not seen. -Alma 32:21",
    # 54: "Learn wisdom in thy youth; learn in thy youth to keep the commandments of God. -Alma 37:35",
    # 55: "He shall go forth, suffering pains and afflictions of every kind. -Alma 7:11",
    # 56: "Pray in your families, always in my name, that your wives and your children may be blessed. -3 Nephi 18:21",
    # 57: "If men come unto me I will show unto them their weakness, that they may be humble. -Ether 12:27",
    # 58: "The Spirit of Christ is given to every man, that he may know good from evil. -Moroni 7:16",
    # 59: "When ye shall receive these things, I would exhort you to ask God if they are not true. -Moroni 10:4",
    # 60: "He suffereth the pains of all men, that they might repent and come unto him. -2 Nephi 9:21",
    # 61: "It must needs be, that there is an opposition in all things. -2 Nephi 2:11",
    # 62: "My God hath been my support; he hath led me through mine afflictions. -2 Nephi 4:20",
    # 63: "Before ye seek for riches, seek ye for the kingdom of God. -Jacob 2:18",
    # 64: "My soul hungered; I cried unto him in mighty prayer all the day long. -Enos 1:4",
    # 65: "If you do keep his commandments he doth bless you and prosper you. -Mosiah 2:22",
    # 66: "There is no other name given whereby salvation can come except in Christ. -Mosiah 3:17",
    # 67: "He will take upon him death, that he may loose the bands of death which bind his people. -Alma 7:12",
    # 68: "I know that which the Lord hath commanded me, and I glory in it. -Alma 29:9",
    # 69: "Nothing could be so bitter as my pains, nor so sweet as my joy. -Alma 36:21",
    # 70: "They did wax stronger in humility, firmer in faith, filling their souls with joy. -Helaman 3:35",
    # 71: "By the power of the Holy Ghost ye may know the truth of all things. -Moroni 10:5",
    # 72: "If ye will come unto me ye shall have eternal life; mine arm of mercy is extended. -3 Nephi 9:14",
    # 73: "I would that ye should be perfect even as I, or your Father who is in heaven is perfect. -3 Nephi 12:48",
    # 74: "There was no contention because of the love of God which did dwell in their hearts. -4 Nephi 1:15",
    # 75: "Repent, be baptized, and lay hold upon the gospel of Christ which shall be set before you. -Mormon 7:8",
    # 76: "God is the same yesterday, today, and forever; in him there is no change. -Mormon 9:9",
    # 77: "Whoso believeth in God might with surety hope for a better world. -Ether 12:4",
    # 78: "Pray unto the Father that ye may be filled with this love, which is bestowed upon true followers of Christ. -Moroni 7:48",
    # 79: "That which is of God inviteth and enticeth to do good continually. -Moroni 7:13",
    # 80: "The first fruits of repentance is baptism. -Moroni 8:25",
    # 81: "Whoso would hearken unto the word of God and hold fast unto it would never perish. -1 Nephi 15:24",
    # 82: "When they are learned they think they are wise, and they hearken not unto the counsel of God. -2 Nephi 9:28",
    # 83: "If ye shall believe in Christ ye will believe these words, for they are the words of Christ. -2 Nephi 33:10",
    # 84: "One being is as precious in his sight as the other. -Jacob 2:21",
    # 85: "Come unto him, and offer your whole souls as an offering unto him. -Omni 1:26",
    # 87: "If you will turn to the Lord with full purpose of heart, and put your trust in him, he will deliver you. -Mosiah 7:33",
    # 88: "I would that ye should be humble, be submissive and gentle, easy to be entreated. -Alma 7:23",
    # 89: "What shall I do that I may have this eternal life of which thou hast spoken? -Alma 22:15",
    # 90: "I ought to be content with the things which the Lord hath allotted unto me. -Alma 29:4",
    # 91: "Awake and arouse your faculties, even to an experiment upon my words. -Alma 32:27",
    # 92: "The way is prepared, and if we will look we may live forever. -Alma 37:44",
    # 93: "The Lord is merciful unto all who will, in the sincerity of their hearts, call upon his holy name. -Helaman 3:27",
    # 94: "If ye believe on his name ye will repent of all your sins, that ye may have remission of them. -Helaman 14:13",
    # 95: "Blessed are ye because of your faith. And now behold, my joy is full. -3 Nephi 17:20",
    # 96: "Behold, I am the light and the life of the world; come unto me and partake of my salvation. -3 Nephi 11:10",
    # 97: "Behold, I am Jesus Christ, whom the prophets testified shall come into the world. - 3 Nephi 11:10",
    # 98: "For behold, the time cometh that the Lord Omnipotent shall come down among the children of men. - Mosiah 3:5",
    # 99: "And he shall suffer temptations, pain of body, hunger, thirst, and fatigue. - Mosiah 3:8",
    # 100: "Redemption cometh in and through the Holy Messiah; for he is full of grace and truth. - 2 Nephi 2:6",
    # 101: "Behold, I would exhort you that when ye shall read these things, remember how merciful the Lord hath been unto you. - Moroni 10:3",
    # 102: "O, how delicious is your love, O God, that makes all things beautiful. - 2 Nephi 4:34",
    # 103: "Behold, the tender mercies of the Lord are over all those who exercise faith in him. - 1 Nephi 10:17",
    # 104: "And know ye that ye shall be judges of this people, according to the judgment which I shall give unto you. - 3 Nephi 27:27",
    # 105: "Men are free according to the flesh; and all things are given them which are expedient unto man. - 2 Nephi 2:7",
    # 106: "O ye my brethren, come, see the workmanship of God. - Mormon 9:11",
    # 107: "Arise and come forth unto me, that ye may thrust your hands into my side, and also that ye may feel the prints of the nails in my hands and in my feet, that ye may know that I am the God of Israel. - 3 Nephi 11:14",
    # 108: "And charity suffereth long, and is kind, and envieth not; charity vaunteth not itself, is not puffed up, seeketh not her own, is not easily provoked, thinketh no evil. - Moroni 7:45",
    # 109: "Blessed are the peacemakers: for they shall be called the children of God. - 3 Nephi 12:19",
    # 110: "Blessed are they that mourn: for they shall be comforted. - 3 Nephi 12:20",
    # 111: "Blessed are the meek: for they shall inherit the earth. - 3 Nephi 12:21",
    # 112: "Blessed are they which do hunger and thirst after righteousness: for they shall be filled. - 3 Nephi 12:22",
    # 113: "Blessed are the merciful: for they shall obtain mercy. - 3 Nephi 12:23",
    # 114: "Blessed are the pure in heart: for they shall see God. - 3 Nephi 12:24",
    # 115: "Blessed are they which are persecuted for righteousness' sake: for theirs is the kingdom of heaven. - 3 Nephi 12:25",
    # 116: "Let your light so shine before men, that they may see your good works and glorify your Father in heaven. - 3 Nephi 12:16",
    # 117: "Ye are the salt of the earth; but if the salt have lost its savor, wherewith shall it be salted? - 3 Nephi 12:15",
    # 118: "Judge not, that ye be not judged. - 3 Nephi 14:1",
    # 119: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you. - 3 Nephi 14:7",
    # 120: "Enter ye in at the strait gate: for wide is the gate, and broad is the way, that leadeth to destruction. - 3 Nephi 14:13",
    # 121: "Yea, come unto Christ, and be perfected in him, and deny yourselves of all ungodliness; and if ye shall deny yourselves of all ungodliness, ye shall be brought to stand before the presence of the Lord. - Moroni 10:32",
    # 122: "And as I partook of the fruit thereof it filled my soul with exceedingly great joy; and I knew that it was the love of God. - 1 Nephi 8:12",
    # 123: "And it came to pass that I did behold a tree, whose fruit was desirable to make one happy. - 1 Nephi 8:10",
    # 124: "And I, Nephi, saw that the things which my father had spoken were true; for I saw a vision of the Redeemer, and I knew that he was the Son of God. - 1 Nephi 11:21",
    # 125: "This is my commandment, that ye love one another. - 3 Nephi 11:12",
    # 126: "For if ye forgive men their trespasses, your heavenly Father will also forgive you. - 3 Nephi 13:14",
    # 127: "God is good",
    # 128: "Now, my son, I have told you this that ye may learn wisdom, that ye may learn of me that there is no other way or means whereby man can be saved, only in and through the atonement of Jesus Christ. -Alma 42:6",
    # 129: "Yea, cry unto God for all thy support; yea, let all thy doings be unto the Lord; and if ye do these things, ye shall be lifted up at the last day. -Alma 37:36",
    # 130: "Wherefore, whoso believeth in God might with surety hope for a better world, if he is faithful to the end, behold, even he shall receive eternal life. -Ether 12:4",
    # 131: "And what is it that ye shall hope for? Behold, I say unto you, that ye shall have hope through the atonement of Christ, and the power of His resurrection, to be raised unto eternal life. -Moroni 7:41",
    # 132: "O Lord, my God, have mercy on me, and hear my prayer, and remember thy servant, for thou hast been merciful unto me. -Enos 1:1",
    # 133: "Search diligently in the scriptures, that ye may learn wisdom and understand the mysteries of God. -Jacob 4:6",
    # 134: "And the records which have been kept by our fathers do witness of the power and mercy of God. -Omni 1:4",
    # 135: "And now, behold, I would speak unto you concerning the things which I have seen; for the Lord hath shown them unto me. -Mormon 7:6",
    # 136: "Yea, if ye will believe in God, ye shall have a hope for eternal life. -2 Nephi 1:20",
    # 137: "And the Spirit of the Lord did rest upon me, and I felt great joy in my soul. -1 Nephi 19:23",
    # 138: "O, how great the goodness of our God! How great the power of His love! -2 Nephi 4:35",
    # 139: "Behold, the Spirit of revelation is upon me, leading me to understand the mysteries of God. -1 Nephi 10:2",
    # 140: "Behold, I say unto you, that ye must exercise even a particle of faith, and miracles shall follow. -Alma 5:7",
    # 141: "And if ye do repent and come unto God, He will forgive your sins and cleanse you from all unrighteousness. -Mosiah 26:30",
    # 142: "I testify that Jesus Christ lives, and His gospel is the power of God unto salvation. -3 Nephi 11:15",
    # 143: "By the mercy of the Savior, our sins are forgiven, and we are made clean. -Moroni 8:26",
    # 144: "Remember, my beloved brethren, that your destiny is to be partakers of the divine nature. -2 Nephi 9:39",
    # 145: "For the words of the prophets are a guide unto righteousness. -Helaman 5:30",
    # 146: "And now, when ye have received this promise, ye are called the children of Christ. -Mosiah 5:2",
    # 147: "Let your faith be strong, and your hearts be humble, that you may overcome the trials of mortality. -2 Nephi 31:12"

    tweet_text = daily_verse[random.randint(1, len(daily_verse))] + " "
    print(tweet_text)

    client.create_tweet(text=tweet_text)
