import random
import boto3
import tweepy
import os
import json

# X credentials stored in env variables
API_KEY = os.environ["API_KEY"]
API_SECRET_KEY = os.environ["API_SECRET_KEY"]
ACCESS_TOKEN = os.environ["ACCESS_TOKEN"]
ACCESS_TOKEN_SECRET = os.environ["ACCESS_TOKEN_SECRET"]
BEARER_TOKEN = os.environ["BEARER_TOKEN"]

auth = tweepy.OAuth1UserHandler(API_KEY, API_SECRET_KEY, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

client = tweepy.Client(
    bearer_token=BEARER_TOKEN,
    consumer_key=API_KEY,
    consumer_secret=API_SECRET_KEY,
    access_token=ACCESS_TOKEN,
    access_token_secret=ACCESS_TOKEN_SECRET
)


def lotr_question(event, context):
    questions = {
        1: "What is the significance of the One Ring in shaping the fate of Middle-earth?",
        2: "How does Frodo Baggins’ journey reflect the theme of sacrifice throughout The Lord of the Rings?",
        3: "In what ways does Samwise Gamgee embody loyalty and hope during the quest to destroy the Ring?",
        4: "How does Gandalf’s transformation from the Grey to the White symbolize renewal and wisdom in LOTR?",
        5: "What does Aragorn’s journey from Strider to King reveal about destiny and leadership?",
        6: "How do Legolas and Gimli’s evolving friendship highlight the bridging of ancient rivalries in Middle-earth?",
        7: "What narrative purpose does Saruman’s fall serve in illustrating the corrupting nature of power?",
        8: "How is Sauron’s distant menace used to build tension and fear in The Lord of the Rings?",
        9: "In what ways does Gollum’s tragic arc explore themes of corruption and redemption?",
        10: "How do the varied landscapes—from the Shire to Mordor—mirror the internal struggles of Middle-earth’s inhabitants?",
        11: "How is the conflict between fate and free will portrayed in Frodo’s decision to carry the Ring?",
        12: "What does Rivendell symbolize in terms of sanctuary and ancient wisdom in LOTR?",
        13: "How does the journey through Moria serve as a turning point for the Fellowship?",
        14: "What role does the film’s score play in enhancing the epic storytelling of The Lord of the Rings?",
        15: "How does The Hobbit portray Bilbo Baggins’ evolution from a reluctant adventurer to a courageous hero?",
        16: "What themes are explored through Thorin Oakenshield’s quest for reclaiming the Lonely Mountain?",
        17: "How do the riddles in 'The Hobbit' illustrate the interplay between wit and ancient lore?",
        18: "What is the significance of Smaug as a symbol of greed and the corrupting power of wealth?",
        19: "How does the Lonely Mountain serve as both a beacon of hope and a burden of destiny in The Hobbit?",
        20: "What narrative parallels can be drawn between the quests in The Hobbit and The Lord of the Rings?",
        21: "How does the theme of homecoming manifest in the journeys of both Frodo and Bilbo?",
        22: "What role do ancient artifacts, such as the Arkenstone, play in driving the plot of The Hobbit?",
        23: "How is the corrupting influence of the One Ring depicted through its effect on various characters?",
        24: "In what ways does Tolkien use the natural world as a reflection of Middle-earth’s moral landscape?",
        25: "How does the diverse fellowship illustrate the strength found in unity and cooperation?",
        26: "What is the importance of the Council of Elrond in uniting the Free Peoples against evil?",
        27: "How do the themes of sacrifice and friendship evolve throughout the Fellowship’s journey?",
        28: "What does the perilous trek to Mount Doom reveal about Frodo’s inner conflicts?",
        29: "How does Arwen contribute to the themes of hope and renewal in LOTR?",
        30: "What role does destiny play in Aragorn’s acceptance of his kingship?",
        31: "How do the different races of Middle-earth represent varied facets of society and culture?",
        32: "What symbolic significance do the Ents hold in the struggle against industrialized evil?",
        33: "How does the contrast between Elven immortality and mortal fragility shape character choices?",
        34: "What insights does Galadriel offer regarding power, temptation, and the burden of foresight?",
        35: "How do the epic battles in LOTR serve as metaphors for the eternal struggle between light and dark?",
        36: "In what ways do the simple lives of hobbits in the Shire counterbalance the epic scope of the journey?",
        37: "How does Boromir’s internal conflict highlight the seductive pull of the Ring’s power?",
        38: "What narrative importance is found in the breaking of the Fellowship and the ensuing solo quests?",
        39: "How does the depiction of Mordor as a desolate wasteland mirror the corruption of its master?",
        40: "What role does ancient lore play in grounding the mythic history of Middle-earth?",
        41: "How does the battle for Helm’s Deep illustrate themes of resilience and unity against overwhelming odds?",
        42: "What does the destruction of the One Ring symbolize in terms of sacrifice and renewal?",
        43: "How do the personal sacrifices of characters like Merry and Pippin contribute to the greater quest?",
        44: "What cinematic techniques bring the vast world of Middle-earth to life on screen?",
        45: "How does the blend of practical effects and CGI enhance the authenticity of Tolkien’s universe?",
        46: "What is the significance of the Fellowship’s reunion at the story’s end?",
        47: "How does the Amazon series 'The Rings of Power' expand upon Tolkien’s established lore?",
        48: "In what ways does 'The Rings of Power' reinterpret the early history of Middle-earth for modern audiences?",
        49: "How do the central themes in 'The Rings of Power' compare with those in LOTR and The Hobbit?",
        50: "What new insights about the creation of the Rings does the Amazon series offer?",
        51: "How does the portrayal of Númenor in 'The Rings of Power' reflect themes of ambition and downfall?",
        52: "What role does destiny play in shaping the fates of characters introduced in 'The Rings of Power'?",
        53: "How do the visual aesthetics of 'The Rings of Power' capture the epic scope of ancient Middle-earth?",
        54: "What parallels exist between the struggles in 'The Rings of Power' and those in LOTR?",
        55: "How does the musical score of 'The Rings of Power' evoke the ancient mystique of Middle-earth?",
        56: "Which character in 'The Rings of Power' best embodies the themes of hope amidst despair?",
        57: "How does 'The Rings of Power' explore the origins of evil through its depiction of early conflicts?",
        58: "What impact do new characters in 'The Rings of Power' have on the established mythology of Tolkien’s world?",
        59: "How is magic portrayed differently in 'The Rings of Power' compared to LOTR?",
        60: "What are your thoughts on the narrative pacing of 'The Rings of Power' versus the LOTR films?",
        61: "How does Elrond’s character reflect the timeless wisdom and burdens of the Elven race?",
        62: "What is the significance of Frodo’s reluctance to bear the weight of the One Ring?",
        63: "How does Sam’s unwavering loyalty serve as the emotional heart of The Lord of the Rings?",
        64: "What does the journey through Lothlórien reveal about healing and the power of Elven grace?",
        65: "How is the theme of temptation explored through the seductive allure of the One Ring?",
        66: "What leadership lessons can be drawn from Aragorn’s path to reclaiming his heritage?",
        67: "How does Legolas’ deep connection to nature enhance his role as a guardian of Middle-earth?",
        68: "What does Gimli’s growing friendship with Legolas say about overcoming ancient enmities?",
        69: "How does Faramir’s character offer a counterpoint to Boromir’s tragic choices?",
        70: "What is the symbolic significance of the fall of Isengard and Saruman’s downfall?",
        71: "How do ancient ruins and lost kingdoms contribute to the epic atmosphere of Middle-earth?",
        72: "What role does prophecy play in driving the actions of key characters in LOTR?",
        73: "How do the personal journeys of Merry and Pippin reflect broader themes of growth and courage?",
        74: "What insights does Eowyn’s character offer about challenging traditional gender roles in war?",
        75: "How does the film adaptation capture the poetic language and spirit of Tolkien’s writings?",
        76: "What importance do the Elves place on preserving history and lore in Middle-earth?",
        77: "How is the portrayal of Orcs used to underscore the pervasive nature of evil in LOTR?",
        78: "What does Treebeard reveal about the ancient wisdom and enduring strength of the Ents?",
        79: "How do the climactic battles in LOTR serve as a culmination of hope and sacrifice?",
        80: "What symbolic role does the reforged sword Andúril play in signifying Aragorn’s destiny?",
        81: "How does the transformation of the Shire from an idyllic home to a scarred land reflect war’s toll?",
        82: "What does the theme of exile reveal about the characters’ struggles to reclaim their identities?",
        83: "How does the tension between old magic and new ambition drive the plot in both The Hobbit and LOTR?",
        84: "What is the importance of the Council of Elrond in uniting diverse peoples against Sauron?",
        85: "How do the sacrifices at the Battle of Pelennor Fields resonate with the themes of honor and duty?",
        86: "In what ways does Boromir’s character highlight the corrupting allure of absolute power?",
        87: "How is the theme of redemption portrayed through characters like Gollum and Faramir?",
        88: "What symbolic weight does the journey through the Dead Marshes add to the narrative?",
        89: "How do the internal struggles of the Fellowship mirror the broader battle between hope and despair?",
        90: "What lessons about leadership emerge from Eomer’s rise in Rohan?",
        91: "How do ancient relics and artifacts deepen the historical tapestry of Middle-earth?",
        92: "What does the battle for Minas Tirith reveal about the resilience of the Free Peoples?",
        93: "How does the pursuit of forbidden knowledge influence the quests of Middle-earth’s heroes?",
        94: "What does the shattered mirror of Narsil symbolize in the restoration of hope in LOTR?",
        95: "How does the journey of the Fellowship encapsulate the timeless struggle between good and evil?",
        96: "What role does destiny play in shaping the lives of Frodo and Aragorn?",
        97: "How do quiet moments of reflection among the hobbits deepen the emotional impact of their journey?",
        98: "What is the significance of Middle-earth’s natural landscapes in conveying its mood and history?",
        99: "How does the interplay of light and dark imagery enhance the narrative of LOTR?",
        100: "What narrative bridge does Bilbo provide between The Hobbit and The Lord of the Rings?",
        101: "How does Bilbo’s discovery of the Ring set the stage for the epic events to come?",
        102: "What does Bilbo’s transformation from a timid hobbit to an adventurer reveal about courage?",
        103: "How does the motif of unexpected heroism emerge in both Bilbo’s and Frodo’s journeys?",
        104: "What thematic parallels exist between Bilbo’s quest in The Hobbit and Frodo’s in LOTR?",
        105: "How do ancient ruins and lost civilizations add to the mystique of Tolkien’s world?",
        106: "What role does prophecy play in directing the destinies of Middle-earth’s inhabitants?",
        107: "How does Boromir’s tragic fate underscore the high cost of ambition in LOTR?",
        108: "What impact does the loss of innocence have on characters facing the brutal realities of war?",
        109: "How is the struggle for power among Men depicted as a broader commentary on corruption?",
        110: "What does the White Tree of Gondor symbolize in the context of hope and renewal?",
        111: "How do the motifs of exile and return operate in both The Hobbit and LOTR?",
        112: "What lessons about leadership and sacrifice can be learned from Aragorn’s journey?",
        113: "How does the interplay between destiny and free will influence decisions made by Middle-earth’s heroes?",
        114: "What is the significance of ancient lore and legends in shaping the narrative of LOTR?",
        115: "How does the portrayal of the Rohirrim capture the spirit of resilience and freedom?",
        116: "What role does the natural world play in helping characters discover their identities?",
        117: "How does Galadriel serve as a moral guide amid the chaos of war in Middle-earth?",
        118: "What does the journey into the Mines of Moria reveal about the characters’ inner fears?",
        119: "How do moments of camaraderie within the Fellowship contrast with the epic battles they face?",
        120: "What is the significance of the final stand at the Black Gate in the struggle between light and darkness?",
        121: "How does the balance between hope and despair drive the narrative momentum of LOTR?",
        122: "What can be learned from the evolving relationships among the members of the Fellowship?",
        123: "How does King Théoden’s transformation reflect themes of leadership, loss, and redemption?",
        124: "What broader lessons about corruption are revealed through Saruman’s dramatic fall?",
        125: "How do the simple perspectives of hobbits provide a counterpoint to the epic scale of war?",
        126: "What narrative techniques weave history and myth into the fabric of Middle-earth?",
        127: "How does the theme of sacrifice manifest in the individual journeys of LOTR’s heroes?",
        128: "What is the symbolic importance of the farewell at the Grey Havens?",
        129: "How do characters grapple with the burden of prophecy and destiny in their quests?",
        130: "What does the enduring legacy of the Elves reveal about the passage of time in Middle-earth?",
        131: "How do ancient rivalries among the races shape the political landscape of Tolkien’s world?",
        132: "What role does humor—especially in the hobbits’ interactions—play in lightening LOTR’s darker themes?",
        133: "How do epic battle sequences like Helm’s Deep serve as metaphors for internal conflict?",
        134: "What does the resilience of the Shire symbolize in the face of overwhelming darkness?",
        135: "How does the interplay of myth and reality enhance the immersive world-building in Tolkien’s works?",
        136: "What narrative function do wise characters like Elrond serve in guiding the heroes?",
        137: "How do the film adaptations capture the epic scale and poetic essence of Tolkien’s writings?",
        138: "What does the journey through the Old Forest represent in the context of The Hobbit?",
        139: "How does Sméagol/Gollum’s inner conflict deepen the narrative of corruption in LOTR?",
        140: "What are your thoughts on the evolving portrayal of evil through the influence of the One Ring?",
        141: "How does the theme of redemption resonate in characters such as Gollum and Boromir?",
        142: "What does Bard the Bowman’s heroic act teach us about courage under dire circumstances?",
        143: "How do the trials faced by Thorin and Company reflect themes of honor and betrayal in The Hobbit?",
        144: "What is the significance of the unexpected alliances formed during the quest for the Lonely Mountain?",
        145: "How does Howard Shore’s musical score contribute to the mythic atmosphere of LOTR?",
        146: "What does the imagery of fire and light signify in the eventual defeat of Sauron?",
        147: "How do magical artifacts in Middle-earth deepen the lore and mystery of Tolkien’s universe?",
        148: "What narrative importance is attached to the downfall of figures like Sauron and Saruman?",
        149: "How does the juxtaposition of pastoral beauty with wartime devastation enhance LOTR’s emotional impact?",
        150: "What do the epic battles in LOTR reveal about the cost of war on individual lives and society?",
        151: "How does the motif of the long journey serve as a metaphor for personal growth in Middle-earth?",
        152: "What role do ancient songs and poetry play in preserving Middle-earth’s cultural heritage?",
        153: "How does the relationship between power and corruption manifest in the rise and fall of kingdoms?",
        154: "What lessons about humility and bravery can be drawn from the character arcs of the hobbits?",
        155: "How do destiny and personal choice interact to shape the outcomes of key conflicts in Middle-earth?",
        156: "What significance do titles and epithets (like 'King of the West') have in establishing character identity?",
        157: "How does the mentor role of Gandalf guide the younger generation in their quests?",
        158: "What does Middle-earth’s ancient lore suggest about the cyclical nature of history and conflict?",
        159: "How is the tension between tradition and progress reflected in the kingdoms of Men?",
        160: "What role does hope play in uniting disparate peoples against the forces of darkness?",
        161: "How does the contrast between battlefield sacrifice and quiet heroism deepen LOTR’s narrative?",
        162: "What impact do ancient prophecies have on the motivations of Middle-earth’s heroes?",
        163: "How does the cinematic portrayal of Middle-earth balance epic scale with intimate character moments?",
        164: "What does the creation of Tolkien’s languages add to the authenticity of his world?",
        165: "How does the tension between the old world and the new manifest in Middle-earth’s political structures?",
        166: "What is the narrative significance of the various realms and their unique cultures in LOTR?",
        167: "How does the quest for the One Ring reveal the true nature of its bearers?",
        168: "What symbolic meaning is conveyed by the breaking of the Fellowship on the road to Mount Doom?",
        169: "How do natural elements like wind, water, and earth contribute to the thematic structure of Middle-earth?",
        170: "What parallels exist between the fall of ancient civilizations in Middle-earth and real-world history?",
        171: "How does Lothlórien embody themes of timeless beauty and sorrow in its ethereal setting?",
        172: "What role do exile and the longing for home play in the narratives of Aragorn and Frodo?",
        173: "How does the quest for the One Ring explore the interplay between temptation, power, and sacrifice?",
        174: "What are your thoughts on the portrayal of forbidden love and unexpected alliances in turbulent times?",
        175: "How do different cinematic adaptations compare in capturing the essence of Tolkien’s epic?",
        176: "What impact does the legacy of past wars have on the conflicts depicted in LOTR?",
        177: "How does symbolic imagery like the Eye of Sauron enhance the narrative tension in Middle-earth?",
        178: "What does the arduous journey across Middle-earth reveal about the inner struggles of its heroes?",
        179: "How is the theme of redemption interwoven into the final acts of The Lord of the Rings?",
        180: "What narrative techniques balance epic battle sequences with intimate character development in LOTR?",
        181: "How does the enduring spirit of the hobbits drive the narrative of hope in Middle-earth?",
        182: "What does the saga of the Ringbearers reveal about heroism in a world marred by corruption?",
        183: "How do Middle-earth’s diverse landscapes contribute to its mythic and timeless quality?",
        184: "What is the significance of quiet, introspective moments amid the grand battles of LOTR?",
        185: "How do the various leaders of Middle-earth shape the strategy against Sauron’s forces?",
        186: "What lessons about unity and division emerge from the alliances formed in LOTR?",
        187: "How does the legacy of ancient heroes influence the actions of characters in Middle-earth?",
        188: "What role do recurring symbols, such as the Evenstar, play in the personal journeys of characters like Arwen?",
        189: "How is the theme of impermanence reflected in the transient nature of beauty and power in Middle-earth?",
        190: "What insights into the corrupting nature of power can be drawn from the influence of the One Ring?",
        191: "How do interpersonal dynamics within the Fellowship enrich the epic narrative of LOTR?",
        192: "What narrative parallels exist between the rise and fall of kingdoms in Middle-earth and modern societies?",
        193: "How does the portrayal of ancient evils, like the Nazgûl, emphasize the eternal struggle between light and dark?",
        194: "What is the metaphorical significance of the journey to Mount Doom in terms of personal transformation?",
        195: "How do cinematic techniques such as slow-motion and close-ups during key moments enhance emotional engagement in LOTR?",
        196: "What do the final scenes of LOTR reveal about the enduring power of hope and the price of sacrifice?",
        197: "How does the return of the King symbolize the restoration of order and justice in Middle-earth?",
        198: "What impact does the departure of key characters (like Gandalf) have on the overarching narrative?",
        199: "How does the theme of exile and longing contribute to the melancholic beauty of Tolkien’s world?",
        200: "What lasting legacy do the epic tales of LOTR, The Hobbit, and Rings of Power leave on the fantasy genre?",
        201: "What are your opinions on Frodo Baggins?",
        202: "What are your opinions on Samwise Gamgee?",
        203: "What are your opinions on Gandalf?",
        204: "What are your opinions on Aragorn?",
        205: "What are your opinions on Legolas?",
        206: "What are your opinions on Gimli?",
        207: "What are your opinions on Gollum?",
        208: "What are your opinions on Saruman?",
        209: "What are your opinions on Sauron?",
        210: "What are your opinions on Galadriel?",
        211: "What are your opinions on Elrond?",
        212: "What are your opinions on Arwen?",
        213: "What are your opinions on Éowyn?",
        214: "What are your opinions on Bilbo Baggins?",
        215: "What are your opinions on Thorin Oakenshield?",
        216: "What are your opinions on Smaug?",
        217: "What are your opinions on Boromir?",
        218: "What is your favorite quote from The Hobbit?",
        219: "What are your opinions on Faramir?",
        220: "What are your opinions on Éomer?",
        221: "What are your opinions on Treebeard?",
        222: "What are your opinions on Bard the Bowman?",
        223: "What are your opinions on Radagast the Brown?",
        224: "What are your opinions on Isildur?",
        225: "What are your opinions on the Balrog?",
        226: "What do you think makes Aragorn such a compelling leader and hero?",
        227: "Frodo or Sam? Who do you think carries the greater burden in the journey to Mordor?",
        228: "What do you think is the most significant sacrifice made by any character in LOTR?",
        229: "What do you think is the most iconic scene in LOTR and why?",
        230: "If you could possess one item from LOTR, what would it be and why?",
        231: "What do you think is the most powerful moment in The Hobbit?",
        232: "How do you think the themes of friendship and loyalty are portrayed in LOTR?",
        233: "What do you think is the most underrated character in LOTR and why?",
        234: "What do you think is the most visually stunning location in Middle-earth?",
        235: "What do you think is the most important lesson we can learn from LOTR?",
        236: "What do you think is the most memorable quote from LOTR?",
        237: "How do you think the concept of 'home' is portrayed in LOTR?",
        238: "What do you think is the most significant difference between the book and film adaptations of LOTR?",
        239: "What do you think is the most epic battle in LOTR?",
        240: "What do you think is the most tragic moment in LOTR?",
        241: "What do you think is the most heartwarming moment in LOTR?",
        242: "What do you think is the most significant theme in The Hobbit?",
        243: "What do you think is the most iconic creature in Middle-earth?",
        244: "What do you think is the most significant event in the history of Middle-earth?",
        245: "What do you think is the most powerful piece of music in LOTR?",
        246: "What do you think is the most significant relationship in LOTR?",
        247: "What do you think is the most important moral dilemma faced by any character in LOTR?",
        248: "What do you think is the most significant moment of redemption in LOTR?",
        249: "What do you think is the most significant moment of betrayal in LOTR?",
        250: "What do you think is the most significant moment of courage in LOTR?",
        251: "What do you think is the most significant moment of wisdom in LOTR?",
        252: "What do you think is the most significant moment of love in LOTR?",
        253: "What is your favorite quote from LOTR?"

    }

    # s3 bucket files look up
    lookup = {
        1: "None",
        2: "None",
        3: "None",
        4: "None",
        5: "None",
        6: "None",
        7: "None",
        8: "None",
        9: "None",
        10: "None",
        11: "None",
        12: "None",
        13: "None",
        14: "None",
        15: "None",
        16: "None",
        17: "None",
        18: "None",
        19: "None",
        20: "None",
        21: "None",
        22: "None",
        23: "None",
        24: "None",
        25: "None",
        26: "None",
        27: "None",
        28: "None",
        29: "None",
        30: "None",
        31: "None",
        32: "None",
        33: "None",
        34: "None",
        35: "None",
        36: "None",
        37: "None",
        38: "None",
        39: "None",
        40: "None",
        41: "None",
        42: "None",
        43: "None",
        44: "None",
        45: "None",
        46: "None",
        47: "None",
        48: "None",
        49: "None",
        50: "None",
        51: "None",
        52: "None",
        53: "None",
        54: "None",
        55: "None",
        56: "None",
        57: "None",
        58: "None",
        59: "None",
        60: "None",
        61: "None",
        62: "None",
        63: "None",
        64: "None",
        65: "None",
        66: "None",
        67: "None",
        68: "None",
        69: "None",
        70: "None",
        71: "None",
        72: "None",
        73: "None",
        74: "None",
        75: "None",
        76: "None",
        77: "None",
        78: "None",
        79: "None",
        80: "None",
        81: "None",
        82: "None",
        83: "None",
        84: "None",
        85: "None",
        86: "None",
        87: "None",
        88: "None",
        89: "None",  # "questions/char_Yoda(puppet)/", #yoda puppet
        90: "None",
        91: "None",
        92: "None",
        93: "None",
        94: "None",
        95: "None",
        96: "None",
        97: "None",
        98: "None",
        99: "None",
        100: "None",
        101: "None",
        102: "None",
        103: "None",
        104: "None",
        105: "None",
        106: "None",
        107: "None",
        108: "None",
        109: "None",
        110: "None",
        111: "None",
        112: "None",
        113: "None",
        114: "None",
        115: "None",
        116: "None",
        117: "None",
        118: "None",
        119: "None",
        120: "None",
        121: "None",
        122: "None",
        123: "None",
        124: "None",
        125: "None",
        126: "None",
        127: "None",
        128: "None",
        129: "None",
        130: "None",
        131: "None",
        132: "None",
        133: "None",
        134: "None",
        135: "None",
        136: "None",
        137: "None",
        138: "None",
        139: "None",
        140: "None",
        141: "None",
        142: "None",
        143: "None",
        144: "None",
        145: "None",
        146: "None",
        147: "None",
        148: "None",
        149: "None",
        150: "None",
        151: "None",
        152: "None",
        153: "None",
        154: "None",
        155: "None",
        156: "None",
        157: "None",
        158: "None",
        159: "None",
        160: "None",
        161: "None",
        162: "None",
        163: "None",
        164: "None",
        165: "None",
        166: "None",
        167: "None",
        168: "None",
        169: "None",
        170: "None",
        171: "None",
        172: "None",
        173: "None",
        174: "None",
        175: "None",
        176: "None",
        177: "None",
        178: "None",
        179: "None",
        180: "None",
        181: "None",
        182: "None",
        183: "None",
        184: "None",
        185: "None",
        186: "None",
        187: "None",
        188: "None",
        189: "None",
        190: "None",
        191: "None",
        192: "None",
        193: "None",
        194: "None",
        195: "None",
        196: "None",
        197: "None",
        198: "None",
        199: "None",
        200: "None",
        201: "None",
        202: "None",
        203: "None",
        204: "None",
        205: "None",
        206: "None",
        207: "None",
        208: "None",
        209: "None",
        210: "None",
        211: "None",
        212: "None",
        213: "None",
        214: "None",
        215: "None",  # "questions/char_JudeLaw/",
        216: "None",  # "questions/char_Omega/",
        217: "None",  # "questions/char_Crosshair/",
        218: "None",  # "questions/char_Hunter/",
        219: "None",  # "questions/char_Tech/",
        220: "None",  # "questions/char_Wrecker/",
        221: "None",  # "questions/char_Echo/",
        222: "None",
        223: "None",
        224: "None",
        225: "None",
        226: "None",  # "questions/char_Leia(Kenobi-show)/",
        227: "None",  # "questions/char_Obi-Wan(Kenobi-Show)/",
        228: "None",  # "questions/char_Vader(Kenobi-show)/",
        229: "None",  # "questions/char_OwenBeruLars(Kenobi-show)/",
        230: "None",
        231: "None",  # "questions/char_SenatorOrgana(Kenobi-Show)/",
        232: "None",  # "questions/char_Kumail(Kenobi-Show)/",
        233: "None",  # "questions/char_DarthJarJar/"
        234: "None",
        235: "None",
        236: "None",
        237: "None",
        238: "None",
        239: "None",
        240: "None",
        241: "None",
        242: "None",
        243: "None",
        244: "None",
        245: "None",
        246: "None",
        247: "None",
        248: "None",
        249: "None",
        250: "None",
        251: "None",
        252: "None",
        253: "None",
        254: "None"
    }

    bucket_name = 'lotr.photos'
    file_key = 'notes/lotr_questions.txt'
    s3 = boto3.client('s3')

    try:
        # Fetch the current file from S3
        response = s3.get_object(Bucket=bucket_name, Key=file_key)
        file_content = response['Body'].read().decode('utf-8')

        # Convert the file content (string) into a Python list
        question_indices = json.loads(file_content)
        print(question_indices)

        index = random.randint(1, len(questions))

        # try again until we get new item not in list
        while index in question_indices:
            index = random.randint(1, len(questions))

        path = lookup[index]

        question_indices.insert(0, index)
        if len(question_indices) > 100:
            question_indices.pop()  # Remove the last element

        updated_content = json.dumps(question_indices)

        s3.put_object(Bucket=bucket_name, Key=file_key, Body=updated_content)
        question = questions[index]

        if path == "None":  # upload just text, no image
            client.create_tweet(text=question)
            return f"POSTED TWEET {question} with no image"

        response = s3.list_objects_v2(Bucket=bucket_name, Prefix=path)
        if 'Contents' not in response:
            return {
                'statusCode': 404,
                'body': 'No files found in the specified directory.'
            }
        # Extract file keys (paths) from the response
        file_keys = [obj['Key'] for obj in response['Contents'] if obj['Key'] != path]
        # Check if there are files to choose from
        if not file_keys:
            return {
                'statusCode': 404,
                'body': 'No files found in the specified directory.'
            }

        # Pick a random file from the list
        random_file = random.choice(file_keys)

        # these 4 are for image, not implemented yet:
        download_path = f"/tmp/{os.path.basename(random_file)}"
        s3.download_file(bucket_name, random_file, download_path)
        media = api.media_upload(download_path)
        client.create_tweet(text=question, media_ids=[media.media_id])
        return f"tweeted image with question {question}"
    except Exception as e:
        print(e)

