import random
import tweepy

marvel_api_key = 'placeholder'
marvel_api_key_secret = 'placeholder'
marvel_bearer_token = 'placeholder'
marvel_access_token = 'placeholder'
marvel_access_token_secret = 'placeholder'


client = tweepy.Client(bearer_token = marvel_bearer_token,
                                consumer_key = marvel_api_key, consumer_secret = marvel_api_key_secret,
                                access_token = marvel_access_token, access_token_secret = marvel_access_token_secret)

def post_marvel_quote(event, context):
    marvel_quotes = {
        0: "\"I can do this all day.\" -Captain America",
        1: "\"Genius, billionaire, philanthropist.\" -Tony Stark",
        2: "\"We're in the endgame now.\" -Doctor Strange",
        3: "\"Wakanda forever!\" -T'Challa",
        4: "\"I'm always angry.\" -Bruce Banner",
        5: "\"I am Iron Man.\" -Tony Stark",
        6: "\"I am Groot.\" -Groot",
        7: "\"Whatever it takes.\" -Steve Rogers",
        8: "\"I have nothing to prove to you.\" -Captain Marvel",
        9: "\"With great power comes great responsibility.\" -Uncle Ben",
        10: "\"Dread it. Run from it. Destiny arrives all the same.\" -Thanos",
        11: "\"That's my secret, Captain: I'm always angry.\" -Bruce Banner",
        12: "\"You get hurt, hurt 'em back. You get killed... walk it off.\" -Steve Rogers",
        13: "\"Puny god.\" -Hulk",
        14: "\"I understood that reference.\" -Steve Rogers",
        15: "\"We are Groot.\" -Groot",
        16: "\"The hardest choices require the strongest wills.\" -Thanos",
        17: "\"Dance off, bro!\" -Peter Quill",
        18: "\"Part of the journey is the end.\" -Tony Stark",
        19: "\"Get this man a shield.\" -T'Challa",
        20: "\"The city is flying and we're fighting an army of robots. And I have a bow and arrow. None of this makes sense.\" -Clint Barton",
        21: "\"I choose to run towards my problems, and not away from them. Because that’s what heroes do.\" -Thor",
        22: "\"Dormammu, I’ve come to bargain.\" -Doctor Strange",
        23: "\"He's a friend from work!\" -Thor",
        24: "\"I am inevitable.\" -Thanos",
        25: "\"I can’t control their fear, only my own.\" -Wanda Maximoff",
        26: "\"On your left.\" -Sam Wilson",
        27: "\"We have a Hulk.\" -Tony Stark",
        28: "\"I don’t want to go.\" -Peter Parker",
        29: "\"Language!\" -Steve Rogers",
        30: "\"The truth is... I am Iron Man.\" -Tony Stark",
        31: "\"If you're nothing without the suit, then you shouldn't have it.\" -Tony Stark",
        32: "\"I'm just a kid from Brooklyn.\" -Steve Rogers",
        33: "\"That's America's a*s.\" -Scott Lang",
        34: "\"The sun will shine on us again.\" -Thor",
        35: "\"I would rather be a good man than a great king.\" -Thor",
        36: "\"The revolution has begun!\" -Korg",
        37: "\"Hail Hydra.\" -Steve Rogers",
        38: "\"We're the Guardians of the Galaxy.\" -Peter Quill",
        39: "\"I like your plan, except it sucks.\" -Peter Quill",
        40: "\"I'm Mary Poppins, y'all!\" -Yondu",
        41: "\"I'm always picking up after you boys.\" -Natasha Romanoff",
        42: "\"You are an Avenger now.\" -Tony Stark",
        43: "\"We never lose our demons, Mordo. We only learn to live above them.\" -The Ancient One",
        44: "\"I just wanted a sister!\" -Yelena Belova",
        45: "\"I don't want to kill anyone. I don't like bullies; I don't care where they're from.\" -Steve Rogers",
        46: "\"I'm with you till the end of the line.\" -Steve Rogers",
        47: "\"I thought my dad was tough on me, but that's how he showed his love.\" -Peter Quill",
        48: "\"I see you’ve copied my beard.\" -Thor",
        49: "\"You should have gone for the head.\" -Thanos",
        50: "\"I went for the head.\" -Thor",
        51: "\"I don't judge people by their worst mistakes.\" -Sam Wilson",
        52: "\"Even when I had nothing, I had Bucky.\" -Steve Rogers",
        53: "\"This is the fight of our lives.\" -Steve Rogers",
        54: "\"It's not enough to be against something. You have to be for something better.\" -Tony Stark",
        55: "\"You're embarrassing me in front of the wizard.\" -Tony Stark",
        56: "\"I got red in my ledger, I'd like to wipe it out.\" -Natasha Romanoff",
        57: "\"This is my choice. There's no version of this where you come out on top.\" -Tony Stark",
        58: "\"No man can win every battle, but no man should fall without a struggle.\" -Peter Parker",
        59: "\"I do anything and everything that Mr. Stark requires. Including occasionally taking out the trash.\" -J.A.R.V.I.S.",
        60: "\"I have lived most of my life surrounded by my enemies. I would be grateful to die surrounded by my friends.\" -Gamora",
        61: "\"We don't trade lives.\" -Steve Rogers",
        62: "\"I don't want to go. I don't want to go, Mr. Stark.\" -Peter Parker",
        63: "\"I love you 3000.\" -Tony Stark",
        64: "\"It’s an imperfect world, but it’s the only one we got.\" -Tony Stark",
        65: "\"I see better from a distance.\" -Clint Barton",
        66: "\"You should have gone for the head.\" -Thanos",
        67: "\"I just wanted a sister!\" -Yelena Belova",
        68: "\"We're the Avengers. We gotta finish this.\" -Tony Stark",
        69: "\"Avengers... assemble!\" -Steve Rogers",
        70: "\"I’m made of rocks, as you can see, but don’t let that intimidate you.\" -Korg",
        71: "\"That's my secret, Cap. I'm always angry.\" -Bruce Banner",
        72: "\"I’ve lived a lot of lives before I met you, Ross.\" -Natasha Romanoff",
        73: "\"I’m sorry, Earth is closed today.\" -Tony Stark",
        74: "\"You’re stronger than you think.\" -Aunt May",
        75: "\"You’re a good man with a good heart. And it’s hard for a good man to be king.\" -T'Chaka",
        76: "\"Victory should be earned, not purchased.\" -Tony Stark",
        77: "\"Sometimes you gotta run before you can walk.\" -Tony Stark",
        78: "\"I am Loki of Asgard, and I am burdened with glorious purpose.\" -Loki",
        79: "\"You get to decide what kind of king you are going to be.\" -Nakia",
        80: "\"You’ll never be a god.\" -Loki",
        81: "\"She’s not alone.\" -Okoye",
        82: "\"Is this your king?\" -Erik Killmonger",
        83: "\"I will bathe the starways in your blood.\" -Ronan",
        84: "\"I don’t see how that’s a party.\" -Tony Stark",
        85: "\"We will never be gods.\" -Thanos",
        86: "\"He’s fast. She’s weird.\" -Maria Hill",
        87: "\"I’m gonna need a rain check on that dance.\" -Steve Rogers",
        88: "\"We create our own demons.\" -Tony Stark",
        89: "\"I’m with you every step of the way.\" -Peggy Carter",
        90: "\"Do you want to build a snowman? It doesn’t have to be a snowman.\" -Tony Stark",
        91: "\"I can't believe you're alive. I saw you die! I mourned you. I cried for you.\" -Thor",
        92: "\"We’re not in Kansas anymore.\" -Tony Stark",
        93: "\"I’m not looking for forgiveness. And I’m way past asking for permission.\" -Natasha Romanoff",
        94: "\"I didn’t ask to be taken to another dimension.\" -Doctor Strange",
        95: "\"You were the one I wanted to fight with me.\" -T’Challa",
        96: "\"You’re unbearably naive.\" -Stephen Strange",
        97: "\"You’re out of your mind.\" -Natasha Romanoff",
        98: "\"I have nothing left to lose.\" -Wanda Maximoff",
        99: "\"The universe is in the palm of your hand.\" -The Ancient One",
        100: "\"I was born yesterday.\" -Vision",
        101: "\"It’s not the world of spies anymore, the world is changing. None of us can go back.\" -Peggy Carter",
        102: "\"I have lived most of my life surrounded by my enemies. I would be grateful to die surrounded by my friends.\" -Gamora",
        103: "\"I’ve been fighting with one arm tied behind my back, but what happens when I’m finally set free?\" -Captain Marvel",
        104: "\"I know who you are, Peter Quill, and I am not some starry-eyed waif here to succumb to your... your pelvic sorcery!\" -Gamora",
        105: "\"I got something kinda big, but I can’t hold it forever!\" -Scott Lang",
        106: "\"I’ll do you one better. Why is Gamora?\" -Drax",
        107: "\"You’re repeating yourself.\" -Gamora",
        108: "\"You should have gone for the head.\" -Thanos",
        109: "\"I don’t want to kill anyone. I don’t like bullies.\" -Steve Rogers",
        110: "\"You couldn’t have done that earlier?\" -Sam Wilson",
        111: "\"What master do you serve?\" -Tony Stark",
        112: "\"I’m a huge fan of the way you lose control and turn into an enormous green rage monster.\" -Tony Stark",
        113: "\"I had strings, but now I’m free.\" -Ultron",
        114: "\"I had this dream... the kind that seems normal at the time.\" -Wanda Maximoff",
        115: "\"Do you know what happens to a toad when it’s struck by lightning? Same thing that happens to everything else.\" -Storm",
        116: "\"I have been falling... for 30 minutes!\" -Loki",
        117: "\"The world is changing. It’s time we change too.\" -T’Challa",
        118: "\"I need a horse!\" -Thor",
        119: "\"I can see that coming from a mile away.\" -Peter Parker",
        120: "\"I had my eyes opened. I came to realize that I had more to offer this world than just making things that blow up.\" -Tony Stark",
        121: "\"I shouldn't be alive... unless it was for a reason.\" -Tony Stark",
        122: "\"The truth is... I am Iron Man.\" -Tony Stark",
        123: "\"Sometimes you gotta run before you can walk.\" -Tony Stark",
        124: "\"I had my eyes opened. I came to realize that I had more to offer this world than just making things that blow up.\" -Tony Stark",
        125: "\"I’m just not the hero type. Clearly.\" -Tony Stark",
        126: "\"Is it better to be feared or respected? I say, is it too much to ask for both?\" -Tony Stark",
        127: "\"I shouldn't be alive, unless it was for a reason. I'm not crazy, Pepper. I just finally know what I have to do.\" -Tony Stark",
        128: "\"The best weapon is one you never have to fire.\" -Tony Stark",
        129: "\"I am Iron Man. The suit and I are one.\" -Tony Stark",
        130: "\"Whatever happens tomorrow, you must promise me one thing: that you will stay who you are. Not a perfect soldier, but a good man.\" -Dr. Erskine",
        131: "\"I don't want to kill anyone. I don't like bullies; I don't care where they're from.\" -Steve Rogers",
        132: "\"You’re late.\" -Peggy Carter",
        133: "\"I'm just a kid from Brooklyn.\" -Steve Rogers",
        134: "\"I can offer you a chance. Only a chance.\" -Dr. Erskine",
        135: "\"The serum amplifies everything that is inside. So good becomes great. Bad becomes worse.\" -Dr. Erskine",
        136: "\"You must promise me one thing. That you will stay who you are. Not a perfect soldier, but a good man.\" -Dr. Erskine",
        137: "\"I had a date.\" -Steve Rogers",
        138: "\"The price of freedom is high. It always has been. And it’s a price I’m willing to pay.\" -Steve Rogers",
        139: "\"You're a laboratory experiment, Rogers. Everything special about you came out of a bottle!\" -Tony Stark",
        140: "\"Do you still think you’re the only superhero in the world?\" -Nick Fury",
        141: "\"I come with glad tidings... of a world made free.\" -Loki",
        142: "\"This drink, I like it! Another!\" -Thor",
        143: "\"Whosoever holds this hammer, if he be worthy, shall possess the power of Thor.\" -Odin",
        144: "\"Do you swear to guard the Nine Realms?\" -Odin",
        145: "\"I just wanted to be like you.\" -Peter Parker",
        146: "\"This mortal form grows weak. I need sustenance!\" -Thor",
        147: "\"I have no plans to die today.\" -Thor",
        148: "\"In the end, you will always kneel.\" -Loki",
        149: "\"Brother, however I have wronged you, whatever I have done to lead you to do this, I am truly sorry.\" -Thor",
        150: "\"I never wanted the throne! I only ever wanted to be your equal!\" -Loki",
        151: "\"Is this the first time you’ve lost a soldier?\" -Nick Fury",
        152: "\"I still believe in heroes.\" -Nick Fury",
        153: "\"We have a Hulk.\" -Tony Stark",
        154: "\"You people are so petty... and tiny.\" -Thor",
        155: "\"I thought humans were more evolved.\" -Loki",
        156: "\"There’s only one God, ma’am, and I’m pretty sure he doesn’t dress like that.\" -Steve Rogers",
        157: "\"You’re my mission!\" -Bucky Barnes",
        158: "\"I’m nothing without the suit.\" -Peter Parker",
        159: "\"I can’t lead a mission when the people I’m leading have missions of their own.\" -Steve Rogers",
        160: "\"Before we get started, does anyone want to get out?\" -Steve Rogers",
        161: "\"I know you’re good people. I know you mean well.\" -Sam Wilson",
    }

    tweet_text = marvel_quotes[random.randint(0,161)]
    tagsString = f" "
    tags = ["#Marvel ", "#MarvelStudios ", "#MCU "]  # i can add more possible tags if desired
    for tag in tags:
        randomProb = 0.1  # each tag has 10% chance of being included unless otherwise specified
        if random.random() < randomProb:
            tagsString += tag
    tweet_text += tagsString
    client.create_tweet(text=tweet_text)
