
# posts to the account at https://x.com/_TheOfficeDaily
import requests
import tweepy
import random
# These are placeholders so my keys won't be on a public github repo
bearer_token = 'placeholder'
api_key = 'placeholder'
api_key_secret = 'placeholder'
access_token = 'placeholder'
access_token_secret = 'placeholder'

# Set up Tweepy client for Twitter API v2
client = tweepy.Client(bearer_token=bearer_token,
                       consumer_key=api_key,
                       consumer_secret=api_key_secret,
                       access_token=access_token,
                       access_token_secret=access_token_secret)

#here
def post_office_quote(event, context):
    office_quotes = {
        0: "\"I would not miss it for the world. But if something else came up, I would definitely not go.\" -Michael Scott",
        1: "\"I’m guessing Angela is the one in the neighborhood that gives the trick-or-treaters toothbrushes, pennies, walnuts.\" -Pam Beesly",
        2: "\"Why are all these people here? There’s too many people on this earth. We need a new plague.\" -Dwight Schrute",
        3: "\"I am faster than 80 percent of all snakes.\" -Dwight Schrute",
        4: "\"That’s what she said!\" -Michael Scott",
        5: "\"It’s never the person who you most suspect. It’s also never the person you least suspect, since anyone with half a brain would suspect them the most. Therefore, I know the killer to be Phyllis. The person who I most medium suspect.\" -Dwight Schrute",
        6: "\"Today, smoking is going to save lives.\" -Dwight Schrute",
        7: "\"If you don’t like it, Stanley, you can go to the back of the bus, or the front of the bus, or drive the bus.\" -Michael Scott",
        8: "\"Babies are one of my many areas of expertise. Growing up, I performed my own circumcision.\" -Dwight Schrute",
        9: "\"They say that your wedding day goes by in such a flash that you’re lucky if you even get a piece of your own cake. I say that’s crazy. I say let them eat cake. Margaret Thatcher said that about marriage. Smart broad.\" -Michael Scott",
        10: "\"Identity theft is not a joke, Jim! Millions of families suffer every year.\" -Dwight Schrute",
        11: "\"I would say I kind of have an unfair advantage because I watch reality dating shows like a hawk, and I learn. I absorb information from the strategies of the winners and the losers. Actually, I probably learn more from the losers.\" -Michael Scott",
        12: "\"Now that I own the building, I’m looking for new sources of revenue. And a daycare center? Muahahahahahahahaha. Well, I guess it’s not an evil idea, it’s just a regular idea, but there’s no good laugh for a regular idea.\" -Dwight Schrute",
        13: "\"Webster’s Dictionary defines wedding as ‘the fusing of two metals with a hot torch.'\" -Michael Scott",
        14: "\"Here it is, heart of New York City, Times Square… named for the good times you have when you’re in it.\" -Michael Scott",
        15: "\"Yes, I have acted before. I was in a production of Oklahoma! In the seventh grade. I played the part of Mutey the Mailman. They had too many kids, so they made up roles like that. I was good.\" -Dwight Schrute",
        16: "\"I… declare…. bankruptcy!\" -Michael Scott",
        17: "\"You know a human can go on living for several hours after being decapitated.\" -Creed Bratton",
        18: "\"Through concentration, I can raise and lower my cholesterol at will.\" -Dwight Schrute",
        19: "\"I don’t care what they say about me. I just want to eat. Which I realize is a lot to ask for…at a dinner party.\" -Pam Beesly",
        20: "\"And I knew exactly what to do. But in a much more real sense, I had no idea what to do.\" -Michael Scott",
        21: "\"Not enough for me? You are everything.\" -Jim Halpert",
        22: "\"Michael always says, ‘K-I-S-S: keep it simple, stupid.’ Great advice. Hurts my feelings every time.\" -Dwight Schrute",
        23: "\"There’s no such thing as an appropriate joke. That’s why it’s called a joke.\" -Michael Scott",
        24: "\"If you break that girl’s heart, I will kill you. That’s just a figure of speech. But seriously, if you break that girl’s heart, I will literally kill you and your entire family.\" -Michael Scott",
        25: "\"Bears are more afraid of you than you are of them? You obviously aren’t scared enough.\" -Dwight Schrute",
        26: "\"You only live once? False. You live every day. You only die once.\" -Dwight Schrute",
        27: "\"That has sort of an oaky afterbirth.\" -Michael Scott",
        28: "\"I am Michael, and I am part English, Irish, German, and Scottish… sort of a virtual United Nations.\" -Michael Scott",
        29: "\"It’s a real shame because studies have shown that more information gets passed through water cooler gossip than through official memos. Which puts me at a disadvantage because I bring my own water to work.\" -Dwight Schrute",
        30: "\"I’m not superstitious but I am a little stitious.\" -Michael Scott",
        31: "\"I enjoy having breakfast in bed. I like waking up to the smell of bacon, sue me. And since I don’t have a butler, I do it myself. So, most nights before I go to bed, I will lay six strips of bacon out on my George Foreman Grill. Then I go to sleep. When I wake up, I plug in the grill, I go back to sleep again. Then I wake up to the smell of crackling bacon.\" -Michael Scott",
        32: "\"Jim told me you could buy gaydar online.\" -Dwight Schrute",
        33: "\"You better learn your rules. If you don’t, you’ll be eaten in your sleep.\" -Dwight Schrute",
        34: "\"Once I’m officially Regional Manager, my first order of business will be to demote Jim Halpert. So, I will need a new number two. My ideal choice? Jack Bauer. But he is unavailable. Fictional. And overqualified.\" -Dwight Schrute",
        35: "\"I’ve been involved in a number of cults, both a leader and a follower. You have more fun as a follower, but you make more money as a leader.\" -Creed Bratton",
        36: "\"I don't talk trash; I talk smack. They're totally different. Trash talk is all hypothetical, like, 'Your Mama's so fat she could eat the internet', but smack talk is happening like right now, like, 'You're ugly and I know it for a fact 'cause I got the evidence right there.'\" -Kelly Kapoor",
        37: "\"Always the Padawan, never the Jedi.\" -Dwight Schrute",
        38: "\"I think green is kind of whorish.\" -Angela Martin",
        39: "\"I always wondered how they picked the person to die. I’d be good at picking the person.\" -Dwight Schrute",
        40: "\"Is there something besides ‘Mexican’ you prefer to be called? Something less offensive?\" -Michael Scott",
        41: "\"When someone smiles at me, all I see is a chimpanzee begging for its life.\" -Dwight Schrute",
        42: "\"Let’s put a smile on that face.\" -Creed Bratton",
        43: "\"I’m not usually the butt of the joke. I’m usually the face of the joke.\" -Michael Scott",
        44: "\"Did I stutter?\" -Stanley Hudson",
        45: "\"OK, see you later, Pan.\" -Dwight Schrute",
        46: "\"I don’t want any special treatment, Pam. I just want you to treat me like you would some family member who’s undergone some sort of serious physical trauma. I don’t think that’s too much to ask?\" -Michael Scott",
        47: "\"I guess the attitude that I’ve tried to create here is that I’m a friend first and a boss second and probably an entertainer third.\" -Michael Scott",
        48: "\"When my mother was pregnant with me, they did an ultrasound and found she was having twins. When they did another ultrasound a few weeks later, they discovered that I had adsorbed the other fetus. Do I regret this? No, I believe his tissue has made me stronger. I now have the strength of a grown man and a little baby.\" -Dwight Schrute",
        49: "\"An office is not for dying. An office is a place for living life to the fullest, to the max, to… an office is a place where dreams come true.\" -Michael Scott",
        50: "\"The Civil War history industry has conveniently forgotten about the battle of Schrute Farms. Whatever. I’m over it. It’s just grossly irresponsible.\" -Dwight Schrute",
        51: "\"When I discovered YouTube, I didn’t work for five days.\" -Michael Scott",
        52: "\"Oh, you know that line on the top of the shrimp? That’s feces.\" -Dwight Schrute",
        53: "\"Well, well, well, how the turntables.\" -Michael Scott",
        54: "\"Would I ever leave this company? Look, I’m all about loyalty. In fact, I feel like part of what I’m being paid for here is my loyalty. But if there were somewhere else that valued loyalty more highly… I’m going wherever they value loyalty the most.\" -Dwight Schrute",
        55: "\"I always knew I would be destroyed by my own creation, but honestly, I thought it would be that bull that Mose and I are trying to reanimate.\" -Dwight Schrute",
        56: "\"I fell in love with these kids. And I didn’t want to see them fall victim to the system. So I made ’em a promise. I told them if they graduated from high school, I would pay for their college education. I have made some empty promises in my life but, hands down, that was the most generous.\" -Michael Scott",
        57: "\"Toby is in HR, which technically means he works for corporate. So he’s not really a part of our family. Also, he’s divorced, so he’s not really a part of his family.\" -Michael Scott",
        58: "\"I wonder if king-sized sheets are called presidential-sized in England?\" -Dwight Schrute",
        59: "\"Society teaches us that having feelings and crying is bad and wrong. Well, that’s baloney, because grief isn’t wrong. There’s such a thing as good grief. Just ask Charlie Brown.\" -Michael Scott",
        60: "\"Security in this office park is a joke. Last year I came to work with my spud-gun in a duffel bag. I sat at my desk all day with a rifle that shoots potatoes at 60 pounds per square inch. Can you imagine if I was deranged?\" -Dwight Schrute",
        61: "\"D.W.I.G.H.T. Determined. Worker. Intense. Good worker. Hard worker. Terrific.\" -Dwight Schrute",
        62: "\"About 40 times a year, Michael gets sick but has no symptoms. Dwight is always gravely concerned.\" -Michael Scott",
        63: "\"When held over heat, the invisible ink will reveal that everyone should meet at the warehouse immediately. Do not ask me where I got the invisible ink. Urine. It was urine.\" -Dwight Schrute",
        64: "\"People will never be replaced by machines. In the end, life and business are about human connections. And computers are about trying to murder you in a lake. And to me the choice is easy.\" -Michael Scott",
        65: "\"Creed Bratton has never declared bankruptcy. When Creed Bratton gets in trouble, he transfers his debt to William Charles Scheider.\" -Creed Bratton",
        66: "\"Twelve hundred dollars is what I spent on my whole bomb shelter. For that kind of money, this stroller should be indestructible.\" -Dwight Schrute",
        67: "\"I saved a life. My own. Am I a hero?… I really can’t say, but yes!\" -Michael Scott",
        68: "\"Can’t a guy just buy some bagels for his friends so they’ll owe him a favor which he can use to get someone fired who stole a co-manager position from him anymore? Jeez. When did everyone get so cynical?\" -Dwight Schrute",
        69: "\"We’re all homos. Homo… Sapiens.\" -Michael Scott",
        70: "\"When I President, they see. They see.\" -Kevin Malone",
        71: "\"Well, it’s love at first sight. Actually, it was… no, it was when I heard her voice. It was love at first see with my ears.\" -Michael Scott",
        72: "\"All that singing got in the way of some perfectly good murders.\" -Dwight Schrute",
        73: "\"I love my employees even though I hit one of you with my car.\" -Michael Scott",
        74: "\"Make friends first, make sales second, make love third. In no particular order.\" -Michael Scott",
        75: "\"They say that no man is an island. False! I am an island and this island is volcanic. And it is about to erupt. With the molten hot lava of strategy!\" -Dwight Schrute",
        76: "\"The eyes are the groin of the head.\" -Dwight Schrute",
        77: "\"Schrute Farms is very easy to find. It’s right in the middle of the root vegetable district. If the soil starts to get acidic, you’ve gone too far.\" -Dwight Schrute",
        78: "\"What is my perfect crime? I break into Tiffany’s at midnight. Do I go for the vault? No, I go for the chandelier. It’s priceless. As I’m taking it down, a woman catches me. She tells me to stop. It’s her father’s business. She’s Tiffany. I say no. We make love all night. In the morning, the cops come, and I escape in one of their uniforms. I tell her to meet me in Mexico, but I go to Canada. I don’t trust her. Besides, I like the cold. Thirty years later, I get a postcard. I have a son, and he’s the chief of police. This is where the story gets interesting. I tell Tiffany to meet me in Paris by the Trocadero. She’s been waiting for me all these years. She’s never taken another lover. I don’t care. I don’t show up. I go to Berlin. That’s where I stashed the chandelier.\" -Dwight Schrute",
        79: "\"At first, I drove myself crazy thinking about the things I should have done differently. I never should have played that joke on Erin. I never should have hollowed out this damn pumpkin in the first place. Then I realized that I was being silly. I mean, the pumpkin should rot off of my head in a month or two. Right?\" -Dwight Schrute",
        80: "\"Michael will be related to this baby through... delusion.\" -Jim Halpert",
        81: "\"You couldn’t handle my undivided attention.\" -Dwight Schrute",
        82: "\"People underestimate the power of nostalgia. Nostalgia is truly one of the greatest human weaknesses, second only to the neck.\" -Dwight Schrute",
        83: "\"You think you’re excited? You should feel my nipples. Boing!\" -Dwight Schrute",
        84: "\"I am running away from my responsibilities. And it feels good.\" -Michael Scott",
        85: "\"I signed up for second life about a year ago. Back then, my life was so great that I literally wanted a second one. Absolutely everything was the same… except I could fly.\" -Dwight Schrute",
        86: "\"And I’m optimistic because every day I get a little more desperate.\" -Michael Scott",
        87: "\"It’s Britney, bitch.\" -Michael Scott",
        88: "\"No, don’t call me a hero. Do you know who the real heroes are? The guys who wake up every morning and go into their normal jobs and get a distress call from the Commissioner and take off their glasses and change into capes and fly around fighting crime. Those are the real heroes.\" -Dwight Schrute",
        89: "\"‘R’ is among the most menacing of sounds. That’s why they call it ‘murder’ and not mukduk’.\" -Dwight Schrute",
        90: "\"Listen up, Flenderson, you’re being weak and ineffectual. I’m cowboying this meeting, OK! Here are the new rules, OK? Earth tones only. Also, women are forbidden to wear pants.\" -Dwight Schrute",
        91: "\"Who is Justice Beaver?\" -Dwight Schrute",
        92: "\"You know, I really would’ve appreciated a heads up that you were into dating mothers. I would’ve introduced you to mine.\" -Dwight Schrute",
        93: "\"Do I have a date for Valentine’s Day? Yes. February 14th.\" -Dwight Schrute",
        94: "\"You know what they say about a car wreck, where it’s so awful you can’t look away? The Dundies are like a car wreck that you want to look away from, but you have to stare at it because your boss is making\" -Pam Beesly",
        95: "\"Bears, Beets, Battlestar Galactica.\" -Jim Halpert",
        96: "\"It’s a good thing Russia doesn’t exist anymore.\" -Michael Scott",
        97: "\"There are a huge number of yeast infections in this county. Probably because we’re downriver from that old bread factory.\" -Dwight Schrute",
        98: "\"Any man who says he totally understands women is a fool. Because they are un-understandable.\" -Michael Scott",
        99: "\"Hold me! Cradle my hand!\" -Dwight Schrute",
        100: "\"I’m not a millionaire. I thought I would be by the time I was 30, but I wasn’t even close. Then I thought maybe by 40, but by 40, I had less money than I did when I was 30.\" -Michael Scott",
        101: "\"If I had a gun with two bullets and I was in a room with Hitler, Bin Laden, and Toby, I would shoot Toby twice.\" -Michael Scott",
        102: "\"I’m gonna intimidate him, OK? Watch this… So anyways, she said that is the biggest penis I have ever seen, and I said I know! That’s why I brought you to the penis museum, where tickets are a thousand dollars.\" -Dwight Schrute",
        103: "\"Those who can’t farm, farm celery.\" -Dwight Schrute",
        104: "\"I wanna do a cartwheel. But real casual-like. Not enough to make a big deal out of it, but I know everyone saw it. One stunning, gorgeous cartwheel.\" -Creed Bratton",
        105: "\"I never thought I’d say this, but I think I ate too much bone marrow.\" -Dwight Schrute",
        106: "\"I studied him, to figure out why I hated him so much. But that blossomed into a very real friendship, as these things often do.\" -Dwight Schrute",
        107: "\"And I will travel to New Zealand. And walk the Lord of the Rings trail to Mordor.\" -Dwight Schrute",
        108: "\"Oh, you’re paying way too much for worms. Who’s your worm guy?\" -Creed Bratton",
        109: "\"I’m not gonna cry over it. I did that in the car on the way home.\" -Michael Scott",
        110: "\"The principle is sound. To avoid illness, expose yourself to germs, enabling your immune system to develop antibodies. I don’t know why everyone doesn’t do this… maybe they have something against living forever.\" -Dwight Schrute",
        111: "\"Hey, what has two thumbs and hates Todd Packer? This guy.\" -Jim Halpert",
        112: "\"Of course, martial arts training is relevant… Uh, I know about a billion Asians that would beg to differ… You know what, you can go to hell, and I will see you there. Burning!\" -Dwight Schrute",
        113: "\"I wish I could menstruate. If I could menstruate, I wouldn’t have to deal with idiotic calendars anymore. I’d just be able to count down from my previous cycle. Plus, I’d be more in tune with the moon and the tides.\" -Dwight Schrute",
        114: "\"Guess what, I have flaws. What are they? Oh, I don’t know. I sing in the shower. Sometimes I spend too much time volunteering. Occasionally I’ll hit somebody with my car. So sue me.\" -Michael Scott",
        115: "\"I’m sinking a few, you know. Swish, swish, swish. Nothing but net. And their jaws just dropped to the floor. African-Americans!\" -Michael Scott",
        116: "\"Granted, maybe this was not the best idea, but at least we care enough about our employees that we are willing to fight for them.\" -Michael Scott",
        117: "\"Bread is the paper of the food industry. You write your sandwich on it.\" -Dwight Schrute",
        118: "\"Five minutes ahead of schedule… right on schedule.\" -Dwight Schrute",
        119: "\"Will I get over it? Mmm. No. But life goes on.\" -Dwight Schrute",
        120: "\"Jim is my enemy. But it turns out that Jim is also his own worst enemy. And the enemy of my enemy is my friend. So, Jim is actually my friend. But because he is his own worst enemy, the enemy of my friend is my enemy so, actually, Jim is my enemy.\" -Dwight Schrute",
        121: "\"A real man swallows his vomit when a lady is present.\" -Dwight Schrute",
        122: "\"I know it’s illegal in Pennsylvania, but it’s for charity, and I consider myself a great philanderer.\" -Michael Scott",
        123: "\"They always say that it’s a mistake to hire your friends. And they are right. So, I hired my best friends. And this is what I get!?\" -Michael Scott",
        124: "\"You cheated on me? When I specifically asked you not to?\" -Michael Scott",
        125: "\"No, I’m not going to tell them about the downsizing. If a patient has cancer, you don’t tell them.\" -Michael Scott",
        126: "\"It’s not like booze ever killed anyone.\" -Michael Scott",
        127: "\"It’s better to be hurt by someone you know accidentally, than by a stranger on purpose.\" -Dwight Schrute",
        128: "\"You are as creepy as a real serial killer. For real.\" -Michael Scott",
        129: "\"It’s a pimple, Phyllis. Avril Lavigne gets them all the time, and she rocks harder than anyone alive.\" -Michael Scott",
        130: "\"The hand that reaches from the grave to grip your throat is the strong hand you want on the wheel.\" -Dwight Schrute",
        131: "\"I wonder if king-sized sheets are called presidential-sized in England.\" -Dwight Schrute",
        132: "\"It’s not effeminate. It’s festive.\" -Dwight Schrute",
        133: "\"No, Rose, they are not breathing. And they have no arms or legs… Where are they? You know what? If we come across somebody with no arms or legs, do we bother resuscitating them? I mean, what quality of life do we have there?\" -Michael Scott",
        134: "\"It's like I used to tell my wife: I do not apologize unless I think I'm wrong, and if you don't like it, you can leave. I say the same thing to my current wife, and I'll say it to my next one too.\" -Stanley Hudson",
        135: "\"Like right here is my favorite New York pizza joint. And I’m going to go get me a New York slice.\" -Michael Scott",
        136: "\"A hero kills people, people that wish him harm. A hero is part human and part supernatural. A hero is born out of a childhood trauma, or out of a disaster, that must be avenged.\" -Dwight Schrute",
        137: "\"I wanna be married and have 100 kids so I can have 100 friends and no one can say ‘no’ to being my friend.\" -Michael Scott",
        138: "\"And I misspelled, in front of the entire school, the word ‘failure.’\" -Dwight Schrute",
        139: "\"Dolphins get a lot of good publicity for the drowning swimmers they push back to shore, but what you don’t hear about is the many people they push farther out to sea! Dolphins aren’t smart. They just like pushing things.\" -Dwight Schrute",
        140: "\"My philosophy is, basically this. And this is something that I live by. And I always have. And I always will. Don’t, ever, for any reason, do anything, to anyone, for any reason, ever, no matter what, no matter where, or who you are with, or, or where you are going, or, or where you’ve been. Ever. For any reason. Whatsoever.\" -Michael Scott",
        141: "\"Do I need to be liked? Absolutely not. I like to be liked. I enjoy being liked. I have to be liked, but it’s not like this compulsive need to be liked, like my need to be praised.\" -Michael Scott",
        142: "\"Saw Inception. Or at least I dreamt I did.\" -Michael Scott",
        143: "\"It is St. Patrick’s Day. And here in Scranton, that is a huge deal. It is the closest that the Irish will ever get to Christmas.\" -Michael Scott",
        144: "\"They say on your deathbed you never wish you spent more time at the office — but I will.\" -Michael Scott",
        145: "\"I already won the lottery. I was born in the US of A, baby. And as backup, I have a Swiss passport.\" -Creed Bratton",
        146: "\"Dwight, you ignorant slut.\" -Michael Scott",
        147: "\"I miss Dwight. Congratulations Universe, you win.\" -Jim Halpert",
        148: "\"Wikipedia is the best thing ever. Anyone in the world can write anything they want about any subject. So you know you are getting the best possible information.\" -Michael Scott",
        149: "\"I have cause. It’s beCAUSE I hate him.\" -Michael Scott",
        150: "\"The rules of shotgun are very simple and very clear. The first person to shout ‘shotgun’ when you’re within sight of the car gets the front seat. That’s how the game’s played. There are no exceptions for someone with a concussion.\" -Michael Scott",
        151: "\"To avoid illness, expose yourself to germs, enabling your immune system to develop antibodies. I don’t know why everyone doesn’t do this. Maybe they have something against living forever.\" -Dwight Schrute",
        152: "\"It’s never too early for ice cream.\" -Michael Scott",
        153: "\"And I did not become a Lackawanna County volunteer sheriff’s deputy to make friends. And by the way, I haven’t.\" -Dwight Schrute",
        154: "\"Friends joke with one another. ‘Hey, you’re poor.’ ‘Hey, your mama’s dead.’ That’s what friends do.\" -Michael Scott",
        155: "\"If I were buying my coffin, I would get one with thicker walls so you couldn’t hear the other dead people.\" -Dwight Schrute",
        156: "\"I am ready to face any challenge that might be foolish enough to face me.\" -Dwight Schrute",
        157: "\"Do you think that doing alcohol is cool?\" -Michael Scott",
        158: "\"I love catching people in the act. That’s why I always whip open doors.\" -Dwight Schrute",
        159: "\"You know what they say ‘Fool me once, strike one, but fool me twice… strike three.’\" -Michael Scott",
        160: "\"Before I do anything I ask myself, ‘Would an idiot do that?’ And if the answer is yes, I do not do that thing.\" -Dwight Schrute",
        161: "\"I’ve got to make sure that YouTube comes down to tape this.\" -Michael Scott",
        162: "\"Nobody steals from Creed Bratton and gets away with it. The last person to do this disappeared. His name? Creed Bratton.\" -Creed Bratton",
        163: "\"I am Beyonce, always.\" -Michael Scott",
        164: "\"It takes an advanced sense of humor. I don’t expect everyone to understand.\" -Michael Scott",
        165: "\"Tell him to call me ASAP as possible.\" -Michael Scott",
        166: "\"Nobody should have to go to work thinking, ‘Oh, this is the place that I might die today.’ That’s what a hospital is for. An office is for not dying. An office is a place to live life to the fullest. To the max. To… an office is a place where dreams come true.\" -Michael Scott",
        167: "\"Presents are the best way to show how much you care. It’s a tangible thing you can point at and say, ‘Hey man, I love you. This many dollars worth.’\" -Michael Scott",
        168: "\"Sasquatches are the strongest animal on the planet, so fine call me a Sasquatch!\" -Dwight Schrute",
        169: "\"I'm going to do something I've never done at this job before - try.\" -Jim Halpert",
        170: "\"I don’t understand. We have a day honoring Martin Luther King, but he didn’t even work here.\" -Michael Scott",
        171: "\"Nothing stresses me out. Except having to seek the approval of my inferiors.\" -Dwight Schrute",
        172: "\"It just seems awfully mean. But sometimes, the ends justify the mean.\" -Michael Scott",
        173: "\"I learned a while back that if I do not text 911, people do not return my calls. Um, but now people always return my calls because they think that something horrible has happened.\" -Michael Scott",
        174: "\"When Pam gets Michael’s old chair, I get Pam’s old chair. Then I’ll have two chairs. Only one to go.\" -Creed Bratton",
        175: "\"Nobody likes beets, Dwight! Why don’t you grow something that everybody does like? You should grow candy.\" -Michael Scott",
        176: "\"You will not die! Stanley! Stanley! Barack is President! You are black, Stanley!\" -Michael Scott",
        177: "\"I think Angela might be gay. Could Oscar and Angela be having a gay affair? Maybe! Is that what this is about?\" -Michael Scott",
        178: "\"And I feel God in this Chili’s tonight.\" -Pam Beesly",
        179: "\"I hate the idea that someone out there hates me. I even hate thinking that Al Qaeda hates me. I think if they got to know me, they wouldn’t hate me.\" -Pam Beesly",
        180: "\"PowerPoints are the peacocks of the business world; all show, no meat.\" -Dwight Schrute",
        181: "\"I don’t have a lot of experience with vampires, but I have hunted werewolves. I shot one once, but by the time I got to it, it had turned back into my neighbor’s dog.\" -Dwight Schrute",
        182: "\"Fortunately, my feelings regenerate at twice the speed of a normal man’s.\" -Dwight Schrute",
        183: "\"That was offensive and lame. So double offensive. This is an environment of welcoming and you should just get the hell out of here.\" -Michael Scott",
        184: "\"Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.\" -Michael Scott",
        185: "\"My perfect Valentine’s day? I’m at home, three cell phones in front of me, fielding desperate calls from people who want to buy one of the fifty restaurant reservations I made over six months ago.\" -Dwight Schrute",
        186: "\"All you need is love? False. The four basic human necessities are air, water, food, and shelter.\" -Dwight Schrute",
        187: "\"Get a friend, loser.\" -Dwight Schrute",
        188: "\"I had a great summer. I got West Nile virus, lost a ton of weight. Then I went back to the lake. And I stepped on a piece of glass in the parking lot, which hurt. That got infected. Even though I peed on it.\" -Michael Scott",
        189: "\"Dwight, you ignorant slut!\" -Michael Scott",
        190: "\"There was a terrible war, ugh, so many died. Far too many died. But if Frodo hadn’t destroyed the ring, then goodness itself might have died.\" -Dwight Schrute",
        191: "\"Oh, this is gonna feel so good getting this thing off my chest… that’s what she said.\" -Michael Scott",
        192: "\"I am one of the few people who looks hot eating a cupcake.\" -Kelly Kapoor",
        193: "\"Reverse psychology is an awesome tool. I don’t know if you guys know about it, but, basically, you make someone think the opposite of what you believe. And that tricks them into doing something stupid. Works like a charm.\" -Michael Scott",
        194: "\"I took her to the hospital. And the doctors tried to save her life, they did the best they could. And she is going to be OK.\" -Michael Scott",
        195: "\"This is our receptionist, Pam. If you think she’s cute now, you should have seen her a couple years ago.\" -Michael Scott",
        196: "\"Hate to see you leave, but love to watch you go. ‘Cause of your butt.\" -Michael Scott",
        197: "\"Jim couldn’t land me in a thousand years.\" -Dwight Schrute",
        198: "\"If I can’t scuba, then what’s this all been about? What am I working toward?\" -Creed Bratton",
        199: "\"Number eight. Learn how to take off a woman’s bra: You just twist your hand until something breaks.\" -Michael Scott",
        200: "\"There were these huge bins of clothes and everybody was rifling through them like crazy. And I grabbed one and it fit! So, I don’t think that this is totally just a woman’s suit. At the very least it’s bisexual.\" -Michael Scott",
        201: "\"Five minutes ahead of schedule… right on schedule.\" -Dwight Schrute",
        202: "\"Will I get over it? Mmm. No. But life goes on.\" -Dwight Schrute",
        203: "\"Jim is my enemy. But it turns out that Jim is also his own worst enemy. And the enemy of my enemy is my friend. So, Jim is actually my friend. But because he is his own worst enemy, the enemy of my friend is my enemy so, actually, Jim is my enemy.\" -Dwight Schrute",
        204: "\"A real man swallows his vomit when a lady is present.\" -Dwight Schrute",
        205: "\"I know it’s illegal in Pennsylvania, but it’s for charity, and I consider myself a great philanderer.\" -Michael Scott",
        206: "\"They always say that it’s a mistake to hire your friends. And they are right. So, I hired my best friends. And this is what I get!?\" -Michael Scott",
        207: "\"You cheated on me? When I specifically asked you not to?\" -Michael Scott",
        208: "\"Welcome to the Hotel Hell. Check-in time is now. Check-out time is never.\" -Dwight Schrute"
        209: "\"It’s not like booze ever killed anyone.\" -Michael Scott",
        210: "\"It’s better to be hurt by someone you know accidentally, than by a stranger on purpose.\" -Dwight Schrute",
        211: "\"You are as creepy as a real serial killer. For real.\" -Michael Scott",
        212: "\"It’s a pimple, Phyllis. Avril Lavigne gets them all the time, and she rocks harder than anyone alive.\" -Michael Scott",
        213: "\"The hand that reaches from the grave to grip your throat is the strong hand you want on the wheel.\" -Dwight Schrute",
        214: "\"I wonder if king-sized sheets are called presidential-sized in England.\" -Dwight Schrute",
        215: "\"It’s not effeminate. It’s festive.\" -Dwight Schrute",
        216: "\"No, Rose, they are not breathing. And they have no arms or legs… Where are they? You know what? If we come across somebody with no arms or legs, do we bother resuscitating them? I mean, what quality of life do we have there?\" -Michael Scott",
        217: "\"It's like I used to tell my wife: I do not apologize unless I think I'm wrong, and if you don't like it, you can leave. I say the same thing to my current wife, and I'll say it to my next one too.\" -Stanley Hudson",
        218: "\"Like right here is my favorite New York pizza joint. And I’m going to go get me a New York slice.\" -Michael Scott",
        219: "\"A hero kills people, people that wish him harm. A hero is part human and part supernatural. A hero is born out of a childhood trauma, or out of a disaster, that must be avenged.\" -Dwight Schrute",
        220: "\"I wanna be married and have 100 kids so I can have 100 friends and no one can say ‘no’ to being my friend.\" -Michael Scott",
        221: "\"And I misspelled, in front of the entire school, the word ‘failure.’\" -Dwight Schrute",
        222: "\"Dolphins get a lot of good publicity for the drowning swimmers they push back to shore, but what you don’t hear about is the many people they push farther out to sea! Dolphins aren’t smart. They just like pushing things.\" -Dwight Schrute",
        223: "\"My philosophy is, basically this. And this is something that I live by. And I always have. And I always will. Don’t, ever, for any reason, do anything, to anyone, for any reason, ever, no matter what, no matter where, or who you are with, or, or where you are going, or, or where you’ve been. Ever. For any reason. Whatsoever.\" -Michael Scott",
        224: "\"Do I need to be liked? Absolutely not. I like to be liked. I enjoy being liked. I have to be liked, but it’s not like this compulsive need to be liked, like my need to be praised.\" -Michael Scott",
        225: "\"Saw Inception. Or at least I dreamt I did.\" -Michael Scott",
        226: "\"It is St. Patrick’s Day. And here in Scranton, that is a huge deal. It is the closest that the Irish will ever get to Christmas.\" -Michael Scott",
        227: "\"They say on your deathbed you never wish you spent more time at the office — but I will.\" -Michael Scott",
        228: "\"I already won the lottery. I was born in the US of A, baby. And as backup, I have a Swiss passport.\" -Creed Bratton",
        229: "\"This day is BANANAS! B-A-N-A-N-A-S!\" -Kelly Kapoor",
        230: "\"I miss Dwight. Congratulations Universe, you win.\" -Jim Halpert",
        231: "\"Wikipedia is the best thing ever. Anyone in the world can write anything they want about any subject. So you know you are getting the best possible information.\" -Michael Scott",
        232: "\"I have cause. It’s beCAUSE I hate him.\" -Michael Scott",
        233: "\"The rules of shotgun are very simple and very clear. The first person to shout ‘shotgun’ when you’re within sight of the car gets the front seat. That’s how the game’s played. There are no exceptions for someone with a concussion.\" -Michael Scott",
        234: "\"To avoid illness, expose yourself to germs, enabling your immune system to develop antibodies. I don’t know why everyone doesn’t do this. Maybe they have something against living forever.\" -Dwight Schrute",
        235: "\"It’s never too early for ice cream.\" -Michael Scott",
        236: "\"And I did not become a Lackawanna County volunteer sheriff’s deputy to make friends. And by the way, I haven’t.\" -Dwight Schrute",
        237: "\"Friends joke with one another. ‘Hey, you’re poor.’ ‘Hey, your mama’s dead.’ That’s what friends do.\" -Michael Scott",
        238: "\"If I were buying my coffin, I would get one with thicker walls so you couldn’t hear the other dead people.\" -Dwight Schrute",
        239: "\"I am ready to face any challenge that might be foolish enough to face me.\" -Dwight Schrute",
        240: "\"Do you think that doing alcohol is cool?\" -Michael Scott",
        241: "\"I love catching people in the act. That’s why I always whip open doors.\" -Dwight Schrute",
        242: "\"You know what they say ‘Fool me once, strike one, but fool me twice… strike three.’\" -Michael Scott",
        243: "\"Before I do anything I ask myself, ‘Would an idiot do that?’ And if the answer is yes, I do not do that thing.\" -Dwight Schrute",
        244: "\"I’ve got to make sure that YouTube comes down to tape this.\" -Michael Scott",
        245: "\"Nobody steals from Creed Bratton and gets away with it. The last person to do this disappeared. His name? Creed Bratton.\" -Creed Bratton",
        246: "\"I am Beyonce, always.\" -Michael Scott",
        247: "\"It takes an advanced sense of humor. I don’t expect everyone to understand.\" -Michael Scott",
        248: "\"Tell him to call me ASAP as possible.\" -Michael Scott",
        249: "\"Nobody should have to go to work thinking, ‘Oh, this is the place that I might die today.’ That’s what a hospital is for. An office is for not dying. An office is a place to live life to the fullest. To the max. To… an office is a place where dreams come true.\" -Michael Scott",
        250: "\"Presents are the best way to show how much you care. It’s a tangible thing you can point at and say, ‘Hey man, I love you. This many dollars worth.’\" -Michael Scott",
        251: "\"Sasquatches are the strongest animal on the planet, so fine call me a Sasquatch!\" -Dwight Schrute",
        252: "\"I'm going to do something I've never done at this job before - try.\" -Jim Halpert",
        253: "\"I don’t understand. We have a day honoring Martin Luther King, but he didn’t even work here.\" -Michael Scott",
        254: "\"Nothing stresses me out. Except having to seek the approval of my inferiors.\" -Dwight Schrute",
        255: "\"It just seems awfully mean. But sometimes, the ends justify the mean.\" -Michael Scott",
        256: "\"I learned a while back that if I do not text 911, people do not return my calls. Um, but now people always return my calls because they think that something horrible has happened.\" -Michael Scott",
        257: "\"When Pam gets Michael’s old chair, I get Pam’s old chair. Then I’ll have two chairs. Only one to go.\" -Creed Bratton",
        258: "\"Nobody likes beets, Dwight! Why don’t you grow something that everybody does like? You should grow candy.\" -Michael Scott",
        259: "\"You will not die! Stanley! Stanley! Barack is President! You are black, Stanley!\" -Michael Scott",
        260: "\"I think Angela might be gay. Could Oscar and Angela be having a gay affair? Maybe! Is that what this is about?\" -Michael Scott",
        261: "\"And I feel God in this Chili’s tonight.\" -Pam Beesly",
        262: "\"I hate the idea that someone out there hates me. I even hate thinking that Al Qaeda hates me. I think if they got to know me, they wouldn’t hate me.\" -Pam Beesly",
        263: "\"PowerPoints are the peacocks of the business world; all show, no meat.\" -Dwight Schrute",
        264: "\"I don’t have a lot of experience with vampires, but I have hunted werewolves. I shot one once, but by the time I got to it, it had turned back into my neighbor’s dog.\" -Dwight Schrute",
        265: "\"Fortunately, my feelings regenerate at twice the speed of a normal man’s.\" -Dwight Schrute",
        266: "\"That was offensive and lame. So double offensive. This is an environment of welcoming and you should just get the hell out of here.\" -Michael Scott",
        267: "\"Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.\" -Michael Scott",
        268: "\"My perfect Valentine’s day? I’m at home, three cell phones in front of me, fielding desperate calls from people who want to buy one of the fifty restaurant reservations I made over six months ago.\" -Dwight Schrute",
        269: "\"All you need is love? False. The four basic human necessities are air, water, food, and shelter.\" -Dwight Schrute",
        270: "\"Get a friend, loser.\" -Dwight Schrute",
        271: "\"I had a great summer. I got West Nile virus, lost a ton of weight. Then I went back to the lake. And I stepped on a piece of glass in the parking lot, which hurt. That got infected. Even though I peed on it.\" -Michael Scott",
        272: "\"Hi, I’m Date Mike. Nice to meet me. How do you like your eggs in the morning?\" -Michael Scott",
        273: "\"There was a terrible war, ugh, so many died. Far too many died. But if Frodo hadn’t destroyed the ring, then goodness itself might have died.\" -Dwight Schrute",
        274: "\"Oh, this is gonna feel so good getting this thing off my chest… that’s what she said.\" -Michael Scott",
        275: "\"I am one of the few people who looks hot eating a cupcake.\" -Kelly Kapoor",
        276: "\"Reverse psychology is an awesome tool. I don’t know if you guys know about it, but, basically, you make someone think the opposite of what you believe. And that tricks them into doing something stupid. Works like a charm.\" -Michael Scott",
        277: "\"I took her to the hospital. And the doctors tried to save her life, they did the best they could. And she is going to be OK.\" -Michael Scott",
        278: "\"This is our receptionist, Pam. If you think she’s cute now, you should have seen her a couple years ago.\" -Michael Scott",
        279: "\"Hate to see you leave, but love to watch you go. ‘Cause of your butt.\" -Michael Scott",
        280: "\"Jim couldn’t land me in a thousand years.\" -Dwight Schrute",
        281: "\"If I can’t scuba, then what’s this all been about? What am I working toward?\" -Creed Bratton",
        282: "\"I’m screaming! I’m screaming! I’m screaming! Aah! Numb me up! I want anesthesia!\" -Dwight Schrute",
        283: "\"I don’t care what Jim says. This is NOT the real Ben Franklin. I am 99.9 percent sure.\" -Dwight Schrute",
        284: "\"OK. When the baby emerges, mark it secretly in a kind of a mark that only you could recognize and no baby snatcher could ever copy.\" -Dwight Schrute",
        285: "\"I live by one rule: No office romances, no way. Very messy, inappropriate… no. But, I live by another rule: Just do it… Nike.\" -Michael Scott",
        286: "\"I say dance, they say ‘How high?'\" -Michael Scott",
        287: "\"He’s gone. I miss him so much. Oh, I cry myself to sleep, Jim. False. I do not miss him.\" -Dwight Schrute",
        288: "\"It takes you thirty seconds to brush your teeth? Wow, that’s ten times as long as it takes me.\" -Michael Scott",
        289: "\"I find the mystery genre disgusting. I hate being titillated.\" -Angela Martin",
        290: "\"I feel like all my kids grew up and then they married each other. It’s every parent’s dream.\" -Michael Scott",
    }



    tweet_text = office_quotes[random.randint(0,len(office_quotes)-1)]
    ran = random.random()
    if ran < 0.3:
        tweet_text += " #TheOffice"
    elif ran < 0.35:
        tweet_text += " #MichaelScott"

    client.create_tweet(text=tweet_text)
